language: python

python:
  - "3.7"
  - "3.8"
  - "3.9"

before_install:
  - python -m pip install --upgrade pip setuptools wheel
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
  - pip install -U numpy
install:
  - python setup.py sdist
script:
  - pytest -v .

notifications:
  email:
    recipients:
      - samuelreay@gmail.com
    on_failure: always
