# Having computed the maps, this file will then show us our progress from before to after
# for all the dimensionality we have in our maps. This will also help pick which sigma clipping we should use
# and verify against the 3yr and 5yr data.

# Oh, and it will allow us to look at the amount of correlation we should be adding.
# This is a huge config, and it will take a long time to run.




# Oh btw, I used YAML anchoring and aliasing in here. How good is it. Just adding it here so its easy to see
ANCHORS:  # The name of this doesnt actually matter, its all about the & and *

  DEFAULT_SIM_MAP: &default_map
    FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_SIM_ERRORFUDGES_DIFFIMG_SBMAG_5_0.DAT
    RANSEED_REPEAT: 1 12345

  DEFAULT_CORR: &default_corr
    FLUXERRMODEL_REDCOV(DEEP): "g:0.05,r:0.05,i:0.05,z:0.05"
    FLUXERRMODEL_REDCOV(SHALLOW): "griz:0.25"

  FAKES_INPUT: &fakesinput
    BASE: surveys/des/sims_ia/fakes_diffimg.input

  FITOPTS: &default_fitopts
    BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 10
    APPEND_TABLE_TEXT: SNRMAX_g SNRMAX_r SNRMAX_i SNRMAX_z chi2_g chi2_r chi2_i chi2_z

  SNLCINP: &default_mapdata
    FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_FAKES_ERRORFUDGES_DIFFIMG_SBMAG_5_0.DAT

  DESLIKESIM: &deslikesim
    IA_G10:
      BASE: surveys/des/sims_ia/sn_ia_salt2_g10_des5yr.input
    IAX:
      BASE: surveys/des/sims_cc/sn_iax_dust.input
    IA91BG:
      BASE: surveys/des/sims_cc/sn_ia91bg.input
    CC_TEMPLATES:
      BASE: surveys/des/sims_cc/sn_collection_maria_dust1.input


DATAPREP:
  FAKES:
    OPTS:
      RAW_DIR: $DES_ROOT/lcmerge/DESALL_forcePhoto_fake_snana_fits
  DATADES3YR:
    OPTS:
      RAW_DIR: $DES_ROOT/lcmerge/DESALL_specType_SMP_real_snana_fits
      TYPES:
        IA: [1, 101]
        NONIA: [120, 130, 20, 30]
  DATADES5YR:
    OPTS:
      RAW_DIR: $DES_ROOT/lcmerge/DESALL_forcePhoto_real_snana_fits
      TYPES:
        IA: [1, 101]
        NONIA: [120, 130, 20, 30]


SIM:
  # Simulate just the fakes with no correction
  SIMFAKES_NOCORR:
    IA:
      BASE: surveys/des/sims_ia/fakes_diffimg.input
    GLOBAL:
      FLUXERRMODEL_FILE: NONE
      RANSEED_REPEAT: 1 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 1


  # Great, so that should allow a good mix for the correlation to be determined
  # broken down by deep and shallow fields. Lets simulate this mix
  SIMFAKE_1D_MIX_0:
    IA: *fakesinput
    GLOBAL:
      <<: *default_map
      <<: *default_corr
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 1

  SIMFAKE_1D_MIX_1:
    IA:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_SIM_ERRORFUDGES_DIFFIMG_SBMAG_5_1.DAT
      RANSEED_REPEAT: 1 12345
    GLOBAL:
      <<: *default_map
      <<: *default_corr
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 1



  # Lets also compare the 1D, 2D and 3D maps with the fakes without correlations
  SIMFAKE_1D_CORR_ALL00:
    IA: *fakesinput
    GLOBAL:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_SIM_ERRORFUDGES_DIFFIMG_SBMAG_5.DAT
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 1

  SIMFAKE_2D_CORR_ALL00:
    IA: *fakesinput
    GLOBAL:
      <<: *default_map
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 1

  SIMFAKE_3D_CORR_ALL00:
    IA: *fakesinput
    GLOBAL:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_SIM_ERRORFUDGES_DIFFIMG_LOGSNR_SBMAG_PSF_5.DAT
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 1





  # 5yr sims
  SIMDES5YR_2D_REDCOV:
    <<: *deslikesim
    GLOBAL:
      <<: *default_map
      <<: *default_corr
      NGEN_UNIT: 1
      RANSEED_REPEAT: 5 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 5

  SIMDES5YR_2D_INDCOV:
    <<: *deslikesim
    GLOBAL:
      <<: *default_map
      NGEN_UNIT: 1
      RANSEED_REPEAT: 5 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 5

  SIMDES5YR_1D_REDCOV:
    <<: *deslikesim
    GLOBAL:
      <<: *default_corr
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_SIM_ERRORFUDGES_DIFFIMG_SBMAG_5.DAT
      RANSEED_REPEAT: 5 12345
      NGEN_UNIT: 1
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 5

  SIMDES5YR_1D_INDCOV:
    <<: *deslikesim
    GLOBAL:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_SIM_ERRORFUDGES_DIFFIMG_SBMAG_5.DAT
      RANSEED_REPEAT: 5 12345
      NGEN_UNIT: 1
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 5

  SIMDES5YR_3D_REDCOV:
    <<: *deslikesim
    GLOBAL:
      <<: *default_corr
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_SIM_ERRORFUDGES_DIFFIMG_LOGSNR_SBMAG_PSF_5.DAT
      RANSEED_REPEAT: 5 12345
      NGEN_UNIT: 1
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 5

  SIMDES5YR_3D_INDCOV:
    <<: *deslikesim
    GLOBAL:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_SIM_ERRORFUDGES_DIFFIMG_LOGSNR_SBMAG_PSF_5.DAT
      RANSEED_REPEAT: 5 12345
      NGEN_UNIT: 1
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 5



# Now we have to fit everything. For the SIMFAKES, we'll fit using the fakes.nml
# For the DES-like sims, we'll fit using surveys/des/lcfit_nml/des_5yr.nml
LCFIT:

  # Fit the fakes and the fake sims
  F0D:  # ie fit fakes, 0D = no correction
    BASE: surveys/des/lcfit_nml/fakes.nml
    MASK: FAKES
    SNLCINP:
      FLUXERRMODEL_FILE: NONE
    OPTS: *default_fitopts

  F1D: # fit fakes using the 2D correction, which only apples to the real fakes, not the sims
    BASE: surveys/des/lcfit_nml/fakes.nml
    MASK: FAKE
    SNLCINP: *default_mapdata
    OPTS: *default_fitopts

  F1D1: # fit fakes using the 2D correction, which only apples to the real fakes, not the sims
    BASE: surveys/des/lcfit_nml/fakes.nml
    MASK: FAKES
    SNLCINP:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_FAKES_ERRORFUDGES_DIFFIMG_SBMAG_5_1.DAT
    OPTS: *default_fitopts


  # Fit the DES sims
  D0D: # fit fakes using the 2D correction, which only apples to the real fakes, not the sims
    BASE: surveys/des/lcfit_nml/des_5yr.nml
    MASK: DATADES
    SNLCINP:
      FLUXERRMODEL_FILE: NONE
      ROOTFILE_OUT: FIT.ROOT
    OPTS: *default_fitopts

  D1D0: # fit fakes using the 2D correction, which only apples to the real fakes, not the sims
    BASE: surveys/des/lcfit_nml/des_5yr.nml
    MASK: DATADES
    SNLCINP:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_FAKES_ERRORFUDGES_DIFFIMG_SBMAG_5_0.DAT
      ROOTFILE_OUT: FIT.ROOT
    OPTS: *default_fitopts

  D1D1: # fit fakes using the 2D correction, which only apples to the real fakes, not the sims
    BASE: surveys/des/lcfit_nml/des_5yr.nml
    MASK: DATADES
    SNLCINP:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_FAKES_ERRORFUDGES_DIFFIMG_SBMAG_5_1.DAT
      ROOTFILE_OUT: FIT.ROOT
    OPTS: *default_fitopts

  D2D: # fit fakes using the 2D correction, which only apples to the real fakes, not the sims
    BASE: surveys/des/lcfit_nml/des_5yr.nml
    MASK: DES
    SNLCINP:
      <<: *default_mapdata
      ROOTFILE_OUT: FIT.ROOT
    OPTS: *default_fitopts

  D3D: # fit fakes using the 2D correction, which only apples to the real fakes, not the sims
    BASE: surveys/des/lcfit_nml/des_5yr.nml
    MASK: DATADES
    SNLCINP:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_FAKES_ERRORFUDGES_DIFFIMG_LOGSNR_SBMAG_PSF_5.DAT
      ROOTFILE_OUT: FIT.ROOT
    OPTS: *default_fitopts
ANALYSE:

  CHECK_FAKES:
    HISTOGRAM:
      - F1D_FAKES
      - F1D1_FAKES
      - F1D_SIMFAKE_1D_MIX_0
      - F1D_SIMFAKE_1D_MIX_1

  CHECK_FAKES_BEFORE_AFTER:
    HISTOGRAM:
      - F0D_FAKES
      - F1D_SIMFAKES_NOCORR
      - F1D_FAKES
      - F1D_SIMFAKE_1D_MIX

  CHECK_5YR_DIST_1D:
    HISTOGRAM:
      - D1D0_DATADES5YR
      - D1D1_DATADES5YR
      - D2D_SIMDES5YR_1D_REDCOV
      - D2D_SIMDES5YR_1D_INDCOV

  CHECK_5YR_DIST_2D:
    HISTOGRAM:
      - D2D_DATADES5YR
      - D2D_SIMDES5YR_2D_REDCOV
      - D2D_SIMDES5YR_2D_INDCOV

  CHECK_5YR_DIST_3D:
    HISTOGRAM:
      - D3D_DATADES5YR
      - D2D_SIMDES5YR_3D_REDCOV
      - D2D_SIMDES5YR_3D_INDCOV
