SIM:
  DESSIMBIAS3YRIA_G10:
    EXTERNAL: $PIPPIN_OUTPUT/SRH_TEST_EXTERNAL_SOURCE/1_SIM/DESSIMBIAS3YRIA_G10

LCFIT:
  MASK: DESSIMBIAS3YRIA_G10
  D:
    EXTERNAL: $PIPPIN_OUTPUT/SRH_TEST_EXTERNAL_SOURCE/2_LCFIT/D_DESSIMBIAS3YRIA_G10