SIM:
  DES_G10:
    IA_G10:
      BASE: surveys/des/sims_ia/sn_ia_salt2_g10_des3yr.input
    GLOBAL:
      NGEN_UNIT: 2
  DESSIMBIAS3YRIA_C11:
    EXTERNAL: $PIPPIN_OUTPUT/GLOBAL/1_SIM/DESSIMBIAS3YRIA_C11
  DESSIMBIAS3YRIA_G10:
    EXTERNAL: $PIPPIN_OUTPUT/GLOBAL/1_SIM/DESSIMBIAS3YRIA_G10

LCFIT:
  D:
    BASE: surveys/des/lcfit_nml/des_3yr.nml
    MASK: DES
    SNLCINP:
      USE_MINOS: F
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 20
    EXTERNAL_DIRS:
      - $PIPPIN_OUTPUT/GLOBAL/2_LCFIT/D_DESSIMBIAS3YRIA_C11
      - $PIPPIN_OUTPUT/GLOBAL/2_LCFIT/D_DESSIMBIAS3YRIA_G10

AGGREGATION:
  AGG:
    EXTERNAL_DIRS:
      - $PIPPIN_OUTPUT/GLOBAL/4_AGG/AGG_DESSIMBIAS3YRIA_C11
      - $PIPPIN_OUTPUT/GLOBAL/4_AGG/AGG_DESSIMBIAS3YRIA_G10
MERGE:
  MERGE:
    EXTERNAL_DIRS:
      - $PIPPIN_OUTPUT/GLOBAL/5_MERGE/MERGE_D_DESSIMBIAS3YRIA_C11
      - $PIPPIN_OUTPUT/GLOBAL/5_MERGE/MERGE_D_DESSIMBIAS3YRIA_G10

BIASCOR:
  3YR:
    BASE: surveys/des/bbc/bbc_3yr.input
    DATA: [D_DES_G10]
    SIMFILE_BIASCOR: [D_DESSIMBIAS3YRIA_G10]
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 5
      chi2max: 16

CREATE_COV:
  ALL:
    OPTS:

COSMOMC:
  SN_OMW:
    OPTS:
      INI: sn_prior_omw.ini

#
#CREATE_COV:
#  ALL:
#    OPTS:
#      COVOPTS:
#        - "[NOSYS] [=DEFAULT,=DEFAULT]"
#
#
#COSMOMC:
#  SN_OMW:
#    OPTS:
#      INI: sn_omw
#      COVOPTS: [ALL, NOSYS]
#      NUM_WALKERS: 40
#
#  SN_CMB_OMW:
#    OPTS:
#      INI: sn_cmb_omw
#      COVOPTS: [ALL]
#      NUM_WALKERS: 20
#
#  CMB_OMW:
#    OPTS:
#      INI: cmb_omw
#
#ANALYSE:
#  ALL_OMW:
#    MASK_COSMOMC: OMW

