SIM:
  DESSIMBIAS3YRIA_G10:
    EXTERNAL: $PIPPIN_OUTPUT/SRH_TEST_EXTERNAL_SOURCE/1_SIM/DESSIMBIAS3YRIA_G10

LCFIT:
  D:
    MASK: DESSIMBIAS3YRIA_G10
    BASE: surveys/des/lcfit_nml/des_5yr.nml
    EXTERNAL: $PIPPIN_OUTPUT/SRH_TEST_EXTERNAL_SOURCE/2_LCFIT/D_DESSIMBIAS3YRIA_G10


CLASSIFICATION:
  UNITY:
    MASK_FIT: D_DESSIMBIAS3YRIA_G10
    CLASSIFIER: UnityClassifier
    MODE: predict
    EXTERNAL: $PIPPIN_OUTPUT/SRH_TEST_EXTERNAL_SOURCE/3_CLAS/UNITY_DESSIMBIAS3YRIA_G10

AGGREGATION:
  AGG:
    MASK_SIM: DESSIMBIAS3YRIA_G10
    EXTERNAL: $PIPPIN_OUTPUT/SRH_TEST_EXTERNAL_SOURCE/4_AGG/AGG_DESSIMBIAS3YRIA_G10

MERGE:
  MERGE:
    MASK_FIT: D_DESSIMBIAS3YRIA_G10
    EXTERNAL: $PIPPIN_OUTPUT/SRH_TEST_EXTERNAL_SOURCE/5_MERGE/MERGE_D_DESSIMBIAS3YRIA_G10
