DATAPREP:
  DESSIMBIAS5YRIA_C11:
    OPTS:
      RAW_DIR: $SCRATCH_SIMDIR/PIP_GLOBAL_BIASCOR_DESSIMBIAS5YRIA_C11
  DESSIMBIAS5YRIA_G10:
    OPTS:
      RAW_DIR: $SCRATCH_SIMDIR/PIP_GLOBAL_BIASCOR_DESSIMBIAS5YRIA_G10
  DESSIMBIAS5YRCC:
    OPTS:
      RAW_DIR: $SCRATCH_SIMDIR/PIP_GLOBAL_BIASCOR_DESSIMBIAS5YRCC

SIM:
  SIMDATADES5YR:
    IA_G10:
      BASE: surveys/des/sims_ia/sn_ia_salt2_g10_des5yr.input
    IAX:
      BASE: surveys/des/sims_cc/sn_iax_dust.input
    IA91BG:
      BASE: surveys/des/sims_cc/sn_ia91bg.input
    CC_TEMPLATES:
      BASE: surveys/des/sims_cc/sn_collection_maria_dust1.input
    GLOBAL:
      NGEN_UNIT: 0.1
      RANSEED_REPEAT: 10 12345

LCFIT:
  DS:
    BASE: surveys/des/lcfit_nml/des_5yr.nml
    MASK: DATADES
    FITOPTS: surveys/global/lcfit_fitopts/global.yml
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 20

  # For the biascor sims, fit without fitopt
  D:
    BASE: surveys/des/lcfit_nml/des_5yr.nml
    MASK: DESSIM
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 40

CLASSIFICATION:
  # Load the existing SNN classifier from GLOBAL_ML
  SNNTEST:
    CLASSIFIER: SuperNNovaClassifier
    MODE: predict
    OPTS:
      MODEL: $PIPPIN_OUTPUT/GLOBAL_ML/3_CLAS/SNNTRAIN_TRAININGSIM/model.pt
  SNIRFTEST:
    CLASSIFIER: SnirfClassifier
    MODE: predict
    OPTS:
      MODEL: $PIPPIN_OUTPUT/GLOBAL_ML/3_CLAS/SNIRFTRAIN_TESTFIT_TRAININGSIM/model.pkl
  UNITY:
    CLASSIFIER: UnityClassifier
    MODE: predict


AGGREGATION:
  AGG:

MERGE:
  MERGE:

BIASCOR:
  5YR:
    DATA: [DS_SIMDATADES5YR]
    SIMFILE_BIASCOR: [D_DESSIMBIAS5YRIA_G10]
    SIMFILE_CCPRIOR: D_DESSIMBIAS5YRCC
    CLASSIFIER: SNNTEST
    MUOPTS:
      SCATTER_C11:
        SIMFILE_BIASCOR: [D_DESSIMBIAS5YRIA_C11]
      CLAS_SNIRF:
        CLASSIFIER: SNIRFTEST
      PROB_CUT_05:
        OPTS:
          CUTWIN_PROB_IA: 0.5 1.0
      PROB_CUT_08:
        OPTS:
          CUTWIN_PROB_IA: 0.8 1.0
      CHI2MAX_100:
        OPTS:
          chi2max: 100
      CCPRIORBINS:

    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 5

CREATE_COV:
  ALL:
    OPTS:
      COVOPTS:
        - "[NOSYS] [=DEFAULT,=DEFAULT]"
        - "[SALT] [+SALT,=DEFAULT]"
        - "[CAL] [+survcal,=DEFAULT]"
        - "[SCATTER] [=DEFAULT,+SCATTER]"
        - "[DUST] [=MWEBV,=DEFAULT]"
        - "[CLASSIFICATION] [=DEFAULT,+CLAS]"
        - "[ZSHIFT] [+zshift,=DEFAULT]"
        - "[VPEC] [+VPEC,=DEFAULT]"
        - "[HSTCAL] [+HST_cal,=DEFAULT]"


COSMOMC:
  SN_OMW:
    OPTS:
      INI: sn_prior_omw
      NUM_WALKERS: 20


ANALYSE:
  ALL_OMW:
    MASK_COSMOMC: OMW

