# We want to make sure that our uncorrelated fudge maps actually bring distributions
# like SNRMAX into line. We expect FITPROB to still be off at this stage, but we want
# to nail everything else before continuing.

ANCHORS:
  FAKES_INPUT: &fakesinput
    BASE: surveys/des/sims_ia/fakes_diffimg.input
  FITOPTS: &default_fitopts
    BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 20
    APPEND_TABLE_TEXT: SNRMAX_g SNRMAX_r SNRMAX_i SNRMAX_z chi2_g chi2_r chi2_i chi2_z


DATAPREP:
  DATAFAKES:
    OPTS:
      RAW_DIR: $DES_ROOT/lcmerge/DESALL_forcePhoto_fake_snana_fits


SIM:
  SIMFAKE_NOCORRECTION:
    IA:
      BASE: surveys/des/sims_ia/fakes_diffimg.input
    GLOBAL:
      FLUXERRMODEL_FILE: NONE
      RANSEED_REPEAT: 1 12345

  SIMFAKE_1D_CORRECTION_F0:
    IA: *fakesinput
    GLOBAL:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_SIM_ERRORFUDGES_DIFFIMG_SBMAG_5_0.DAT
      RANSEED_REPEAT: 1 12345

  SIMFAKE_1D_CORRECTION_F1:
    IA: *fakesinput
    GLOBAL:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_SIM_ERRORFUDGES_DIFFIMG_SBMAG_5_1.DAT
      RANSEED_REPEAT: 1 12345

  SIMFAKE_2D_CORRECTION_F0:
    IA: *fakesinput
    GLOBAL:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_SIM_ERRORFUDGES_DIFFIMG_LOGSNR_SBMAG_5_0.DAT
      RANSEED_REPEAT: 1 12345

  SIMFAKE_2D_CORRECTION_F1:
    IA: *fakesinput
    GLOBAL:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_SIM_ERRORFUDGES_DIFFIMG_LOGSNR_SBMAG_5_1.DAT
      RANSEED_REPEAT: 1 12345


  SIMFAKE_3D_CORRECTION_F0:
    IA: *fakesinput
    GLOBAL:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_SIM_ERRORFUDGES_DIFFIMG_LOGSNR_SBMAG_PSF_5.DAT
      RANSEED_REPEAT: 1 12345

  SIMFAKE_3D_CORRECTION_F1:
    IA: *fakesinput
    GLOBAL:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_SIM_ERRORFUDGES_DIFFIMG_LOGSNR_SBMAG_PSF_5.DAT
      RANSEED_REPEAT: 1 12345

LCFIT:

  F0D:
    BASE: surveys/des/lcfit_nml/fakes.nml
    MASK: [DATAFAKES, SIMFAKE_NOCORRECTION]
    SNLCINP:
      FLUXERRMODEL_FILE: NONE
    OPTS: *default_fitopts

  F1D0:
    BASE: surveys/des/lcfit_nml/fakes.nml
    MASK: [DATAFAKES, SIMFAKE_1D_CORRECTION_F0]
    SNLCINP:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_FAKES_ERRORFUDGES_DIFFIMG_SBMAG_5_0.DAT
    OPTS: *default_fitopts

  F1D1:
    BASE: surveys/des/lcfit_nml/fakes.nml
    MASK: [DATAFAKES, SIMFAKE_1D_CORRECTION_F1]
    SNLCINP:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_FAKES_ERRORFUDGES_DIFFIMG_SBMAG_5_1.DAT
    OPTS: *default_fitopts

  F2D0:
    BASE: surveys/des/lcfit_nml/fakes.nml
    MASK: [DATAFAKES, SIMFAKE_2D_CORRECTION_F0]
    SNLCINP:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_FAKES_ERRORFUDGES_DIFFIMG_LOGSNR_SBMAG_5_0.DAT
    OPTS: *default_fitopts

  F2D1:
    BASE: surveys/des/lcfit_nml/fakes.nml
    MASK: [DATAFAKES, SIMFAKE_2D_CORRECTION_F1]
    SNLCINP:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_FAKES_ERRORFUDGES_DIFFIMG_LOGSNR_SBMAG_5_1.DAT
    OPTS: *default_fitopts

  F3D0:
    BASE: surveys/des/lcfit_nml/fakes.nml
    MASK: [DATAFAKES, SIMFAKE_3D_CORRECTION_F0]
    SNLCINP:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_FAKES_ERRORFUDGES_DIFFIMG_LOGSNR_SBMAG_PSF_5_0.DAT
    OPTS: *default_fitopts

  F3D1:
    BASE: surveys/des/lcfit_nml/fakes.nml
    MASK: [DATAFAKES, SIMFAKE_3D_CORRECTION_F1]
    SNLCINP:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_FAKES_ERRORFUDGES_DIFFIMG_LOGSNR_SBMAG_PSF_5_1.DAT
    OPTS: *default_fitopts

ANALYSE:

  SANITY_0D:
    MASK_LCFIT:
      - F0D0_DATAFAKES
      - F0D0_SIMFAKE_NOCORRECTION_F0
      - F0D1_DATAFAKES
      - F0D1_SIMFAKE_NOCORRECTION_F1

  SANITY_1D:
    MASK_LCFIT:
      - F1D0_DATAFAKES
      - F1D0_SIMFAKE_1D_CORRECTION_F0
      - F1D1_DATAFAKES
      - F1D1_SIMFAKE_1D_CORRECTION_F1

  SANITY_2D:
    MASK_LCFIT:
      - F2D0_DATAFAKES
      - F2D0_SIMFAKE_2D_CORRECTION_F0
      - F2D1_DATAFAKES
      - F2D1_SIMFAKE_2D_CORRECTION_F1

  SANITY_3D:
    MASK_LCFIT:
      - F3D0_DATAFAKES
      - F3D0_SIMFAKE_3D_CORRECTION_F0
      - F3D1_DATAFAKES
      - F3D1_SIMFAKE_3D_CORRECTION_F1