DATAPREP:
  DESSIMBIAS5YRIA_C11:
    OPTS:
      RAW_DIR: $SCRATCH_SIMDIR/PIP_GLOBAL_BIASCOR_DESSIMBIAS5YRIA_C11
  DESSIMBIAS5YRIA_G10:
    OPTS:
      RAW_DIR: $SCRATCH_SIMDIR/PIP_GLOBAL_BIASCOR_DESSIMBIAS5YRIA_G10
  DESSIMBIAS5YRCC:
    OPTS:
      RAW_DIR: $SCRATCH_SIMDIR/PIP_GLOBAL_BIASCOR_DESSIMBIAS5YRCC
  LOWZSIMBIAS_G10:
    OPTS:
      RAW_DIR: $SCRATCH_SIMDIR/PIP_GLOBAL_BIASCOR_LOWZSIMBIAS
  LOWZSIMBIAS_C11:
    OPTS:
      RAW_DIR: $SCRATCH_SIMDIR/PIP_GLOBAL_BIASCOR_LOWZSIMBIAS_C11

SIM:
  SIMDATADES5YR:
    IA_G10:
      BASE: surveys/des/sims_ia/sn_ia_salt2_g10_des5yr.input
      HOSTLIB_FILE: $DES_ROOT/simlibs/DES-NEWMASS-v3.HOSTLIB
      HOSTLIB_WGTMAP_FILE: $DES_ROOT/simlibs/OG_WGTMAP.DAT
      HOSTLIB_MSKOPT: 326
    IAX:
      BASE: surveys/des/sims_cc/sn_iax_dust.input
    IA91BG:
      BASE: surveys/des/sims_cc/sn_ia91bg.input
    CC_TEMPLATES:
      BASE: surveys/des/sims_cc/sn_collection_maria_dust1.input
    GLOBAL:
      NGEN_UNIT: 0.1
      RANSEED_REPEAT: 10 12345

  SIMDATALOWZ:
    IA_G10:
      BASE: surveys/lowz/sims_ia/sn_ia_salt2_g10_lowz.input
    GLOBAL:
      NGEN_UNIT: 0.1
      RANSEED_REPEAT: 10 12345



LCFIT:
  DS:
    BASE: surveys/des/lcfit_nml/des_5yr.nml
    MASK: DATADES
    FITOPTS: surveys/des/lcfit_fitopts/des.fitopts
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 20

  # For the biascor sims, fit without fitopt
  D:
    BASE: surveys/des/lcfit_nml/des_5yr.nml
    MASK: DESSIM
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 40

  LS:
    BASE: surveys/lowz/lcfit_nml/lowz.nml
    MASK: DATALOWZ
    FITOPTS: surveys/lowz/lcfit_fitopts/lowz.fitopts
    SNLCINP:
      USE_MINOS: F
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 20

  L:
    BASE: surveys/lowz/lcfit_nml/lowz.nml
    MASK: LOWZSIM
    SNLCINP:
      USE_MINOS: F
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 20

CLASSIFICATION:
  # Load the existing SNN classifier from GLOBAL_ML
  SNNTEST:
    CLASSIFIER: SuperNNovaClassifier
    MODE: predict
    OPTS:
      MODEL: $PIPPIN_OUTPUT/GLOBAL_ML/3_CLAS/SNNTRAIN_TRAININGSIM/model.pt
  SNIRFTEST:
    CLASSIFIER: SnirfClassifier
    MODE: predict
    OPTS:
      MODEL: $PIPPIN_OUTPUT/GLOBAL_ML/3_CLAS/SNIRFTRAIN_TESTFIT_TRAININGSIM/model.pkl
  UNITY:
    CLASSIFIER: UnityClassifier
    MODE: predict


AGGREGATION:
  AGG:

MERGE:
  MERGE:

BIASCOR:
  5YR:
    DATA: [DS_SIMDATADES5YR, LS_SIMDATALOWZ]
    SIMFILE_BIASCOR: [D_DESSIMBIAS5YRIA_G10, L_LOWZSIMBIAS_G10]
    SIMFILE_CCPRIOR: D_DESSIMBIAS5YRCC
    CLASSIFIER: SNNTEST
    MAKE_ALL_HUBBLE: True
    MUOPTS:
      SCATTER_C11:
        SIMFILE_BIASCOR: [D_DESSIMBIAS5YRIA_C11, L_LOWZSIMBIAS_C11]
      CLAS_SNIRF:
        CLASSIFIER: SNIRFTEST
      PROB_CUT_05:
        OPTS:
          CUTWIN_PROB_IA: 0.5 1.0
      PROB_CUT_08:
        OPTS:
          CUTWIN_PROB_IA: 0.8 1.0
      CHI2MAX_12:
        OPTS:
          chi2max: 12.25
      CHI2MAX_100:
        OPTS:
          chi2max: 100
      CCPRIORBINS:
        OPTS:
          nzbin_ccprior: 8
      HOSTMASS_DBETA:
        OPTS:
          u16: 1  # p16 = betaHost (dbeta/dlogmass)
          u7: 0  # p7 = logmass_cen (fix location of logmass step)
    OPTS:
      u5: 1  # Vary and fit mass step at all
      u7: 1  # Vary and fit step location
      p8: 0.01  # logmass tau
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 20

CREATE_COV:
  ALL:
    MASK: 5YR
    OPTS:
      FITOPT_SCALES:
        SALT2: 0.03
      COVOPTS:
        - "[NOSYS] [=DEFAULT,=DEFAULT]"
        - "[SALT] [+SALT,=DEFAULT]"
        - "[CAL] [+survcal,=DEFAULT]"
        - "[SCATTER] [=DEFAULT,+SCATTER]"
        - "[DUST] [=MWEBV,=DEFAULT]"
        - "[CLASSIFICATION] [=DEFAULT,+CLAS]"
        - "[ZSHIFT] [+zshift,=DEFAULT]"
        - "[VPEC] [+VPEC,=DEFAULT]"
        - "[HSTCAL] [+HST_cal,=DEFAULT]"
        - "[PROBCUT05] [=DEFAULT,=PROB_CUT_05]"
        - "[PROBCUT08] [=DEFAULT,=PROB_CUT_08]"
        - "[CHI2MAX_12] [=DEFAULT,=CHI2MAX_12]"
        - "[CHI2MAX_100] [=DEFAULT,=CHI2MAX_100]"
        - "[CCPRIORBINS] [=DEFAULT,=CCPRIORBINS]"
        - "[HOSTMASS_DBETA] [=DEFAULT,=HOSTMASS_DBETA]"

COSMOMC:
  SN_OMW:
    OPTS:
      INI: sn_prior_omw
      NUM_WALKERS: 20


ANALYSE:
  ALL_OMW:
    MASK_COSMOMC: OMW
    MASK_LCFIT: [DS_SIMDATADES5YR, D_DESSIMBIAS5YRIA_G10, D_DESSIMBIAS5YRCC, D_DESSIMBIAS5YRIA_C11]

