# To get light curves for data and sim, use
# sntable_dump.pl FITOPT000.ROOT FITRES --V CID zHD FIELD PKMJD x1 c FITPROB MJD FLUXCAL_DATA FLUXCAL_DATA_ERR FLUXCAL_MODEL FLUXCAL_MODEL_ERR


ANCHORS:  # The name of this doesnt actually matter, its all about the & and *

  DESLIKESIM: &deslikesim
    IAX:
      BASE: surveys/des/sims_cc/sn_iax_dust.input
    IA91BG:
      BASE: surveys/des/sims_cc/sn_ia91bg.input
    CC_TEMPLATES:
      BASE: surveys/des/sims_cc/sn_collection_maria_dust1.input
    GLOBAL:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_SIM_ERRORFUDGES_DIFFIMG_SBMAG.DAT
      RANSEED_REPEAT: 5 12345
      FLUXERRMODEL_REDCOV(DEEP): "g:0.2,r:0.2,i:0.2,z:0.2"
      FLUXERRMODEL_REDCOV(SHALLOW): "griz:0.45"
      SEARCHEFF_zHOST_FILE: $DES_ROOT/models/searcheff/5yr/efficiency_zHD_G10.dat
      NGEN_UNIT: 1



DATAPREP:
  DATADES5YR:
    OPTS:
      RAW_DIR: $DES_ROOT/lcmerge/DESALL_forcePhoto_real_snana_fits
      TYPES:
        IA: [1, 101]
        NONIA: [120, 130, 20, 30]


SIM:

  SIMDES5YR_NOPHASE:
    <<: *deslikesim
    IA_G10:
      BASE: surveys/des/sims_ia/sn_ia_salt2_g10_des5yr.input
      GENMAG_SMEAR_ADDPHASECOR: 0 0.001


  SIMDES5YR_02_0:
    <<: *deslikesim
    IA_G10:
      BASE: surveys/des/sims_ia/sn_ia_salt2_g10_des5yr.input
      GENMAG_SMEAR_ADDPHASECOR: 0.02 0.001

  SIMDES5YR_02_1:
    <<: *deslikesim
    IA_G10:
      BASE: surveys/des/sims_ia/sn_ia_salt2_g10_des5yr.input
      GENMAG_SMEAR_ADDPHASECOR: 0.02 1

  SIMDES5YR_02_3:
    <<: *deslikesim
    IA_G10:
      BASE: surveys/des/sims_ia/sn_ia_salt2_g10_des5yr.input
      GENMAG_SMEAR_ADDPHASECOR: 0.02 3

  SIMDES5YR_02_6:
    <<: *deslikesim
    IA_G10:
      BASE: surveys/des/sims_ia/sn_ia_salt2_g10_des5yr.input
      GENMAG_SMEAR_ADDPHASECOR: 0.02 6

  SIMDES5YR_02_10:
    <<: *deslikesim
    IA_G10:
      BASE: surveys/des/sims_ia/sn_ia_salt2_g10_des5yr.input
      GENMAG_SMEAR_ADDPHASECOR: 0.02 10








  SIMDES5YR_03_0:
    <<: *deslikesim
    IA_G10:
      BASE: surveys/des/sims_ia/sn_ia_salt2_g10_des5yr.input
      GENMAG_SMEAR_ADDPHASECOR: 0.03 0.001

  SIMDES5YR_03_1:
    <<: *deslikesim
    IA_G10:
      BASE: surveys/des/sims_ia/sn_ia_salt2_g10_des5yr.input
      GENMAG_SMEAR_ADDPHASECOR: 0.03 1

  SIMDES5YR_03_3:
    <<: *deslikesim
    IA_G10:
      BASE: surveys/des/sims_ia/sn_ia_salt2_g10_des5yr.input
      GENMAG_SMEAR_ADDPHASECOR: 0.03 3

  SIMDES5YR_03_6:
    <<: *deslikesim
    IA_G10:
      BASE: surveys/des/sims_ia/sn_ia_salt2_g10_des5yr.input
      GENMAG_SMEAR_ADDPHASECOR: 0.03 6

  SIMDES5YR_03_10:
    <<: *deslikesim
    IA_G10:
      BASE: surveys/des/sims_ia/sn_ia_salt2_g10_des5yr.input
      GENMAG_SMEAR_ADDPHASECOR: 0.03 10






  SIMDES5YR_04_0:
    <<: *deslikesim
    IA_G10:
      BASE: surveys/des/sims_ia/sn_ia_salt2_g10_des5yr.input
      GENMAG_SMEAR_ADDPHASECOR: 0.04 0.001

  SIMDES5YR_04_1:
    <<: *deslikesim
    IA_G10:
      BASE: surveys/des/sims_ia/sn_ia_salt2_g10_des5yr.input
      GENMAG_SMEAR_ADDPHASECOR: 0.04 1

  SIMDES5YR_04_3:
    <<: *deslikesim
    IA_G10:
      BASE: surveys/des/sims_ia/sn_ia_salt2_g10_des5yr.input
      GENMAG_SMEAR_ADDPHASECOR: 0.04 3

  SIMDES5YR_04_6:
    <<: *deslikesim
    IA_G10:
      BASE: surveys/des/sims_ia/sn_ia_salt2_g10_des5yr.input
      GENMAG_SMEAR_ADDPHASECOR: 0.04 6

  SIMDES5YR_04_10:
    <<: *deslikesim
    IA_G10:
      BASE: surveys/des/sims_ia/sn_ia_salt2_g10_des5yr.input
      GENMAG_SMEAR_ADDPHASECOR: 0.04 10


  SIMDES5YR_05_0:
    <<: *deslikesim
    IA_G10:
      BASE: surveys/des/sims_ia/sn_ia_salt2_g10_des5yr.input
      GENMAG_SMEAR_ADDPHASECOR: 0.05 0.001

  SIMDES5YR_05_1:
    <<: *deslikesim
    IA_G10:
      BASE: surveys/des/sims_ia/sn_ia_salt2_g10_des5yr.input
      GENMAG_SMEAR_ADDPHASECOR: 0.05 1

  SIMDES5YR_05_3:
    <<: *deslikesim
    IA_G10:
      BASE: surveys/des/sims_ia/sn_ia_salt2_g10_des5yr.input
      GENMAG_SMEAR_ADDPHASECOR: 0.05 3

  SIMDES5YR_05_6:
    <<: *deslikesim
    IA_G10:
      BASE: surveys/des/sims_ia/sn_ia_salt2_g10_des5yr.input
      GENMAG_SMEAR_ADDPHASECOR: 0.05 6

  SIMDES5YR_05_10:
    <<: *deslikesim
    IA_G10:
      BASE: surveys/des/sims_ia/sn_ia_salt2_g10_des5yr.input
      GENMAG_SMEAR_ADDPHASECOR: 0.05 10

LCFIT:

  D1D: # fit fakes using the 2D correction, which only apples to the real fakes, not the sims
    BASE: surveys/des/lcfit_nml/des_5yr.nml
    MASK: DES
    SNLCINP:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_FAKES_ERRORFUDGES_DIFFIMG_SBMAG.DAT
      ROOTFILE_OUT: FIT.ROOT
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 5
      APPEND_TABLE_TEXT: SNRMAX_g SNRMAX_r SNRMAX_i SNRMAX_z chi2_g chi2_r chi2_i chi2_z

  D1DOBS: # fit fakes using the 2D correction, which only apples to the real fakes, not the sims
    BASE: surveys/des/lcfit_nml/des_5yr.nml
    MASK: [DATADES5YR, SIMDES5YR_05_1, SIMDES5YR_NOPHASE]
    SNLCINP:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_FAKES_ERRORFUDGES_DIFFIMG_SBMAG.DAT
      ROOTFILE_OUT: FIT.ROOT
      SNTABLE_LIST: FITRES FITRES+RESIDUALS LCPLOT(text:csv)
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 5
      APPEND_TABLE_TEXT: SNRMAX_g SNRMAX_r SNRMAX_i SNRMAX_z chi2_g chi2_r chi2_i chi2_z



ANALYSE:

  CHECK_5YR_02:
    MASK_LCFIT:
      - D1D_DATADES5YR
      - D1D_SIMDES5YR_NOPHASE
      - D1D_SIMDES5YR_02_0
      - D1D_SIMDES5YR_02_1
      - D1D_SIMDES5YR_02_3
      - D1D_SIMDES5YR_02_6
      - D1D_SIMDES5YR_02_10

  CHECK_5YR_03:
    MASK_LCFIT:
      - D1D_DATADES5YR
      - D1D_SIMDES5YR_NOPHASE
      - D1D_SIMDES5YR_03_0
      - D1D_SIMDES5YR_03_1
      - D1D_SIMDES5YR_03_3
      - D1D_SIMDES5YR_03_6
      - D1D_SIMDES5YR_03_10

  CHECK_5YR_04:
    MASK_LCFIT:
      - D1D_DATADES5YR
      - D1D_SIMDES5YR_NOPHASE
      - D1D_SIMDES5YR_04_0
      - D1D_SIMDES5YR_04_1
      - D1D_SIMDES5YR_04_3
      - D1D_SIMDES5YR_04_6
      - D1D_SIMDES5YR_04_10

  CHECK_5YR_05:
    MASK_LCFIT:
      - D1D_DATADES5YR
      - D1D_SIMDES5YR_NOPHASE
      - D1D_SIMDES5YR_05_0
      - D1D_SIMDES5YR_05_1
      - D1D_SIMDES5YR_05_3
      - D1D_SIMDES5YR_05_6
      - D1D_SIMDES5YR_05_10