DATAPREP:
  DATADES5YR:  # 5 yr photometry sample
    OPTS:
      RAW_DIR: $DES_ROOT/lcmerge/DESALL_forcePhoto_real_snana_fits
      TYPES:
        IA: [1, 101]
        NONIA: [120, 130, 20, 30]
      BLIND: True

SIM:
  DESSIMBIAS5YRIA_C11:
    EXTERNAL: $PIPPIN_OUTPUT/GLOBAL/1_SIM/DESSIMBIAS5YRIA_C11
  DESSIMBIAS5YRIA_G10:
    EXTERNAL: $PIPPIN_OUTPUT/GLOBAL/1_SIM/DESSIMBIAS5YRIA_G10
  DESSIMBIAS5YRCC:
    EXTERNAL: $PIPPIN_OUTPUT/GLOBAL/1_SIM/DESSIMBIAS5YRCC

LCFIT:
  DS:
    BASE: surveys/des/lcfit_nml/des_5yr.nml
    MASK: DATADES
    FITOPTS: surveys/des/lcfit_fitopts/des.fitopts
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 20

  D:
    BASE: surveys/des/lcfit_nml/des_5yr.nml
    MASK: DESSIM
    EXTERNAL_DIRS:
      - $PIPPIN_OUTPUT/GLOBAL/2_LCFIT/D_DESSIMBIAS5YRIA_C11
      - $PIPPIN_OUTPUT/GLOBAL/2_LCFIT/D_DESSIMBIAS5YRIA_G10
      - $PIPPIN_OUTPUT/GLOBAL/2_LCFIT/D_DESSIMBIAS5YRCC


CLASSIFICATION:
  FITPROBTEST:
    CLASSIFIER: FitProbClassifier
    MODE: predict
    EXTERNAL_DIRS:
      - $PIPPIN_OUTPUT/GLOBAL/3_CLAS/FITPROBTEST_D_DESSIMBIAS5YRCC

  SNIRFTEST:
    CLASSIFIER: SnirfClassifier
    MODE: predict
    OPTS:
      MODEL: $PIPPIN_OUTPUT/GLOBAL/3_CLAS/SNIRFTRAIN_D_DESTRAIN/model.pkl
    EXTERNAL_DIRS:
      - $PIPPIN_OUTPUT/GLOBAL/3_CLAS/SNIRFTEST_D_DESSIMBIAS5YRIA_C11_SNIRFTRAIN_D_DESTRAIN
      - $PIPPIN_OUTPUT/GLOBAL/3_CLAS/SNIRFTEST_D_DESSIMBIAS5YRIA_G10_SNIRFTRAIN_D_DESTRAIN
      - $PIPPIN_OUTPUT/GLOBAL/3_CLAS/SNIRFTEST_D_DESSIMBIAS5YRCC_SNIRFTRAIN_D_DESTRAIN


AGGREGATION:
  AGG:
    EXTERNAL_DIRS:
      - $PIPPIN_OUTPUT/GLOBAL/4_AGG/AGG_DESSIMBIAS5YRIA_C11
      - $PIPPIN_OUTPUT/GLOBAL/4_AGG/AGG_DESSIMBIAS5YRIA_G10

MERGE:
  MERGE:
    EXTERNAL_DIRS:
      - $PIPPIN_OUTPUT/GLOBAL/5_MERGE/MERGE_D_DESSIMBIAS5YRIA_C11
      - $PIPPIN_OUTPUT/GLOBAL/5_MERGE/MERGE_D_DESSIMBIAS5YRIA_G10

BIASCOR:
  5YR:
    DATA: [DS_DATADES5YR]
    SIMFILE_BIASCOR: [D_DESSIMBIAS5YRIA_G10]
    SIMFILE_CCPRIOR: D_DESSIMBIAS5YRCC
    CLASSIFIER: SNIRFTEST
    MUOPTS:
      SCATTER_C11:
        SIMFILE_BIASCOR: [D_DESSIMBIAS5YRIA_C11]
        FITOPT: 0
      CLAS_SNIRF:
        CLASSIFIER: SNIRFTEST
        FITOPT: 0
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 5
