
ANCHORS:  # The name of this doesnt actually matter, its all about the & and *


  FITOPTS: &default_fitopts
    BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 10
    APPEND_TABLE_TEXT: SNRMAX_g SNRMAX_r SNRMAX_i SNRMAX_z chi2_g chi2_r chi2_i chi2_z

  SNLCINP: &default_mapdata
    FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_FAKES_ERRORFUDGES_DIFFIMG_SBMAG_5.DAT

  DESLIKESIM: &deslikesim
    IAX:
      BASE: surveys/des/sims_cc/sn_iax_dust.input
    IA91BG:
      BASE: surveys/des/sims_cc/sn_ia91bg.input
    CC_TEMPLATES:
      BASE: surveys/des/sims_cc/sn_collection_maria_dust1.input
    GLOBAL:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_SIM_ERRORFUDGES_DIFFIMG_SBMAG_5.DAT
      RANSEED_REPEAT: 1 12345
      FLUXERRMODEL_REDCOV(DEEP): "g:0.1,r:0.1,i:0.1,z:0.1"
      FLUXERRMODEL_REDCOV(SHALLOW): "griz:0.2"
      NGEN_UNIT: 1

DATAPREP:
  DATADES5YR:
    OPTS:
      RAW_DIR: $DES_ROOT/lcmerge/DESALL_forcePhoto_real_snana_fits
      TYPES:
        IA: [1, 101]
        NONIA: [120, 130, 20, 30]


SIM:



  SIMDES5YR_NOPHASE:
    <<: *deslikesim
    IA_G10:
      BASE: surveys/des/sims_ia/sn_ia_salt2_g10_des5yr.input
      GENMAG_SMEAR_ADDPHASECOR: 0 0


  SIMDES5YR_02_0:
    <<: *deslikesim
    IA_G10:
      BASE: surveys/des/sims_ia/sn_ia_salt2_g10_des5yr.input
      GENMAG_SMEAR_ADDPHASECOR: 0.02 0

  SIMDES5YR_02_1:
    <<: *deslikesim
    IA_G10:
      BASE: surveys/des/sims_ia/sn_ia_salt2_g10_des5yr.input
      GENMAG_SMEAR_ADDPHASECOR: 0.02 1

  SIMDES5YR_02_3:
    <<: *deslikesim
    IA_G10:
      BASE: surveys/des/sims_ia/sn_ia_salt2_g10_des5yr.input
      GENMAG_SMEAR_ADDPHASECOR: 0.02 3

  SIMDES5YR_02_6:
    <<: *deslikesim
    IA_G10:
      BASE: surveys/des/sims_ia/sn_ia_salt2_g10_des5yr.input
      GENMAG_SMEAR_ADDPHASECOR: 0.02 6










  SIMDES5YR_03_0:
    <<: *deslikesim
    IA_G10:
      BASE: surveys/des/sims_ia/sn_ia_salt2_g10_des5yr.input
      GENMAG_SMEAR_ADDPHASECOR: 0.03 0

  SIMDES5YR_03_1:
    <<: *deslikesim
    IA_G10:
      BASE: surveys/des/sims_ia/sn_ia_salt2_g10_des5yr.input
      GENMAG_SMEAR_ADDPHASECOR: 0.03 1

  SIMDES5YR_03_3:
    <<: *deslikesim
    IA_G10:
      BASE: surveys/des/sims_ia/sn_ia_salt2_g10_des5yr.input
      GENMAG_SMEAR_ADDPHASECOR: 0.03 3

  SIMDES5YR_03_6:
    <<: *deslikesim
    IA_G10:
      BASE: surveys/des/sims_ia/sn_ia_salt2_g10_des5yr.input
      GENMAG_SMEAR_ADDPHASECOR: 0.03 6








  SIMDES5YR_04_0:
    <<: *deslikesim
    IA_G10:
      BASE: surveys/des/sims_ia/sn_ia_salt2_g10_des5yr.input
      GENMAG_SMEAR_ADDPHASECOR: 0.04 0

  SIMDES5YR_04_1:
    <<: *deslikesim
    IA_G10:
      BASE: surveys/des/sims_ia/sn_ia_salt2_g10_des5yr.input
      GENMAG_SMEAR_ADDPHASECOR: 0.04 1

  SIMDES5YR_04_3:
    <<: *deslikesim
    IA_G10:
      BASE: surveys/des/sims_ia/sn_ia_salt2_g10_des5yr.input
      GENMAG_SMEAR_ADDPHASECOR: 0.04 3

  SIMDES5YR_04_6:
    <<: *deslikesim
    IA_G10:
      BASE: surveys/des/sims_ia/sn_ia_salt2_g10_des5yr.input
      GENMAG_SMEAR_ADDPHASECOR: 0.04 6




LCFIT:

  D1D: # fit fakes using the 2D correction, which only apples to the real fakes, not the sims
    BASE: surveys/des/lcfit_nml/des_5yr.nml
    MASK: DES
    SNLCINP:
      <<: *default_mapdata
      ROOTFILE_OUT: FIT.ROOT
    OPTS: *default_fitopts


ANALYSE:

  CHECK_5YR_ALL:
    HISTOGRAM:
      - D1D_DATADES5YR
      - D1D_SIMDES5YR_NOPHASE
      - D1D_SIMDES5YR_02_0
      - D1D_SIMDES5YR_02_1
      - D1D_SIMDES5YR_02_3
      - D1D_SIMDES5YR_02_6
      - D1D_SIMDES5YR_03_0
      - D1D_SIMDES5YR_03_1
      - D1D_SIMDES5YR_03_3
      - D1D_SIMDES5YR_03_6
      - D1D_SIMDES5YR_04_0
      - D1D_SIMDES5YR_04_1
      - D1D_SIMDES5YR_04_3
      - D1D_SIMDES5YR_04_6

  CHECK_5YR_02:
    HISTOGRAM:
      - D1D_DATADES5YR
      - D1D_SIMDES5YR_NOPHASE
      - D1D_SIMDES5YR_02_0
      - D1D_SIMDES5YR_02_1
      - D1D_SIMDES5YR_02_3
      - D1D_SIMDES5YR_02_6

  CHECK_5YR_03:
    HISTOGRAM:
      - D1D_DATADES5YR
      - D1D_SIMDES5YR_NOPHASE
      - D1D_SIMDES5YR_03_0
      - D1D_SIMDES5YR_03_1
      - D1D_SIMDES5YR_03_3
      - D1D_SIMDES5YR_03_6

  CHECK_5YR_04:
    HISTOGRAM:
      - D1D_DATADES5YR
      - D1D_SIMDES5YR_NOPHASE
      - D1D_SIMDES5YR_04_0
      - D1D_SIMDES5YR_04_1
      - D1D_SIMDES5YR_04_3
      - D1D_SIMDES5YR_04_6