# We want to make sure that our uncorrelated fudge maps actually bring distributions
# like SNRMAX into line. We expect FITPROB to still be off at this stage, but we want
# to nail everything else before continuing.

ANCHORS:
  FAKES_INPUT: &fakesinput
    BASE: surveys/des/sims_ia/fakes_diffimg.input
  FITOPTS: &default_fitopts
    BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 20
    APPEND_TABLE_TEXT: SNRMAX_g SNRMAX_r SNRMAX_i SNRMAX_z chi2_g chi2_r chi2_i chi2_z


DATAPREP:
  DATAFAKES:
    OPTS:
      RAW_DIR: $DES_ROOT/lcmerge/DESALL_forcePhoto_fake_snana_fits


SIM:
  SIMFAKE_NOCORRECTION:
    IA:
      BASE: surveys/des/sims_ia/fakes_diffimg.input
    GLOBAL:
      FLUXERRMODEL_FILE: NONE
      RANSEED_REPEAT: 1 12345

  SIMFAKE_1D_CORRECTION:
    IA: *fakesinput
    GLOBAL:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_SIM_ERRORFUDGES_DIFFIMG_SBMAG_5.DAT
      RANSEED_REPEAT: 1 12345

  SIMFAKE_2D_CORRECTION:
    IA: *fakesinput
    GLOBAL:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_SIM_ERRORFUDGES_DIFFIMG_LOGSNR_SBMAG_5.DAT
      RANSEED_REPEAT: 1 12345

  SIMFAKE_3D_CORRECTION:
    IA: *fakesinput
    GLOBAL:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_SIM_ERRORFUDGES_DIFFIMG_LOGSNR_SBMAG_PSF_5.DAT
      RANSEED_REPEAT: 1 12345


LCFIT:

  F0D:
    BASE: surveys/des/lcfit_nml/fakes.nml
    MASK: [DATAFAKES, SIMFAKE_NOCORRECTION]
    SNLCINP:
      FLUXERRMODEL_FILE: NONE
    OPTS: *default_fitopts

  F1D:
    BASE: surveys/des/lcfit_nml/fakes.nml
    MASK: [DATAFAKES, SIMFAKE_1D_CORRECTION]
    SNLCINP:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_FAKES_ERRORFUDGES_DIFFIMG_SBMAG_5.DAT
    OPTS: *default_fitopts

  F2D:
    BASE: surveys/des/lcfit_nml/fakes.nml
    MASK: [DATAFAKES, SIMFAKE_2D_CORRECTION]
    SNLCINP:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_FAKES_ERRORFUDGES_DIFFIMG_LOGSNR_SBMAG_5.DAT
    OPTS: *default_fitopts

  F3D:
    BASE: surveys/des/lcfit_nml/fakes.nml
    MASK: [DATAFAKES, SIMFAKE_3D_CORRECTION]
    SNLCINP:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_FAKES_ERRORFUDGES_DIFFIMG_LOGSNR_SBMAG_PSF_5.DAT
    OPTS: *default_fitopts


ANALYSE:

  SANITY_0D:
    HISTOGRAM:
      - F0D_DATAFAKES
      - F0D_SIMFAKE_NOCORRECTION

  SANITY_1D:
    HISTOGRAM:
      - F1D_DATAFAKES
      - F1D_SIMFAKE_1D_CORRECTION

  SANITY_2D:
    HISTOGRAM:
      - F2D_DATAFAKES
      - F2D_SIMFAKE_2D_CORRECTION

  SANITY_3D:
    HISTOGRAM:
      - F3D_DATAFAKES
      - F3D_SIMFAKE_3D_CORRECTION
