# Having computed the maps, this file will then show us our progress from before to after
# for all the dimensionality we have in our maps. This will also help pick which sigma clipping we should use
# and verify against the 3yr and 5yr data.

# Oh, and it will allow us to look at the amount of correlation we should be adding.
# This is a huge config, and it will take a long time to run.




# Oh btw, I used YAML anchoring and aliasing in here. How good is it. Just adding it here so its easy to see
ANCHORS:  # The name of this doesnt actually matter, its all about the & and *

  DEFAULT_SIM_MAP3D: &map3d
    FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_SIM_ERRORFUDGES_DIFFIMG_LOGSNR_SBMAG_PSF_5.DAT
    RANSEED_REPEAT: 1 12345

  DEFAULT_SIM_MAP2D: &map2d
    FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_SIM_ERRORFUDGES_DIFFIMG_LOGSNR_SBMAG_5.DAT
    RANSEED_REPEAT: 1 12345

  FAKES_INPUT: &fakesinput
    BASE: surveys/des/sims_ia/fakes_diffimg.input

  FITOPTS: &default_fitopts
    BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 5
    APPEND_TABLE_TEXT: SNRMAX_g SNRMAX_r SNRMAX_i SNRMAX_z chi2_g chi2_r chi2_i chi2_z

  SNLCINP3D: &map3ddata
    FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_FAKES_ERRORFUDGES_DIFFIMG_LOGSNR_SBMAG_PSF_5.DAT
  SNLCINP2D: &map2ddata
    FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_FAKES_ERRORFUDGES_DIFFIMG_LOGSNR_SBMAG_5.DAT

DATAPREP:
  FAKES:
    OPTS:
      RAW_DIR: $DES_ROOT/lcmerge/DESALL_forcePhoto_fake_snana_fits


SIM:
  # Simulate just the fakes with no correction
  SIMFAKES_NOCORR:
    IA:
      BASE: surveys/des/sims_ia/fakes_diffimg.input
    GLOBAL:
      FLUXERRMODEL_FILE: NONE
      RANSEED_REPEAT: 1 12345


  # Compute the correlation values by taking the 2D map as an interim, and creating a set of sims
  # with correlation - both intra- and inter-band. We'll step in 0.2 increments.
  SIMFAKE_3D_CORR_ALL00:
    IA: *fakesinput
    GLOBAL:
      <<: *map3d
  SIMFAKE_3D_CORR_ALL01:
    IA: *fakesinput
    GLOBAL:
      <<: *map3d
      FLUXERRMODEL_REDCOV: "griz:0.1"
  SIMFAKE_3D_CORR_ALL02:
    IA: *fakesinput
    GLOBAL:
      <<: *map3d
      FLUXERRMODEL_REDCOV: "griz:0.2"
  SIMFAKE_3D_CORR_ALL03:
    IA: *fakesinput
    GLOBAL:
      <<: *map3d
      FLUXERRMODEL_REDCOV: "griz:0.3"
  SIMFAKE_3D_CORR_ALL04:
    IA: *fakesinput
    GLOBAL:
      <<: *map3d
      FLUXERRMODEL_REDCOV: "griz:0.4"

  SIMFAKE_3D_CORR_INDEP01:
    IA: *fakesinput
    GLOBAL:
      <<: *map3d
      FLUXERRMODEL_REDCOV: "g:0.1,r:0.1,i:0.1,z:0.1"
  SIMFAKE_3D_CORR_INDEP02:
    IA: *fakesinput
    GLOBAL:
      <<: *map3d
      FLUXERRMODEL_REDCOV: "g:0.2,r:0.2,i:0.2,z:0.2"
  SIMFAKE_3D_CORR_INDEP03:
    IA: *fakesinput
    GLOBAL:
      <<: *map3d
      FLUXERRMODEL_REDCOV: "g:0.3,r:0.3,i:0.3,z:0.3"
  SIMFAKE_3D_CORR_INDEP04:
    IA: *fakesinput
    GLOBAL:
      <<: *map3d
      FLUXERRMODEL_REDCOV: "g:0.4,r:0.4,i:0.4,z:0.4"



  SIMFAKE_2D_CORR_ALL00:
    IA: *fakesinput
    GLOBAL:
      <<: *map2d
  SIMFAKE_2D_CORR_ALL01:
    IA: *fakesinput
    GLOBAL:
      <<: *map2d
      FLUXERRMODEL_REDCOV: "griz:0.1"
  SIMFAKE_2D_CORR_ALL02:
    IA: *fakesinput
    GLOBAL:
      <<: *map2d
      FLUXERRMODEL_REDCOV: "griz:0.2"
  SIMFAKE_2D_CORR_ALL03:
    IA: *fakesinput
    GLOBAL:
      <<: *map2d
      FLUXERRMODEL_REDCOV: "griz:0.3"
  SIMFAKE_2D_CORR_ALL04:
    IA: *fakesinput
    GLOBAL:
      <<: *map2d
      FLUXERRMODEL_REDCOV: "griz:0.4"



  SIMFAKE_2D_CORR_INDEP01:
    IA: *fakesinput
    GLOBAL:
      <<: *map2d
      FLUXERRMODEL_REDCOV: "g:0.1,r:0.1,i:0.1,z:0.1"
  SIMFAKE_2D_CORR_INDEP02:
    IA: *fakesinput
    GLOBAL:
      <<: *map2d
      FLUXERRMODEL_REDCOV: "g:0.2,r:0.2,i:0.2,z:0.2"
  SIMFAKE_2D_CORR_INDEP03:
    IA: *fakesinput
    GLOBAL:
      <<: *map2d
      FLUXERRMODEL_REDCOV: "g:0.3,r:0.3,i:0.3,z:0.3"
  SIMFAKE_2D_CORR_INDEP04:
    IA: *fakesinput
    GLOBAL:
      <<: *map2d
      FLUXERRMODEL_REDCOV: "g:0.4,r:0.4,i:0.4,z:0.4"


# Now we have to fit everything. For the SIMFAKES, we'll fit using the fakes.nml
# For the DES-like sims, we'll fit using surveys/des/lcfit_nml/des_5yr.nml
LCFIT:

  # Fit the fakes and the fake sims
  F0D:  # ie fit fakes, 0D = no correction
    BASE: surveys/des/lcfit_nml/fakes.nml
    MASK: FAKES
    SNLCINP:
      FLUXERRMODEL_FILE: NONE
    OPTS: *default_fitopts

  F2D: # fit fakes using the 2D correction, which only apples to the real fakes, not the sims
    BASE: surveys/des/lcfit_nml/fakes.nml
    MASK: FAKES
    SNLCINP: *map2ddata
    OPTS: *default_fitopts

  F3D: # fit fakes using the 3D correction, which only apples to the real fakes, not the sims
    BASE: surveys/des/lcfit_nml/fakes.nml
    MASK: FAKE
    SNLCINP: *map3ddata
    OPTS: *default_fitopts


ANALYSE:

  CHECK_INDEP_3D_LOOKS_ALRIGHT:
    HISTOGRAM:
      - F0D_FAKES
      - F3D_FAKES
      - F3D_SIMFAKES_NOCORR
      - F3D_SIMFAKE_3D_CORR_ALL00
  CHECK_INDEP_2D_LOOKS_ALRIGHT:
    HISTOGRAM:
      - F0D_FAKES
      - F2D_FAKES
      - F3D_SIMFAKES_NOCORR
      - F3D_SIMFAKE_2D_CORR_ALL00

  CORR_3D_00:
    HISTOGRAM:
      - F3D_FAKES
      - F3D_SIMFAKE_3D_CORR_ALL00
  CORR_3D_01:
    HISTOGRAM:
      - F3D_FAKES
      - F3D_SIMFAKE_3D_CORR_ALL01
      - F3D_SIMFAKE_3D_CORR_INDEP01
  CORR_3D_02:
    HISTOGRAM:
      - F3D_FAKES
      - F3D_SIMFAKE_3D_CORR_ALL02
      - F3D_SIMFAKE_3D_CORR_INDEP02
  CORR_3D_03:
    HISTOGRAM:
      - F3D_FAKES
      - F3D_SIMFAKE_3D_CORR_ALL03
      - F3D_SIMFAKE_3D_CORR_INDEP03
  CORR_3D_04:
    HISTOGRAM:
      - F3D_FAKES
      - F3D_SIMFAKE_3D_CORR_ALL04
      - F3D_SIMFAKE_3D_CORR_INDEP04

  ALL_3D_CORRELATIONS:
    HISTOGRAM:
      - F3D_FAKES
      - F3D_SIMFAKES_NOCORR
      - F3D_SIMFAKE_3D_CORR_ALL00
      - F3D_SIMFAKE_3D_CORR_ALL01
      - F3D_SIMFAKE_3D_CORR_ALL02
      - F3D_SIMFAKE_3D_CORR_ALL03
      - F3D_SIMFAKE_3D_CORR_INDEP01
      - F3D_SIMFAKE_3D_CORR_INDEP02
      - F3D_SIMFAKE_3D_CORR_INDEP03

  CORR_2D_00:
    HISTOGRAM:
      - F2D_FAKES
      - F3D_SIMFAKE_2D_CORR_ALL00
  CORR_2D_01:
    HISTOGRAM:
      - F2D_FAKES
      - F3D_SIMFAKE_2D_CORR_ALL01
      - F3D_SIMFAKE_2D_CORR_INDEP01
  CORR_2D_02:
    HISTOGRAM:
      - F2D_FAKES
      - F3D_SIMFAKE_2D_CORR_ALL02
      - F3D_SIMFAKE_2D_CORR_INDEP02
  CORR_2D_03:
    HISTOGRAM:
      - F2D_FAKES
      - F3D_SIMFAKE_2D_CORR_ALL03
      - F3D_SIMFAKE_2D_CORR_INDEP03
  CORR_2D_04:
    HISTOGRAM:
      - F2D_FAKES
      - F3D_SIMFAKE_2D_CORR_ALL04
      - F3D_SIMFAKE_2D_CORR_INDEP04

  ALL_2D_CORRELATIONS:
    HISTOGRAM:
      - F2D_FAKES
      - F3D_SIMFAKES_NOCORR
      - F3D_SIMFAKE_2D_CORR_ALL00
      - F3D_SIMFAKE_2D_CORR_ALL02
      - F3D_SIMFAKE_2D_CORR_ALL03
      - F3D_SIMFAKE_2D_CORR_ALL04
      - F3D_SIMFAKE_2D_CORR_INDEP02
      - F3D_SIMFAKE_2D_CORR_INDEP03
      - F3D_SIMFAKE_2D_CORR_INDEP04
