# This configuration is used to compute the independent multiplicative error fudges
# How to use:
# 1. Run this file in Pippin
# 2. Run    sntable_dump.pl FITOPT000.ROOT FITRES obs    in both of the LCFIT output folders
# 3. Use these files to run compute_map.py   in the external code directory
# 4. Copy the maps it produces into the $DES_ROOT/simlibs/maps directory

DATAPREP:
  FAKESDIFFIMG:
    OPTS:
      RAW_DIR: $DES_ROOT/lcmerge/DESALL_forcePhoto_fake_snana_fits

SIM:
  FAKESIMLIBDIFFIMG:
    IA:
      BASE: surveys/des/sims_ia/fakes_diffimg.input
    GLOBAL:
      RANSEED_REPEAT: 10 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr-lc.TEMPLATE 10

LCFIT:
  FAKES:
    BASE: surveys/des/lcfit_nml/fakes.nml
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr-lc.TEMPLATE 40