DATAPREP:
  DATAFOUND:
    OPTS:
      RAW_DIR: /project2/rkessler/SURVEYS/DES/ROOT/analysis_photoIa_5yr/base/foundation/lcmerge/Foundation_DJ17_COMBINED_FITS
      TYPES:
        IA: [1, 101]
        NONIA: [120, 130, 20, 30]
      BLIND: False

SIM:
  FOUND_G10:
    IA_FOUND_G10:
      BASE: surveys/foundation/sims_ia/sn_ia_salt2_g10_foundation.input
    GLOBAL:
      NGEN_UNIT: 1
      RANSEED_REPEAT: 10 12345

LCFIT:
  FIT:
    BASE: surveys/foundation/lcfit_nml/foundation.nml
    MASK: FOUND
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2b.TEMPLATE 20

ANALYSE:
  FOUNDATION_COMPARISON:
    MASK_LCFIT: FIT