SIM:
  DESSIMBIAS3YRIA_G10:
    EXTERNAL: $PIPPIN_OUTPUT/SRH_TEST_EXTERNAL_SOURCE/1_SIM/DESSIMBIAS3YRIA_G10

LCFIT:
  D:
    MASK: DESSIMBIAS3YRIA_G10
    BASE: surveys/des/lcfit_nml/des_5yr.nml
    EXTERNAL: $PIPPIN_OUTPUT/SRH_TEST_EXTERNAL_SOURCE/2_LCFIT/D_DESSIMBIAS3YRIA_G10