# Having computed the maps, this file will then show us our progress from before to after
# for all the dimensionality we have in our maps. This will also help pick which sigma clipping we should use
# and verify against the 3yr and 5yr data.

# Oh, and it will allow us to look at the amount of correlation we should be adding.
# This is a huge config, and it will take a long time to run.




# Oh btw, I used YAML anchoring and aliasing in here. How good is it. Just adding it here so its easy to see
ANCHORS:  # The name of this doesnt actually matter, its all about the & and *


  DEFAULT_CORR1: &default_corr_1d
    FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_SIM_ERRORFUDGES_DIFFIMG_SBMAG.DAT

  DEFAULT_CORR2: &default_corr_2d
    FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_SIM_ERRORFUDGES_DIFFIMG_LOGSNR_SBMAG.DAT

  DEFAULT_CORR3: &default_corr_3d
    FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_SIM_ERRORFUDGES_DIFFIMG_LOGSNR_SBMAG_PSF.DAT

  FAKES_INPUT: &fakesinput
    BASE: surveys/des/sims_ia/fakes_diffimg.input

  FITOPTS: &default_fitopts
    BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 10
    APPEND_TABLE_TEXT: SNRMAX_g SNRMAX_r SNRMAX_i SNRMAX_z chi2_g chi2_r chi2_i chi2_z


  DESLIKESIM: &deslikesim
    IA_G10:
      BASE: surveys/des/sims_ia/sn_ia_salt2_g10_des5yr.input
    IAX:
      BASE: surveys/des/sims_cc/sn_iax_dust.input
    IA91BG:
      BASE: surveys/des/sims_cc/sn_ia91bg.input
    CC_TEMPLATES:
      BASE: surveys/des/sims_cc/sn_collection_maria_dust1.input


DATAPREP:
  FAKES:
    OPTS:
      RAW_DIR: $DES_ROOT/lcmerge/DESALL_forcePhoto_fake_snana_fits
  DATADES3YR:
    OPTS:
      RAW_DIR: $DES_ROOT/lcmerge/DESALL_specType_SMP_real_snana_fits
      TYPES:
        IA: [1, 101]
        NONIA: [120, 130, 20, 30]
  DATADES5YR:
    OPTS:
      RAW_DIR: $DES_ROOT/lcmerge/DESALL_forcePhoto_real_snana_fits
      TYPES:
        IA: [1, 101]
        NONIA: [120, 130, 20, 30]


SIM:
  # Simulate just the fakes with no correction
  SIMFAKES_NOCORR:
    IA:
      BASE: surveys/des/sims_ia/fakes_diffimg.input
    GLOBAL:
      FLUXERRMODEL_FILE: NONE
      RANSEED_REPEAT: 5 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 5


  # Great, so that should allow a good mix for the correlation to be determined
  # broken down by deep and shallow fields. Lets simulate this mix
  SIMFAKE_1D_MIX:
    IA: *fakesinput
    GLOBAL:
      <<: *default_corr_1d
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 5
      RANSEED_REPEAT: 5 12345


  SIMFAKE_2D_MIX:
    IA: *fakesinput
    GLOBAL:
      <<: *default_corr_2d
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 5
      RANSEED_REPEAT: 5 12345


  SIMFAKE_3D_MIX:
    IA: *fakesinput
    GLOBAL:
      <<: *default_corr_3d
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 5
      RANSEED_REPEAT: 5 12345




  # 5yr sims
  SIMDES5YR_1D:
    <<: *deslikesim
    GLOBAL:
      <<: *default_corr_1d
      NGEN_UNIT: 1
      RANSEED_REPEAT: 5 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 5

  SIMDES5YR_2D:
    <<: *deslikesim
    GLOBAL:
      <<: *default_corr_2d
      NGEN_UNIT: 1
      RANSEED_REPEAT: 5 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 5

  SIMDES5YR_3D:
    <<: *deslikesim
    GLOBAL:
      <<: *default_corr_3d
      NGEN_UNIT: 1
      RANSEED_REPEAT: 5 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 5



# Now we have to fit everything. For the SIMFAKES, we'll fit using the fakes.nml
# For the DES-like sims, we'll fit using surveys/des/lcfit_nml/des_5yr.nml
LCFIT:

  # Fit the fakes and the fake sims
  F0D:
    BASE: surveys/des/lcfit_nml/fakes.nml
    MASK: FAKES
    SNLCINP:
      FLUXERRMODEL_FILE: NONE
    OPTS: *default_fitopts

  F1D: # fit fakes using the 2D correction, which only apples to the real fakes, not the sims
    BASE: surveys/des/lcfit_nml/fakes.nml
    MASK: FAKE
    SNLCINP:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_FAKES_ERRORFUDGES_DIFFIMG_SBMAG.DAT
    OPTS: *default_fitopts

  F2D: # fit fakes using the 2D correction, which only apples to the real fakes, not the sims
    BASE: surveys/des/lcfit_nml/fakes.nml
    MASK: FAKES
    SNLCINP:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_FAKES_ERRORFUDGES_DIFFIMG_LOGSNR_SBMAG.DAT
    OPTS: *default_fitopts

  F3D: # fit fakes using the 2D correction, which only apples to the real fakes, not the sims
    BASE: surveys/des/lcfit_nml/fakes.nml
    MASK: FAKES
    SNLCINP:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_FAKES_ERRORFUDGES_DIFFIMG_LOGSNR_SBMAG_PSF.DAT
    OPTS: *default_fitopts

  # Fit the DES sims
  D0D:
    BASE: surveys/des/lcfit_nml/des_5yr.nml
    MASK: DATADES
    SNLCINP:
      FLUXERRMODEL_FILE: NONE
      ROOTFILE_OUT: FIT.ROOT
    OPTS: *default_fitopts

  D1D: # fit fakes using the 2D correction, which only apples to the real fakes, not the sims
    BASE: surveys/des/lcfit_nml/des_5yr.nml
    MASK: DATADES
    SNLCINP:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_FAKES_ERRORFUDGES_DIFFIMG_SBMAG.DAT
      ROOTFILE_OUT: FIT.ROOT
    OPTS: *default_fitopts

  D2D: # fit fakes using the 2D correction, which only apples to the real fakes, not the sims
    BASE: surveys/des/lcfit_nml/des_5yr.nml
    MASK: DES
    SNLCINP:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_FAKES_ERRORFUDGES_DIFFIMG_LOGSNR_SBMAG.DAT
      ROOTFILE_OUT: FIT.ROOT
    OPTS: *default_fitopts

  D3D: # fit fakes using the 2D correction, which only apples to the real fakes, not the sims
    BASE: surveys/des/lcfit_nml/des_5yr.nml
    MASK: DATADES
    SNLCINP:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_FAKES_ERRORFUDGES_DIFFIMG_LOGSNR_SBMAG_PSF.DAT
      ROOTFILE_OUT: FIT.ROOT
    OPTS: *default_fitopts




ANALYSE:

  CHECK_FAKES:
    MASK_LCFIT:
      - F1D_FAKES
      - F1D_FAKES
      - F1D_SIMFAKE_1D_MIX

  CHECK_FAKES_BEFORE_AFTER:
    MASK_LCFIT:
      - F0D_FAKES
      - F1D_SIMFAKES_NOCORR
      - F1D_FAKES
      - F1D_SIMFAKE_1D_MIX

  CHECK_5YR_DIST_1D:
    MASK_LCFIT:
      - D1D_DATADES5YR
      - D2D_SIMDES5YR_1D

  CHECK_5YR_DIST_2D:
    MASK_LCFIT:
      - D2D_DATADES5YR
      - D2D_SIMDES5YR_2D

  CHECK_5YR_DIST_3D:
    MASK_LCFIT:
      - D3D_DATADES5YR
      - D2D_SIMDES5YR_3D
