# Having computed the maps, this file will then show us our progress from before to after
# for all the dimensionality we have in our maps. This will also help pick which sigma clipping we should use
# and verify against the 3yr and 5yr data.

# Oh, and it will allow us to look at the amount of correlation we should be adding.
# This is a huge config, and it will take a long time to run.




# Oh btw, I used YAML anchoring and aliasing in here. How good is it. Just adding it here so its easy to see
ANCHORS:  # The name of this doesnt actually matter, its all about the & and *

  DEFAULT_SIM_MAP: &default_map
    FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_SIM_ERRORFUDGES_DIFFIMG_LOGSNR_SBMAG_5.DAT
    RANSEED_REPEAT: 1 12345

  DEFAULT_CORR: &default_corr
    FLUXERRMODEL_REDCOV(DEEP): "griz:0.6"
    FLUXERRMODEL_REDCOV(SHALLOW): "g:0.2,r:0.2,i:0.2,z:0.0"

  FITOPTS: &default_fitopts
    BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 5
    APPEND_TABLE_TEXT: SNRMAX_g SNRMAX_r SNRMAX_i SNRMAX_z chi2_g chi2_r chi2_i chi2_z

  SNLCINP: &default_mapdata
    FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_FAKES_ERRORFUDGES_DIFFIMG_LOGSNR_SBMAG_5.DAT

  DESLIKESIM: &deslikesim
    IA_G10:
      BASE: surveys/des/sims_ia/sn_ia_salt2_g10_des5yr.input
    IAX:
      BASE: surveys/des/sims_cc/sn_iax_dust.input
    IA91BG:
      BASE: surveys/des/sims_cc/sn_ia91bg.input
    CC_TEMPLATES:
      BASE: surveys/des/sims_cc/sn_collection_maria_dust1.input


DATAPREP:
  FAKES:
    OPTS:
      RAW_DIR: $DES_ROOT/lcmerge/DESALL_forcePhoto_fake_snana_fits
  DATADES3YR:
    OPTS:
      RAW_DIR: $DES_ROOT/lcmerge/DESALL_specType_SMP_real_snana_fits
      TYPES:
        IA: [1, 101]
        NONIA: [120, 130, 20, 30]
  DATADES5YR:
    OPTS:
      RAW_DIR: $DES_ROOT/lcmerge/DESALL_forcePhoto_real_snana_fits
      TYPES:
        IA: [1, 101]
        NONIA: [120, 130, 20, 30]


SIM:
  # Simulate just the fakes with no correction
  SIMFAKES_NOCORR:
    IA:
      BASE: surveys/des/sims_ia/fakes_diffimg.input
    GLOBAL:
      FLUXERRMODEL_FILE: NONE
      RANSEED_REPEAT: 1 12345


  # Compute the correlation values by taking the 2D map as an interim, and creating a set of sims
  # with correlation - both intra- and inter-band. We'll step in 0.2 increments.
  SIMFAKE_2D_CORR_ALL00:
    IA:
      BASE: surveys/des/sims_ia/fakes_diffimg.input
    GLOBAL:
      <<: *default_map

  SIMFAKE_2D_CORR_ALL02:
    IA:
      BASE: surveys/des/sims_ia/fakes_diffimg.input
    GLOBAL:
      <<: *default_map
      FLUXERRMODEL_REDCOV: "griz:0.2"
  SIMFAKE_2D_CORR_ALL04:
    IA:
      BASE: surveys/des/sims_ia/fakes_diffimg.input
    GLOBAL:
      <<: *default_map
      FLUXERRMODEL_REDCOV: "griz:0.4"
  SIMFAKE_2D_CORR_ALL06:
    IA:
      BASE: surveys/des/sims_ia/fakes_diffimg.input
    GLOBAL:
      <<: *default_map
      FLUXERRMODEL_REDCOV: "griz:0.6"
  SIMFAKE_2D_CORR_ALL08:
    IA:
      BASE: surveys/des/sims_ia/fakes_diffimg.input
    GLOBAL:
      <<: *default_map
      FLUXERRMODEL_REDCOV: "griz:0.8"
  SIMFAKE_2D_CORR_INDEP02:
    IA:
      BASE: surveys/des/sims_ia/fakes_diffimg.input
    GLOBAL:
      <<: *default_map
      FLUXERRMODEL_REDCOV: "g:0.2,r:0.2,i:0.2,z:0.2"
  SIMFAKE_2D_CORR_INDEP04:
    IA:
      BASE: surveys/des/sims_ia/fakes_diffimg.input
    GLOBAL:
      <<: *default_map
      FLUXERRMODEL_REDCOV: "g:0.4,r:0.4,i:0.4,z:0.4"
  SIMFAKE_2D_CORR_INDEP06:
    IA:
      BASE: surveys/des/sims_ia/fakes_diffimg.input
    GLOBAL:
      <<: *default_map
      FLUXERRMODEL_REDCOV: "g:0.6,r:0.6,i:0.6,z:0.6"
  SIMFAKE_2D_CORR_INDEP08:
    IA:
      BASE: surveys/des/sims_ia/fakes_diffimg.input
    GLOBAL:
      <<: *default_map
      FLUXERRMODEL_REDCOV: "g:0.8,r:0.8,i:0.8,z:0.8"

  # Great, so that should allow a good mix for the correlation to be determined
  # broken down by deep and shallow fields. Lets simulate this mix
  SIMFAKE_2D_MIX:
    IA:
      BASE: surveys/des/sims_ia/fakes_diffimg.input
    GLOBAL:
      <<: *default_map
      <<: *default_corr





  # Lets also compare the 1D, 2D and 3D maps with the fakes without correlations
  SIMFAKE_1D_CORR_ALL00:
    IA:
      BASE: surveys/des/sims_ia/fakes_diffimg.input
    GLOBAL:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_SIM_ERRORFUDGES_DIFFIMG_SBMAG_5.DAT

  SIMFAKE_3D_CORR_ALL00:
    IA:
      BASE: surveys/des/sims_ia/fakes_diffimg.input
    GLOBAL:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_SIM_ERRORFUDGES_DIFFIMG_LOGSNR_SBMAG_PSF_5.DAT




  # So now that we have the correlations, lets apply them to the 3yr data and then the 5yr data,
  # with and without the correlations, and also with no fudges at all

  # 3yr sims
  SIMDES3YR_2D_REDCOV:
      IA_G10:
        BASE: surveys/des/sims_ia/sn_ia_salt2_g10_des3yr.input
      GLOBAL:
        <<: *default_map
        <<: *default_corr
        NGEN_UNIT: 10.0
  SIMDES3YR_2D_INDCOV:
      IA_G10:
        BASE: surveys/des/sims_ia/sn_ia_salt2_g10_des3yr.input
      GLOBAL:
        <<: *default_map
        NGEN_UNIT: 10.0
  SIMDES3YR_2D_NOCOR:
    IA_G10:
      BASE: surveys/des/sims_ia/sn_ia_salt2_g10_des3yr.input
    GLOBAL:
      FLUXERRMODEL_FILE: NONE
      NGEN_UNIT: 10.0
      RANSEED_REPEAT: 1 12345

  # 5yr sims
  SIMDES5YR_2D_REDCOV:
    <<: *deslikesim
    GLOBAL:
      <<: *default_map
      <<: *default_corr
      NGEN_UNIT: 1
      RANSEED_REPEAT: 5 12345
  SIMDES5YR_2D_INDCOV:
    <<: *deslikesim
    GLOBAL:
      <<: *default_map
      NGEN_UNIT: 1
      RANSEED_REPEAT: 5 12345
  SIMDES5YR_2D_NOCOR:
    <<: *deslikesim
    GLOBAL:
      NGEN_UNIT: 1
      FLUXERRMODEL_FILE: NONE
      RANSEED_REPEAT: 5 12345

# Now we have to fit everything. For the SIMFAKES, we'll fit using the fakes.nml
# For the DES-like sims, we'll fit using surveys/des/lcfit_nml/des_5yr.nml
LCFIT:

  # Fit the fakes and the fake sims
  F0D:  # ie fit fakes, 0D = no correction
    BASE: surveys/des/lcfit_nml/fakes.nml
    MASK: FAKES
    SNLCINP:
      FLUXERRMODEL_FILE: NONE
    OPTS: *default_fitopts
  F1D:
    BASE: surveys/des/lcfit_nml/fakes.nml
    MASK: FAKES
    SNLCINP:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_FAKES_ERRORFUDGES_DIFFIMG_SBMAG_5.DAT
    OPTS: *default_fitopts
  F2D: # fit fakes using the 2D correction, which only apples to the real fakes, not the sims
    BASE: surveys/des/lcfit_nml/fakes.nml
    MASK: FAKE
    SNLCINP: *default_mapdata
    OPTS: *default_fitopts
  F3D:
    BASE: surveys/des/lcfit_nml/fakes.nml
    MASK: FAKES
    SNLCINP:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/maps/DES5YR_FAKES_ERRORFUDGES_DIFFIMG_LOGSNR_SBMAG_PSF_5.DAT
    OPTS: *default_fitopts

  # Fit the DES sims
  D0D: # fit fakes using the 2D correction, which only apples to the real fakes, not the sims
    BASE: surveys/des/lcfit_nml/des_5yr.nml
    MASK: DATADES
    SNLCINP:
      FLUXERRMODEL_FILE: NONE
      ROOTFILE_OUT: FIT.ROOT
    OPTS: *default_fitopts
  D2D: # fit fakes using the 2D correction, which only apples to the real fakes, not the sims
    BASE: surveys/des/lcfit_nml/des_5yr.nml
    MASK: DES
    SNLCINP:
      <<: *default_mapdata
      ROOTFILE_OUT: FIT.ROOT
    OPTS: *default_fitopts


ANALYSE:
  CHECK_DIMENSIONALITY:
    HISTOGRAM:
      - F0D_FAKES
      - F1D_FAKES
      - F2D_FAKES
      - F3D_FAKES
      - F2D_SIMFAKES_NOCORR
      - F2D_SIMFAKE_1D_CORR_ALL00
      - F2D_SIMFAKE_2D_CORR_ALL00
      - F2D_SIMFAKE_3D_CORR_ALL00

  CHECK_DIMENSIONALITY_1D:
    HISTOGRAM:
      - F1D_FAKES
      - F2D_SIMFAKE_1D_CORR_ALL00
  CHECK_DIMENSIONALITY_2D:
    HISTOGRAM:
      - F2D_FAKES
      - F2D_SIMFAKE_2D_CORR_ALL00
  CHECK_DIMENSIONALITY_3D:
    HISTOGRAM:
      - F3D_FAKES
      - F2D_SIMFAKE_3D_CORR_ALL00

  CHECK_FAKES:
    HISTOGRAM:
      - F0D_FAKES
      - F2D_SIMFAKES_NOCORR
      - F2D_FAKES
      - F2D_SIMFAKE_2D_MIX

  DETERMINE_CORRELATIONS:
    HISTOGRAM:
      - F2D_FAKES
      - F2D_SIMFAKES_NOCORR
      - F2D_SIMFAKE_2D_CORR_ALL00
      - F2D_SIMFAKE_2D_CORR_ALL02
      - F2D_SIMFAKE_2D_CORR_ALL04
      - F2D_SIMFAKE_2D_CORR_ALL06
      - F2D_SIMFAKE_2D_CORR_ALL08
      - F2D_SIMFAKE_2D_CORR_INDEP02
      - F2D_SIMFAKE_2D_CORR_INDEP04
      - F2D_SIMFAKE_2D_CORR_INDEP06
      - F2D_SIMFAKE_2D_CORR_INDEP08

  CHECK_3YR_DIST:
    HISTOGRAM:
      - D2D_DATADES3YR
      - D2D_SIMDES3YR_2D_REDCOV
      - D2D_SIMDES3YR_2D_INDCOV
      - D2D_SIMDES3YR_2D_NOCOR

  CHECK_5YR_DIST:
    HISTOGRAM:
      - D2D_DATADES5YR
      - D2D_SIMDES5YR_2D_REDCOV
      - D2D_SIMDES5YR_2D_INDCOV
      - D2D_SIMDES5YR_2D_NOCOR

  CHECK_5YR_DIST_INDCOV:
    HISTOGRAM:
      - D2D_DATADES5YR
      - D2D_SIMDES5YR_2D_INDCOV

  CHECK_5YR_DIST_REDCOV:
    HISTOGRAM:
      - D2D_DATADES5YR
      - D2D_SIMDES5YR_2D_REDCOV

  CHECK_5YR_DIST_NOCOR:
    HISTOGRAM:
      - D2D_DATADES5YR
      - D2D_SIMDES5YR_2D_NOCOR