DATAPREP:
  DATADES5YR:  # 5 yr photometry sample
    OPTS:
      RAW_DIR: $DES_ROOT/lcmerge/DESALL_forcePhoto_real_snana_fits
  DATALOWZ:  # lowz combined sample
    OPTS:
      RAW_DIR: $DES_ROOT/lcmerge/DES3YR_LOWZ_COMBINED_FITS
  DATADES3YR:  # 3yr spec sample
    OPTS:
      RAW_DIR: $DES_ROOT/lcmerge/DESALL_specType_SMP_real_snana_fits

SIM:
  TRAININGDESSIM:
    IA_G10:
      BASE: sn_ia_salt2_g10.input
    II_JONES:
      BASE: sn_collection_jones.input
    GLOBAL:
      NGEN_UNIT: 1.0
      RANSEED_REPEAT: 10 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 10

  TESDESSIM:
    IA_G10:
      BASE: sn_ia_salt2_g10.input
    II_JONES:
      BASE: sn_collection_jones.input
      DNDZ_ALLSCALE: 1.0
    GLOBAL:
      NGEN_UNIT: 0.2
      RANSEED_REPEAT: 5 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 10

  LOWZSIMBIASCOR:
    IA_G10_LOWZ:
      BASE: sn_ia_salt2_g10_lowz.input
      GENSIGMA_SALT2ALPHA: 1E8  1E8
      GENRANGE_SALT2ALPHA: 0.12 0.20
      GENGRID_SALT2ALPHA: 2
      GENSIGMA_SALT2BETA: 1E8  1E8
      GENRANGE_SALT2BETA: 2.6  3.6
      GENGRID_SALT2BETA: 2
    GLOBAL:
      NGEN_UNIT: 10
      RANSEED_REPEAT: 10 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 10

  DESSIMBIASCOR3YRIA:
    IA_G10_DES3YR:
      BASE: sn_ia_salt2_g10_des3yr.input
      GENSIGMA_SALT2ALPHA: 1E8  1E8
      GENRANGE_SALT2ALPHA: 0.12 0.20
      GENGRID_SALT2ALPHA: 2
      GENSIGMA_SALT2BETA: 1E8  1E8
      GENRANGE_SALT2BETA: 2.6  3.6
      GENGRID_SALT2BETA: 2
    GLOBAL:
      NGEN_UNIT: 10
      RANSEED_REPEAT: 10 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 10

  DESSIMBIAS5YRIA:
    IA_G10:
      BASE: sn_ia_salt2_g10.input
      GENSIGMA_SALT2ALPHA: 1E8  1E8
      GENRANGE_SALT2ALPHA: 0.12 0.20
      GENGRID_SALT2ALPHA: 2
      GENSIGMA_SALT2BETA: 1E8  1E8
      GENRANGE_SALT2BETA: 2.6  3.6
      GENGRID_SALT2BETA: 2
    GLOBAL:
      NGEN_UNIT: 10
      RANSEED_REPEAT: 10 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 10

  DESSIMBIAS5YRCC:
    IBC_TEMPLATES:
      BASE: sn_ibc_templates.input
    II_TEMPLATES:
      BASE: sn_ii_templates.input
    GLOBAL:
      NGEN_UNIT: 10
      RANSEED_REPEAT: 10 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 10

LCFIT:
  LOWZFITSYS:
    BASE: lowz.nml
    FITOPTS: lowz_small.fitopts
    MASK: DATALOWZ

  DESFITSYS:
    BASE: des.nml
    FITOPTS: des_small.fitopts
    MASK: DATADES

  LOWZFIT:
    BASE: lowz.nml
    MASK: LOWZSIM

  DESFIT:
    BASE: des.nml
    MASK: DESSIM

CLASSIFICATION:
  SNIRFTRAIN:
    CLASSIFIER: SnirfClassifier
    MODE: train
    MASK_SIM: TRAINING

  SNIRFTEST:
    CLASSIFIER: SnirfClassifier
    MODE: predict
    OPTS:
      MODEL: SNIRFTRAIN

AGGREGATION:
  AGG:
    OPTS:
      PLOT: True

MERGE:
  MERGE:

BIASCOR:
  5YR:
    DATA: [DATADES5YR, DATALOWZ]
    SIMFILE_BIASCOR: [DESSIMBIAS5YRIA, LOWZSIMBIASCOR]
    SIMFILE_CCPRIOR: DESSIMBIAS5YRCC
    CLASSIFIER: SNIRFTEST
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 5

  3YR:
    DATA: [DATADES3YR, DATALOWZ]
    SIMFILE_BIASCOR: [DESSIMBIAS3YRIA, LOWZSIMBIASCOR]
    CLASSIFIER: SNIRFTEST
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 5


CREATE_COV:
  ALL:
    OPTS:
      COVOPTS:
        - "[NOSYS] [=DEFAULT,=DEFAULT]"


COSMOMC:
  SN_OMW:
    OPTS:
      INI: sn_omw
      COVOPTS: [ALL, NOSYS]  # If you leave this blank, you get them all. Exact matching
      NUM_WALKERS: 20

ANALYSE:
  ALL_OMW:
    MASK_COSMOMC: OMW
    OPTS:
      BLIND: w
