DATAPREP:
  TRAINSPECFULL:
    OPTS:
      RAW_DIR: PIP_ANAIS_SNN_RELIABILITY_TRAINSPECFULL

  TESTSPECFULL:
    OPTS:
      RAW_DIR: PIP_ANAIS_SNN_RELIABILITY_TESTSPECFULL

CLASSIFICATION:
  SNNVANILLATRAIN:
    CLASSIFIER: SuperNNovaClassifier
    MODE: train
    MASK_SIM: TRAIN

  SNNVANILLATEST:
    CLASSIFIER: SuperNNovaClassifier
    MODE: predict
    OPTS:
      MODEL: SNNVANILLATRAIN

AGGREGATION:
  AGG:
    OPTS:
      PLOT: True