DATAPREP:
  TRAINSPECFULL:
    OPTS:
      RAW_DIR: PIP_ANAIS_SNN_RELIABILITY_TRAINSPECFULL
      TYPES:
        IA: [1, 101]
        NONIA: [120, 130, 20, 30]

  TESTSPECFULL:
    OPTS:
      RAW_DIR: PIP_ANAIS_SNN_RELIABILITY_TESTSPECFULL
      TYPES:
        IA: [1, 101]
        NONIA: [120, 130, 20, 30]

CLASSIFICATION:
  SNNVANILLATRAIN:
    CLASSIFIER: SuperNNovaClassifier
    MODE: train
    MASK_SIM: TRAIN

  SNNVANILLATEST:
    CLASSIFIER: SuperNNovaClassifier
    MODE: predict
    OPTS:
      MODEL: SNNVANILLATRAIN

AGGREGATION:
  AGG:
    OPTS:
      PLOT: True