SIM:
  LOWZSIM:
    IA_G10_LOWZ:
      BASE: sn_ia_salt2_g10_lowz.input
    GLOBAL:
      NGEN_UNIT: 2
      RANSEED_CHANGE: 30 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_1hr.TEMPLATE 30

  DESSIM:
    IA_G10:
      BASE: sn_ia_salt2_g10.input
    GLOBAL:
      NGEN_UNIT: 1
      RANSEED_CHANGE: 30 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_1hr.TEMPLATE 30

  LOWZSIMBIAS:
    IA_G10_LOWZ:
      BASE: sn_ia_salt2_g10_lowz.input
      GENSIGMA_SALT2ALPHA: 1E8  1E8
      GENRANGE_SALT2ALPHA: 0.12 0.20
      GENGRID_SALT2ALPHA: 2
      GENSIGMA_SALT2BETA: 1E8  1E8
      GENRANGE_SALT2BETA: 2.6  3.6
      GENGRID_SALT2BETA: 2
    GLOBAL:
      NGEN_UNIT: 10
      RANSEED_REPEAT: 30 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 30

  DESSIMBIAS5YRIA:
    IA_G10:
      BASE: sn_ia_salt2_g10.input
      GENSIGMA_SALT2ALPHA: 1E8  1E8
      GENRANGE_SALT2ALPHA: 0.12 0.20
      GENGRID_SALT2ALPHA: 2
      GENSIGMA_SALT2BETA: 1E8  1E8
      GENRANGE_SALT2BETA: 2.6  3.6
      GENGRID_SALT2BETA: 2
    GLOBAL:
      NGEN_UNIT: 10
      RANSEED_REPEAT: 30 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 30

LCFIT:
  L:
    BASE: lowz.nml
    MASK: LOWZ
    SNLCINP:
      USE_MINOS: F
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 20

  D:
    BASE: des.nml
    MASK: DES
    SNLCINP:
      USE_MINOS: F
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 20

CLASSIFICATION:
  UNITY:
    CLASSIFIER: UnityClassifier
    MODE: predict

AGGREGATION:
  AGG:

MERGE:
  MERGE:

BIASCOR:
  BIASCHECK_BOTH:
    DATA: [D_DESSIM, L_LOWZSIM]
    SIMFILE_BIASCOR: [D_DESSIMBIAS5YRIA, L_LOWZSIMBIAS]
    CLASSIFIER: UNITY
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 20
      chi2max: 16

  BIASCHECK_DES:
    DATA: [D_DESSIM]
    SIMFILE_BIASCOR: [D_DESSIMBIAS5YRIA]
    CLASSIFIER: UNITY
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 20
      chi2max: 16

  BIASCHECK_LOWZ:
    DATA: [L_LOWZSIM]
    SIMFILE_BIASCOR: [L_LOWZSIMBIAS]
    CLASSIFIER: UNITY
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 20
      chi2max: 16

ANALYSE:
  BIASCHECK:
