# Train on Jones, but sim on Maria and take it to cosmology and see what we get

SIM:
  LOWZ:
    IA_G10_LOWZ:
      BASE: sn_ia_salt2_g10_lowz.input
    GLOBAL:
      NGEN_UNIT: 0.2
      RANSEED_REPEAT: 10 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_1hr.TEMPLATE 50

  DESMARIA:
    IA_G10:
      BASE: sn_ia_salt2_g10.input
    II_TEMPLATES:
      BASE: sn_collection_maria.input
    GLOBAL:
      NGEN_UNIT: 0.1
      RANSEED_REPEAT: 10 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_1hr.TEMPLATE 50

  DESJONES:
    IA_G10:
      BASE: sn_ia_salt2_g10.input
    II_TEMPLATES:
      BASE: sn_collection_jones.input
    GLOBAL:
      NGEN_UNIT: 0.1
      RANSEED_REPEAT: 10 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_1hr.TEMPLATE 50

  TRAINDES:
    IA_G10:
      BASE: sn_ia_salt2_g10.input
    II_TEMPLATES:
      BASE: sn_collection_jones.input
    GLOBAL:
      NGEN_UNIT: 3
      RANSEED_REPEAT: 30 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 30

  TESTDESMARIA:
    IA_G10:
      BASE: sn_ia_salt2_c11.input
    II_TEMPLATES:
      BASE: sn_collection_maria.input
      PATH_NON1ASED: $DES_USERS/mvincenzi/NON1A/
    GLOBAL:
      NGEN_UNIT: 2
      RANSEED_REPEAT: 20 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 20

  LOWZBIAS:
    IA_G10_LOWZ:
      BASE: sn_ia_salt2_g10_lowz.input
      GENSIGMA_SALT2ALPHA: 1E8  1E8
      GENRANGE_SALT2ALPHA: 0.12 0.20
      GENGRID_SALT2ALPHA: 2
      GENSIGMA_SALT2BETA: 1E8  1E8
      GENRANGE_SALT2BETA: 2.6  3.6
      GENGRID_SALT2BETA: 2
    GLOBAL:
      NGEN_UNIT: 10
      RANSEED_REPEAT: 30 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 30

  DESBIASIA:
    IA_G10:
      BASE: sn_ia_salt2_g10.input
      GENSIGMA_SALT2ALPHA: 1E8  1E8
      GENRANGE_SALT2ALPHA: 0.12 0.20
      GENGRID_SALT2ALPHA: 2
      GENSIGMA_SALT2BETA: 1E8  1E8
      GENRANGE_SALT2BETA: 2.6  3.6
      GENGRID_SALT2BETA: 2
    GLOBAL:
      NGEN_UNIT: 10
      RANSEED_REPEAT: 30 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 30

  DESBIASCC:
    II_TEMPLATES:
      BASE: sn_collection_jones.input
    GLOBAL:
      NGEN_UNIT: 10
      RANSEED_REPEAT: 10 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 10


LCFIT:
  L:
    BASE: lowz.nml
    MASK: LOWZ
    SNLCINP:
      USE_MINOS: F
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 20

  D:
    BASE: des.nml
    MASK: DES
    SNLCINP:
      USE_MINOS: F
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 80

CLASSIFICATION:
  SNN:
    CLASSIFIER: SuperNNovaClassifier
    MODE: train
    MASK_SIM: TRAINDESSIM

  SNNTEST:
    CLASSIFIER: SuperNNovaClassifier
    MODE: predict
    OPTS:
      MODEL: SNN

AGGREGATION:
  AGG:

MERGE:
  MERGE:

BIASCOR:
  M:
    DATA: [D_DESMARIA, L_LOWZ]
    SIMFILE_BIASCOR: [D_DESBIASIA, L_LOWZBIAS]
    SIMFILE_CCPRIOR: D_DESBIASCC
    CLASSIFIER: SNNTEST
    MAKE_ALL_HUBBLE: False
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 20
  J:
    DATA: [D_DESJONES, L_LOWZ]
    SIMFILE_BIASCOR: [D_DESBIASIA, L_LOWZBIAS]
    SIMFILE_CCPRIOR: D_DESBIASCC
    CLASSIFIER: SNNTEST
    MAKE_ALL_HUBBLE: False
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 20

CREATE_COV:
  ALL:

COSMOMC:
  SN_OMW:
    OPTS:
      INI: sn_omw
      NUM_WALKERS: 20

ANALYSE:
  MARIAvJONES:
