SIM:
  DES:
    IA_G10:
      BASE: sn_ia_salt2_g10.input
    IA_C11:
      BASE: sn_ia_salt2_c11.input
    IAX:
      BASE: sn_iax.input
    II_NMF:
      BASE: sn_ii_nmf.input
    GLOBAL:
      NGEN_UNIT: 0.1


LCFIT:
  BASIC:
      BASE: des.nml


CLASSIFICATION:
  SNN:
    CLASSIFIER: SuperNNovaClassifier
    OPTS:
      MODEL: output/SNN/2_CLAS/PIP_SNN_DES_BASIC_SNN/dump/models/vanilla_S_0_CLF_2_R_None_saltfit_DF_1.0_N_global_lstm_32x2_0.05_128_True_mean/vanilla_S_0_CLF_2_R_None_saltfit_DF_1.0_N_global_lstm_32x2_0.05_128_True_mean.pt
