# Plot hjistograms comparing data to sims

DATAPREP:
  DATA:  # 5 yr photometry sample
    OPTS:
      RAW_DIR: $DES_ROOT/lcmerge/DESALL_forcePhoto_real_snana_fits
      TYPES:
        IA: [1, 101]
        NONIA: [120, 130, 20, 30]

SIM:
  MAGI:
    IA_G10:
      BASE: sn_ia_salt2_g10.input
    II_TEMPLATES:
      BASE: sn_collection_maria.input
    GLOBAL:
      SEARCHEFF_zHOST_FILE: $DES_ROOT/models/searcheff/samtest/efficiency_HOST_MAG_i.dat
      NGEN_UNIT: 0.6
      RANSEED_REPEAT: 20 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_1hr.TEMPLATE 20

  MAGR:
    IA_G10:
      BASE: sn_ia_salt2_g10.input
    II_TEMPLATES:
      BASE: sn_collection_maria.input
    GLOBAL:
      SEARCHEFF_zHOST_FILE: $DES_ROOT/models/searcheff/samtest/efficiency_HOST_MAG_r.dat
      NGEN_UNIT: 0.6
      RANSEED_REPEAT: 20 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_1hr.TEMPLATE 20

  ZHD:
    IA_G10:
      BASE: sn_ia_salt2_g10.input
    II_TEMPLATES:
      BASE: sn_collection_maria.input
    GLOBAL:
      SEARCHEFF_zHOST_FILE: $DES_ROOT/models/searcheff/samtest/efficiency_zHD.dat
      NGEN_UNIT: 0.6
      RANSEED_REPEAT: 20 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_1hr.TEMPLATE 20


  BASE:
    IA_G10:
      BASE: sn_ia_salt2_g10.input
    II_TEMPLATES:
      BASE: sn_collection_maria.input
    GLOBAL:
      NGEN_UNIT: 0.6
      RANSEED_REPEAT: 20 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_1hr.TEMPLATE 20

LCFIT:
  D:
    BASE: des.nml
    SNLCINP:
      USE_MINOS: F
      ROOTFILE_OUT: "'FIT.ROOT'"
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 50
      APPEND_FITRES: MWEBV HOST_MAG_i HOST_MAG_r HOST_MAG_g SNRMAX_g SNRMAX_r SNRMAX_i SNRMAX_z


ANALYSE:
  HIST:
    HISTOGRAM: [D_DATA, D_BASE, D_MAGI, D_MAGR, D_ZHD]
