# Plot hjistograms comparing data to sims

DATAPREP:
  DATA:  # 5 yr photometry sample
    OPTS:
      RAW_DIR: $DES_ROOT/lcmerge/DESALL_forcePhoto_real_snana_fits
      TYPES:
        IA: [1, 101]
        NONIA: [120, 130, 20, 30]
  FAKES:
    OPTS:
      RAW_DIR: $DES_ROOT/lcmerge/DESALL_forcePhoto_fake_snana_fits

SIM:
  BASE:
    IA_G10:
      BASE: sn_ia_salt2_g10.input
    II_TEMPLATES:
      BASE: sn_collection_maria.input
    GLOBAL:
      NGEN_UNIT: 0.1
      RANSEED_REPEAT: 5 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_1hr.TEMPLATE 5

LCFIT:
  D:
    BASE: des.nml
    SNLCINP:
      USE_MINOS: F
      SNTABLE_LIST: "'FITRES FITRES+RESIDUALS LCPLOT(text:csv)'"
      ROOTFILE_OUT: "'FIT.ROOT'"
      MXLC_PLOT: 100
      FLUXERRMAP_IGNORE_DATAERR: FLUXERR_ADD,FLUXERR_SCALE
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 50

