DATAPREP:
  DATADES3YR:  # 3yr spec sample
    OPTS:
      RAW_DIR: $DES_ROOT/lcmerge/DESALL_specType_SMP_real_snana_fits
      TYPES:
        IA: [1, 101]
        NONIA: [120, 130, 20, 30]
  DATALOWZ:  # lowz combined sample
    OPTS:
      RAW_DIR: $DES_ROOT/lcmerge/DES3YR_LOWZ_COMBINED_FITS
      TYPES:
        IA: [1, 101]
        NONIA: [120, 130, 20, 30]
LCFIT:
  LS:
    BASE: lowz.nml
    MASK: DATALOWZ
    SNLCINP:
      USE_MINOS: F
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 20

  DS:
    BASE: des.nml
    MASK: DATADES
    SNLCINP:
      USE_MINOS: F
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 20
