SIM: # Dont change this
  BORINGSIM: # This is the name of the simulation
    IA:
      BASE: des_ia.input
      GENMAG_SMEAR_MODELNAME: G10
    NONIA:
      BASE: des_cc.input
      GENMODEL: NON1AGRID $DES_ROOT/models/NON1AGRID/DES_NON1ASED_K10.GRID
    GLOBAL:
      NGEN_UNIT: 0.1
      RANSEED_CHANGE: 2 12345

LCFIT: # Dont change this
  NOCHANGES: # Name of the light curve fitting
      BASE: des.nml
#    DIFFERENT_SN:
#        BASE: des.nml
#        FITOPTS: des.fitopts
#        SNLCINP:
#            CUTWIN_SNRMAX:  3.0, 1.0E8
#            CUTWIN_NFILT_SNRMAX:  3.0, 99.

CLASSIFICATION: # Dont change this
  TOY: # Name of the classification step
    CLASSIFIER: ToyClassifier
