SIM:
  LOWZSIM:
    IA_G10_LOWZ:
      BASE: sn_ia_salt2_g10_lowz.input
    GLOBAL:
      NGEN_UNIT: 1
      RANSEED_REPEAT: 1 12345

  DESSIM:
    IA_G10_DES3YR:
      BASE: sn_ia_salt2_g10_des3yr.input
    GLOBAL:
      NGEN_UNIT: 1
      RANSEED_REPEAT: 1 12345

  LOWZBIASCOR:
    IA_G10_LOWZ:
      BASE: sn_ia_salt2_g10_lowz.input
      GENSIGMA_SALT2ALPHA: 1E8  1E8
      GENRANGE_SALT2ALPHA: 0.12 0.20
      GENGRID_SALT2ALPHA: 2
      GENSIGMA_SALT2BETA: 1E8  1E8
      GENRANGE_SALT2BETA: 2.6  3.6
      GENGRID_SALT2BETA: 2
    GLOBAL:
      NGEN_UNIT: 3
      RANSEED_REPEAT: 20 12345

  DESBIASCOR:
    IA_G10_DES3YR:
      BASE: sn_ia_salt2_g10_des3yr.input
      GENSIGMA_SALT2ALPHA: 1E8  1E8
      GENRANGE_SALT2ALPHA: 0.12 0.20
      GENGRID_SALT2ALPHA: 2
      GENSIGMA_SALT2BETA: 1E8  1E8
      GENRANGE_SALT2BETA: 2.6  3.6
      GENGRID_SALT2BETA: 2
    GLOBAL:
      NGEN_UNIT: 3
      RANSEED_REPEAT: 20 12345

LCFIT:
  LOWZFIT:
    BASE: lowz.nml
    MASK: LOWZ
  DESFIT:
    BASE: des.nml
    MASK: DES

# Note the stuff below does effectively nothing, but allows
# us to treat spec and photometric samples identically
CLASSIFICATION:
  UNITY:
    CLASSIFIER: UnityClassifier
    MODE: predict

AGGREGATION:
  AGG:
    OPTS:
      INCLUDE_TYPE: True
      PLOT: True

MERGE:
  MERGE:

BIASCOR:
  BCOR:
    DATA:
      - DESSIM
      - LOWZSIM
    BIAS_COR_FITS:
      - DESBIASCOR
      - LOWZBIASCOR
    CLASSIFIER: UNITY

