SIM:
  LOWZSIM:
    IA_G10_LOWZ:
      BASE: sn_ia_salt2_g10_lowz.input
    GLOBAL:
      NGEN_UNIT: 1
      RANSEED_REPEAT: 1 12345

  DESSIM:
    IA_G10_DES3YR:
      BASE: sn_ia_salt2_g10_des3yr.input
    GLOBAL:
      NGEN_UNIT: 1
      RANSEED_REPEAT: 1 12345

  LOWZBIASCOR:
    IA_G10_LOWZ:
      BASE: sn_ia_salt2_g10_lowz.input
      GENSIGMA_SALT2ALPHA: 1E8  1E8
      GENRANGE_SALT2ALPHA: 0.12 0.20
      GENGRID_SALT2ALPHA: 2
      GENSIGMA_SALT2BETA: 1E8  1E8
      GENRANGE_SALT2BETA: 2.6  3.6
      GENGRID_SALT2BETA: 2
    GLOBAL:
      NGEN_UNIT: 5
      RANSEED_REPEAT: 40 12345

  DESBIASCOR:
    IA_G10_DES3YR:
      BASE: sn_ia_salt2_g10_des3yr.input
      GENSIGMA_SALT2ALPHA: 1E8  1E8
      GENRANGE_SALT2ALPHA: 0.12 0.20
      GENGRID_SALT2ALPHA: 2
      GENSIGMA_SALT2BETA: 1E8  1E8
      GENRANGE_SALT2BETA: 2.6  3.6
      GENGRID_SALT2BETA: 2
    GLOBAL:
      NGEN_UNIT: 5
      RANSEED_REPEAT: 40 12345

LCFIT:
  LOWZFITSYS:
    BASE: lowz.nml
    FITOPTS: lowz.fitopts
    MASK: LOWZSIM

  DESFITSYS:
    BASE: des.nml
    FITOPTS: des.fitopts
    MASK: DESSIM

  LOWZFIT:
    BASE: lowz.nml
    MASK: LOWZBIAS

  DESFIT:
    BASE: des.nml
    MASK: DESBIAS


# Note the stuff below does effectively nothing, but allows
# us to treat spec and photometric samples identically
CLASSIFICATION:
  UNITY:
    CLASSIFIER: UnityClassifier
    MODE: predict

AGGREGATION:
  AGG:
    OPTS:
      INCLUDE_TYPE: True
      PLOT: True

MERGE:
  MERGE:

BIASCOR:
  BCOR:
    DATA: [DESSIM, LOWZSIM]
    SIMFILE_BIASCOR: [DESBIASCOR, LOWZBIASCOR]
    CLASSIFIER: UNITY

CREATE_COV:
  ALL:
    OPTS:
      COVOPTS:  # note you'll get an 'ALL' covopt no matter what
        - "[NOSYS] [=DEFAULT,=DEFAULT]"

COSMOMC:
  SN_OMW:
    OPTS:
      INI: sn_omw
      COVOPTS: [ALL, NOSYS]  # If you leave this blank, you get them all. Exact matching
      NUM_WALKERS: 8

  SN_CMB_OMW:
    OPTS:
      INI: sn_cmb_omw
      COVOPTS: [ALL]  # If you leave this blank, you get them all. Exact matching
      NUM_WALKERS: 8

ANALYSE:
  ALL_OMW:
    MASK_COSMOMC: OMW
    OPTS:
      BLIND: w
      # COVOPTS: ALL