DATAPREP:
  TESTDATA:
    OPTS:
      RAW_DIR: $SNDATA_ROOT/lcmerge/SDSS_allCandidates+BOSS
      TYPES:
        IA: [118, 120]
        NONIA: [113, 117, 111, 115, 112, 114, 110]
SIM:
  TRAINSPECFULL:
    IA_SDSS:
      BASE: djbrout_sdss/SIMGEN_SDSS_SALT2.input
    II:
      BASE: djbrout_sdss/SNII_Templates.input
    Ibc:
      BASE: djbrout_sdss/SNIbc_Templates.input
      UVLAM_EXTRAPFLUX: 500
    GLOBAL:
      NGEN_UNIT: 0.2
      RESET_CIDOFF: 2
      RANSEED_REPEAT: 1 12345
      SIMLIB_FILE: djbrout_sdss/SDSS_3year.SIMLIB
      SOLID_ANGLE: 0.08
      SEARCHEFF_zHOST_FILE: /project2/rkessler/SURVEYS/SDSS/USERS/BAP37/SEARCHEFF_zHOST_SDSS_PerfEff.DAT
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_3hr.TEMPLATE 15

  TRAINSPLINEFULL:
    IA_SDSS:
      BASE: djbrout_sdss/SIMGEN_SDSS_SALT2.input
    II:
      BASE: djbrout_sdss/SNII_Templates_spline.input
    Ibc:
      BASE: djbrout_sdss/SNIbc_Templates_spline.input
      UVLAM_EXTRAPFLUX: 500
    GLOBAL:
      NGEN_UNIT: 0.2
      RESET_CIDOFF: 2
      RANSEED_REPEAT: 1 12345
      SIMLIB_FILE: djbrout_sdss/SDSS_3year.SIMLIB
      SOLID_ANGLE: 0.08 # This duplicates a lot of stuff, do I not have multiple genversions implemented?
      SEARCHEFF_zHOST_FILE: /project2/rkessler/SURVEYS/SDSS/USERS/BAP37/SEARCHEFF_zHOST_SDSS_PerfEff.DAT
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_3hr.TEMPLATE 15

LCFIT:
  FIT:
    BASE: djbrout_sdss/sdss.nml
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_3hr.TEMPLATE 20

CLASSIFICATION:
  FITPROBTEST:
    CLASSIFIER: FitProbClassifier
    MODE: predict
    MASK_SIM: TEST

  SNIRF-x1-c-zHD-FITPROB-TRAIN:
    CLASSIFIER: SnirfClassifier
    MODE: train
    MASK_SIM: TRAIN
    OPTS:
      FEATURES: x1 c zHD FITPROB

  SNIRF-x1-c-zHD-FITPROB-TEST:
    CLASSIFIER: SnirfClassifier
    MODE: predict
    MASK_SIM: TEST
    OPTS:
      MODEL: SNIRF-x1-c-zHD-FITPROB-TRAIN
      FEATURES: x1 c zHD FITPROB

AGGREGATION:
  AGG:
    MASK_SIM: TEST
    OPTS:
      INCLUDE_TYPE: True
      PLOT: True