SIM:
  TRAIN_SPEC:
    IA_G10_DES3YR:
      BASE: djbrout_spec_test/SNIa-SALT2.input
    II:
      BASE: djbrout_spec_test/SNII_Templates.input
    Ibc:
      BASE: djbrout_spec_test/SNIbc_Templates.input
      UVLAM_EXTRAPFLUX: 500
    GLOBAL:
      NGEN_UNIT: 0.2
      RESET_CIDOFF: 2  # This might have something to do with the different genversions to make them reset for matching. Ask Dillon
      RANSEED_REPEAT: 1 12345
      SIMLIB_FILE: $PLASTICC_MODELS/LSST_OBSERVATIONS_DDF.SIMLIB
      SOLID_ANGLE: 5.468
      SEARCHEFF_zHOST_FILE: $PLASTICC_MODELS/LSST+4MOST_zHOST_DDF.TEXT
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_1hr.TEMPLATE 10

  TRAIN_SPLINE:
    IA_G10_DES3YR:
      BASE: djbrout_spec_test/SNIa-SALT2.input
    II:
      BASE: djbrout_spec_test/SNII_Templates_spline.input
    Ibc:
      BASE: djbrout_spec_test/SNIbc_Templates_spline.input
      UVLAM_EXTRAPFLUX: 500
    GLOBAL:
      NGEN_UNIT: 0.2
      RESET_CIDOFF: 2
      RANSEED_REPEAT: 1 12345
      SIMLIB_FILE: $PLASTICC_MODELS/LSST_OBSERVATIONS_DDF.SIMLIB
      SOLID_ANGLE: 5.468 # This duplicates a lot of stuff, do I not have multiple genversions implemented?
      SEARCHEFF_zHOST_FILE: $PLASTICC_MODELS/LSST+4MOST_zHOST_DDF.TEXT
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_1hr.TEMPLATE 10

  TEST_SIM:  # For Dillon to flesh out I think. Using SDSS data was it? Just copying the TRAIN_SPEC sim for now
    IA_G10_DES3YR:
      BASE: djbrout_spec_test/SNIa-SALT2.input
    II:
      BASE: djbrout_spec_test/SNII_Templates.input
    Ibc:
      BASE: djbrout_spec_test/SNIbc_Templates.input
      UVLAM_EXTRAPFLUX: 500
    GLOBAL:
      NGEN_UNIT: 0.2
      RESET_CIDOFF: 2
      RANSEED_REPEAT: 1 12345
      SIMLIB_FILE: $PLASTICC_MODELS/LSST_OBSERVATIONS_DDF.SIMLIB
      SOLID_ANGLE: 5.468
      SEARCHEFF_zHOST_FILE: $PLASTICC_MODELS/LSST+4MOST_zHOST_DDF.TEXT
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_1hr.TEMPLATE 10

LCFIT:
  FIT:
    BASE: djbrout_spec_test/lsst.nml
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_1hr.TEMPLATE 10


CLASSIFICATION:
  SNNVANILLATRAIN:
    CLASSIFIER: SuperNNovaClassifier
    MODE: train
    MASK_SIM: TRAIN

  SNNVANILLATEST:
    CLASSIFIER: SuperNNovaClassifier
    MODE: predict
    MASK_SIM: TEST
    OPTS:
      MODEL: SNNVANILLATRAIN

#  SNNVARIATIONALTRAIN:
#    CLASSIFIER: SuperNNovaClassifier
#    MODE: train
#    MASK_SIM: TRAIN
#    OPTS:
#      VARIANT: variational
#
#  SNNVARIATIONALTEST:
#    CLASSIFIER: SuperNNovaClassifier
#    MODE: predict
#    MASK_SIM: TEST
#    OPTS:
#      MODEL: SNNVARIATIONALTRAIN
#      VARIANT: variational
#
#  SNNBAYESIANTRAIN:
#    CLASSIFIER: SuperNNovaClassifier
#    MODE: train
#    MASK_SIM: TRAIN
#    OPTS:
#      VARIANT: bayesian
#
#  SNNBAYESIANTEST:
#    CLASSIFIER: SuperNNovaClassifier
#    MODE: predict
#    MASK_SIM: TEST
#    OPTS:
#      MODEL: SNNBAYESIANTRAIN
#      VARIANT: bayesian
#
#  FITPROBTEST:
#    CLASSIFIER: FitProbClassifier
#    MODE: predict
#    MASK_SIM: TEST
#
#  NNTRAIN:
#    CLASSIFIER: NearestNeighborClassifier
#    MODE: train
#    MASK_SIM: TRAIN
#
#  NNTEST:
#    CLASSIFIER: NearestNeighborClassifier
#    MODE: predict
#    MASK_SIM: TEST
#    OPTS:
#        MODEL: NNTRAIN
#
#  SNIRF-TRAIN:
#    CLASSIFIER: SnirfClassifier
#    MODE: train
#    MASK_SIM: TRAIN
#
#  SNIRF-TEST:
#    CLASSIFIER: SnirfClassifier
#    MODE: predict
#    MASK_SIM: TEST
#    OPTS:
#      MODEL: SNIRF-TRAIN

AGGREGATION:
  AGG:
    MASK_SIM: TEST
    OPTS:
      INCLUDE_TYPE: True
      PLOT: True

MERGE:
  MERGE:
    MASK_SIM: TEST
