# Run a test using the updated fake and sim error fudges and updated spec eff
# and see if the sim looks more like the data


DATAPREP:
  FAKES:
    OPTS:
      RAW_DIR: $DES_ROOT/lcmerge/DESALL_forcePhoto_fake_snana_fits


SIM:
  SIM00:
    IA:
      BASE: fluxerr/fakes.input
    GLOBAL:
      OPT_DEVEL_GENFLUX: 2
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/DES5YR_SIM_ERRORFUDGES.DAT
      FLUXERRMODEL_REDCOV: "griz:0.0"
      RANSEED_REPEAT: 5 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 5

  SIM02:
    IA:
      BASE: fluxerr/fakes.input
    GLOBAL:
      OPT_DEVEL_GENFLUX: 2
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/DES5YR_SIM_ERRORFUDGES.DAT
      FLUXERRMODEL_REDCOV: "griz:0.2"
      RANSEED_REPEAT: 5 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 5

  SIM04:
    IA:
      BASE: fluxerr/fakes.input
    GLOBAL:
      OPT_DEVEL_GENFLUX: 2
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/DES5YR_SIM_ERRORFUDGES.DAT
      FLUXERRMODEL_REDCOV: "griz:0.4"
      RANSEED_REPEAT: 5 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 5

  SIM06:
    IA:
      BASE: fluxerr/fakes.input
    GLOBAL:
      OPT_DEVEL_GENFLUX: 2
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/DES5YR_SIM_ERRORFUDGES.DAT
      FLUXERRMODEL_REDCOV: "griz:0.6"
      RANSEED_REPEAT: 5 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 5

  SIM08:
    IA:
      BASE: fluxerr/fakes.input
    GLOBAL:
      OPT_DEVEL_GENFLUX: 2
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/DES5YR_SIM_ERRORFUDGES.DAT
      FLUXERRMODEL_REDCOV: "griz:0.8"
      RANSEED_REPEAT: 5 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 5

  SIM02i:
    IA:
      BASE: fluxerr/fakes.input
    GLOBAL:
      OPT_DEVEL_GENFLUX: 2
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/DES5YR_SIM_ERRORFUDGES.DAT
      FLUXERRMODEL_REDCOV: "g:0.2,r:0.2,i:0.2,z:0.2"
      RANSEED_REPEAT: 1 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 1

  SIM04i:
    IA:
      BASE: fluxerr/fakes.input
    GLOBAL:
      OPT_DEVEL_GENFLUX: 2
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/DES5YR_SIM_ERRORFUDGES.DAT
      FLUXERRMODEL_REDCOV: "g:0.4,r:0.4,i:0.4,z:0.4"
      RANSEED_REPEAT: 1 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 1

  SIM06i:
    IA:
      BASE: fluxerr/fakes.input
    GLOBAL:
      OPT_DEVEL_GENFLUX: 2
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/DES5YR_SIM_ERRORFUDGES.DAT
      FLUXERRMODEL_REDCOV: "g:0.6,r:0.6,i:0.6,z:0.6"
      RANSEED_REPEAT: 1 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 1

  SIM08i:
    IA:
      BASE: fluxerr/fakes.input
    GLOBAL:
      OPT_DEVEL_GENFLUX: 2
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/DES5YR_SIM_ERRORFUDGES.DAT
      FLUXERRMODEL_REDCOV: "g:0.8,r:0.8,i:0.8,z:0.8"
      RANSEED_REPEAT: 1 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 1

  SIM_MIX:
    IA:
      BASE: fluxerr/fakes.input
    GLOBAL:
      OPT_DEVEL_GENFLUX: 2
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/DES5YR_SIM_ERRORFUDGES.DAT
      FLUXERRMODEL_REDCOV(DEEP): "griz:0.6"
      FLUXERRMODEL_REDCOV(SHALLOW): "g:0.2,r:0.2,i:0.2,z:0.0"
      RANSEED_REPEAT: 1 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 1

  SIM_NOREDCOV:
    IA:
      BASE: fluxerr/fakes.input
    GLOBAL:
      OPT_DEVEL_GENFLUX: 2
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/DES5YR_SIM_ERRORFUDGES.DAT
      RANSEED_REPEAT: 1 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 1

LCFIT:
  D:
    BASE: des.nml
    SNLCINP:
      FLUXERRMODEL_FILE: "'$DES_ROOT/simlibs/DES5YR_FAKES_ERRORFUDGES.DAT'"
      ROOTFILE_OUT: "'FIT.ROOT'"
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 20
      APPEND_TABLE_TEXT: SNRMAX_g SNRMAX_r SNRMAX_i SNRMAX_z chi2_g chi2_r chi2_i chi2_z

ANALYSE:
  HIST_ALL:
    HISTOGRAM: [D_FAKES, D_SIM00, D_SIM02, D_SIM04, D_SIM06, D_SIM08,  D_SIM02i, D_SIM04i, D_SIM06i, D_SIM08i, D_SIM_MIX, D_SIM_NOREDCOV]
  HIST_COMP:
    HISTOGRAM: [D_FAKES, D_SIM_MIX, D_SIM_NOREDCOV]