# After computing the error map from fakes_simlib, we want to make sure the fakes dist
# and the correct sim fakes match their distributions.

DATAPREP:
  FAKES:
    OPTS:
      RAW_DIR: $DES_ROOT/lcmerge/DESALL_forcePhoto_fake_snana_fits

SIM:
  NEWCORR_10:
    IA:
      BASE: fluxerr/fakes.input
    GLOBAL:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/DES5YR_SIM_ERRORFUDGES_LOGSNR_SBMAG_10.DAT
      RANSEED_REPEAT: 5 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 10

  NEWCORR_20:
    IA:
      BASE: fluxerr/fakes.input
    GLOBAL:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/DES5YR_SIM_ERRORFUDGES_LOGSNR_SBMAG_20.DAT
      RANSEED_REPEAT: 5 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 10

  NEWCORR_50:
    IA:
      BASE: fluxerr/fakes.input
    GLOBAL:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/DES5YR_SIM_ERRORFUDGES_LOGSNR_SBMAG_50.DAT
      RANSEED_REPEAT: 5 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 10

  OLDCORR:
    IA:
      BASE: fluxerr/fakes.input
    GLOBAL:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/DES3YR_SIM_ERRORFUDGES.DAT
      RANSEED_REPEAT: 5 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 10

  NOCORR:
    IA:
      BASE: fluxerr/fakes.input
    GLOBAL:
      RANSEED_REPEAT: 5 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 10

LCFIT:
  D:
    BASE: des.nml
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 40

ANALYSE:
  SIM_FAKES_COMP:
    HISTOGRAM: [D_FAKES, D_NEWCORR_10, D_NEWCORR_20, D_NEWCORR_50, D_OLDCORR, D_NOCORR]