SIM:
  FakesY1E1:
    IA:
      BASE: fluxerr/fluxerr_base.input
      SIMLIB_FIELDLIST: E1
      NGEN_SCALE: 0.167
      DNDZ: ZPOLY 0.0939158382461 4.9401375184 -6.96574861099 2.75617274478
      GENMODEL: SALT2.Guy10_LAMOPEN
    GLOBAL:
      RANSEED_REPEAT: 2 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 10