# Run a test using the updated fake and sim error fudges and updated spec eff
# and see if the sim looks more like the data


DATAPREP:
#  FAKES:
#    OPTS:
#      RAW_DIR: $DES_ROOT/lcmerge/DESALL_forcePhoto_fake_snana_fits
  DATA:  # 5 yr photometry sample
    OPTS:
      RAW_DIR: $DES_ROOT/lcmerge/DESALL_forcePhoto_real_snana_fits
      TYPES:
        IA: [1, 101]
        NONIA: [120, 130, 20, 30]
      BLIND: True # Defaults to true anyway! Set to false to unblind

SIM:
  BASE_FUDGE:
    IA_G10:
      BASE: sn_ia_salt2_g10.input
    II_TEMPLATES:
      BASE: sn_collection_maria.input
    GLOBAL:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/DES5YR_SIM_ERRORFUDGES_LOGSNR_SBMAG.dat
      SEARCHEFF_zHOST_FILE: $DES_ROOT/models/searcheff/samtest/efficiency_zHD.dat
      NGEN_UNIT: 0.4
      RANSEED_REPEAT: 20 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_1hr.TEMPLATE 20

  BASE_NOFUDGE:
    IA_G10:
      BASE: sn_ia_salt2_g10.input
    II_TEMPLATES:
      BASE: sn_collection_maria.input
    GLOBAL:
      FLUXERRMODEL_FILE:
      SEARCHEFF_zHOST_FILE: $DES_ROOT/models/searcheff/samtest/efficiency_zHD.dat
      NGEN_UNIT: 0.4
      RANSEED_REPEAT: 20 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_1hr.TEMPLATE 20
LCFIT:
  D:
    BASE: des.nml
    SNLCINP:
      FLUXERRMODEL_FILE:
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 40
  D_5YR_2DERR:
    MASK: DATA
    BASE: des.nml
    SNLCINP:
      FLUXERRMODEL_FILE: "'$DES_ROOT/simlibs/DES5YR_FAKE_ERRORFUDGES_LOGSNR_SBMAG.DAT'"
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 40
  D_5YR_1DERR:
    MASK: DATA
    BASE: des.nml
    SNLCINP:
      FLUXERRMODEL_FILE: "'$DES_ROOT/simlibs/DES5YR_FAKE_ERRORFUDGES_SBMAG.DAT'"
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 40
  D_3YRERR:
    MASK: DATA
    BASE: des.nml
    SNLCINP:
      FLUXERRMODEL_FILE: "'$DES_ROOT/simlibs/DES3YR_FAKE_ERRORFUDGES.DAT'"
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 40

ANALYSE:
  HIST_ALL:
    HISTOGRAM: [D_DATA, D_5YR_1DERR_DATA, D_5YR_2DERR_DATA, D_3YRERR_DATA, D_BASE_FUDGE, D_BASE_NOFUDGE]