# Once I understand whats happening, replace this with a useful comment on why any of this is happening.

SIM:
  FakesY1E1:
    IA:
      BASE: fluxerr/fluxerr_base.input
      GENRANGE_PEAKMJD: 56505 56726
      SIMLIB_FIELDLIST: E1
      DNDZ: ZPOLY 1.0 0.0 0.0 0.0
      GENMODEL: SALT2.Guy10_LAMOPEN
      NGEN_SCALE: 0.01
    GLOBAL:
      RANSEED_REPEAT: 2 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 2