# After computing the error map from fakes_simlib, we want to make sure the fakes dist
# and the correct sim fakes match their distributions.

DATAPREP:
  FAKES:
    OPTS:
      RAW_DIR: $DES_ROOT/lcmerge/DESALL_forcePhoto_fake_snana_fits

SIM:
  NEWCORR_PSF:
    IA:
      BASE: fluxerr/fakes.input
    GLOBAL:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/DES5YR_SIM_ERRORFUDGES_LOGSNR_SBMAG_PSF_20.DAT
      RANSEED_REPEAT: 10 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 10

  NEWCORR:
    IA:
      BASE: fluxerr/fakes.input
    GLOBAL:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/DES5YR_SIM_ERRORFUDGES_LOGSNR_SBMAG.DAT
      RANSEED_REPEAT: 10 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 10

  OLDCORR:
    IA:
      BASE: fluxerr/fakes.input
    GLOBAL:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/DES3YR_SIM_ERRORFUDGES.DAT
      RANSEED_REPEAT: 10 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 10

  NOCORR:
    IA:
      BASE: fluxerr/fakes.input
    GLOBAL:
      RANSEED_REPEAT: 10 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 10

LCFIT:
  D:
    BASE: des.nml
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 40
      APPEND_FITRES: SNRMAX_g SNRMAX_r SNRMAX_i SNRMAX_z

ANALYSE:
  SIM_FAKES_COMP:
    HISTOGRAM: [D_FAKES, D_NEWCORR, D_OLDCORR, D_NOCORR, D_NEWCORR_PSF]

  NO_CORR:
    HISTOGRAM: [D_FAKES, D_NOCORR]
  NEW_CORR:
    HISTOGRAM: [D_FAKES, D_NEWCORR]
  NEW_CORR_PSF:
    HISTOGRAM: [D_FAKES, D_NEWCORR_PSF]
  OLD_CORR:
    HISTOGRAM: [D_FAKES, D_OLDCORR]