# Run a test using the updated fake and sim error fudges and updated spec eff
# and see if the sim looks more like the data


DATAPREP:
  FAKES:
    OPTS:
      RAW_DIR: $DES_ROOT/lcmerge/DESALL_forcePhoto_fake_snana_fits
  DATADES5YR:  # 5 yr photometry sample
    OPTS:
      RAW_DIR: $DES_ROOT/lcmerge/DESALL_forcePhoto_real_snana_fits
      TYPES:
        IA: [1, 101]
        NONIA: [120, 130, 20, 30]
      BLIND: True # Defaults to true anyway! Set to false to unblind

SIM:
  BASE:
    IA_G10:
      BASE: sn_ia_salt2_g10.input
    II_TEMPLATES:
      BASE: sn_collection_maria.input
    GLOBAL:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/DES5YR_SIM_ERRORFUDGES_LOGSNR_SBMAG.dat
      SEARCHEFF_zHOST_FILE: $DES_ROOT/models/searcheff/samtest/efficiency_zHD.dat
      NGEN_UNIT: 1
      RANSEED_REPEAT: 20 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_1hr.TEMPLATE 20

LCFIT:
  FAKES:
    BASE: des.nml
    SNLCINP:
      FLUXERRMODEL_FILE: "'$DES_ROOT/simlibs/DES5YR_FAKES_ERRORFUDGES_LOGSNR_SBMAG.dat'"
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 40


ANALYSE:
  HIST:
    HISTOGRAM: [FAKES_DATADES5YR, FAKES_BASE]