# Once I understand whats happening, replace this with a useful comment on why any of this is happening.

DATAPREP:
  FAKES:
    OPTS:
      RAW_DIR: $DES_ROOT/lcmerge/DESALL_forcePhoto_fake_snana_fits

SIM:
  Y1E1:
    IA:
      BASE: fluxerr/fluxerr_base.input
      GENRANGE_PEAKMJD: 56505 56726
      SIMLIB_FIELDLIST: E1
      DNDZ: ZPOLY 1.0 0.0 0.0 0.0
      GENMODEL: SALT2.Guy10_LAMOPEN
      NGEN_SCALE: 1.0
    GLOBAL:
      RANSEED_REPEAT: 3 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 2

  Y1E2:
    IA:
      BASE: fluxerr/fluxerr_base.input
      GENRANGE_PEAKMJD: 56505 56726
      SIMLIB_FIELDLIST: E2
      DNDZ: ZPOLY 1.0 0.0 0.0 0.0
      GENMODEL: SALT2.Guy10_LAMOPEN
      NGEN_SCALE: 1.0
    GLOBAL:
      RANSEED_REPEAT: 3 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 2

  Y1S1:
    IA:
      BASE: fluxerr/fluxerr_base.input
      GENRANGE_PEAKMJD: 56505 56726
      SIMLIB_FIELDLIST: S1
      DNDZ: ZPOLY 1.0 0.0 0.0 0.0
      GENMODEL: SALT2.Guy10_LAMOPEN
      NGEN_SCALE: 1.0
    GLOBAL:
      RANSEED_REPEAT: 3 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 2

  Y1S2:
    IA:
      BASE: fluxerr/fluxerr_base.input
      GENRANGE_PEAKMJD: 56505 56726
      SIMLIB_FIELDLIST: S2
      DNDZ: ZPOLY 1.0 0.0 0.0 0.0
      GENMODEL: SALT2.Guy10_LAMOPEN
      NGEN_SCALE: 1.0
    GLOBAL:
      RANSEED_REPEAT: 3 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 2

  Y1C1:
    IA:
      BASE: fluxerr/fluxerr_base.input
      GENRANGE_PEAKMJD: 56505 56726
      SIMLIB_FIELDLIST: C1
      DNDZ: ZPOLY 1.0 0.0 0.0 0.0
      GENMODEL: SALT2.Guy10_LAMOPEN
      NGEN_SCALE: 1.0
    GLOBAL:
      RANSEED_REPEAT: 3 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 2

  Y1C2:
    IA:
      BASE: fluxerr/fluxerr_base.input
      GENRANGE_PEAKMJD: 56505 56726
      SIMLIB_FIELDLIST: C2
      DNDZ: ZPOLY 1.0 0.0 0.0 0.0
      GENMODEL: SALT2.Guy10_LAMOPEN
      NGEN_SCALE: 1.0
    GLOBAL:
      RANSEED_REPEAT: 3 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 2

  Y1C3:
    IA:
      BASE: fluxerr/fluxerr_base.input
      GENRANGE_PEAKMJD: 56505 56726
      SIMLIB_FIELDLIST: C3
      DNDZ: ZPOLY 1.0 0.0 0.0 0.0
      GENMODEL: SALT2.Guy10_LAMOPEN
      NGEN_SCALE: 1.0
    GLOBAL:
      RANSEED_REPEAT: 3 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 2

  Y1X1:
    IA:
      BASE: fluxerr/fluxerr_base.input
      GENRANGE_PEAKMJD: 56505 56726
      SIMLIB_FIELDLIST: X1
      DNDZ: ZPOLY 1.0 0.0 0.0 0.0
      GENMODEL: SALT2.Guy10_LAMOPEN
      NGEN_SCALE: 1.0
    GLOBAL:
      RANSEED_REPEAT: 3 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 2

  Y1X2:
    IA:
      BASE: fluxerr/fluxerr_base.input
      GENRANGE_PEAKMJD: 56505 56726
      SIMLIB_FIELDLIST: X2
      DNDZ: ZPOLY 1.0 0.0 0.0 0.0
      GENMODEL: SALT2.Guy10_LAMOPEN
      NGEN_SCALE: 1.0
    GLOBAL:
      RANSEED_REPEAT: 3 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 2

  Y1X3:
    IA:
      BASE: fluxerr/fluxerr_base.input
      GENRANGE_PEAKMJD: 56505 56726
      SIMLIB_FIELDLIST: X3
      DNDZ: ZPOLY 1.0 0.0 0.0 0.0
      GENMODEL: SALT2.Guy10_LAMOPEN
      NGEN_SCALE: 1.0
    GLOBAL:
      RANSEED_REPEAT: 3 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 2

  Y2E1:
    IA:
      BASE: fluxerr/fluxerr_base.input
      GENRANGE_PEAKMJD: 56870  57090
      SIMLIB_FIELDLIST: E1
      DNDZ: ZPOLY 1.0 0.0 0.0 0.0
      GENMODEL: SALT2.Guy10_UV2IR
      NGEN_SCALE: 1.0
    GLOBAL:
      RANSEED_REPEAT: 3 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 2

  Y2E2:
    IA:
      BASE: fluxerr/fluxerr_base.input
      GENRANGE_PEAKMJD: 56870  57090
      SIMLIB_FIELDLIST: E2
      DNDZ: ZPOLY 1.0 0.0 0.0 0.0
      GENMODEL: SALT2.Guy10_UV2IR
      NGEN_SCALE: 1.0
    GLOBAL:
      RANSEED_REPEAT: 3 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 2

  Y2S1:
    IA:
      BASE: fluxerr/fluxerr_base.input
      GENRANGE_PEAKMJD: 56870  57090
      SIMLIB_FIELDLIST: S1
      DNDZ: ZPOLY 1.0 0.0 0.0 0.0
      GENMODEL: SALT2.Guy10_UV2IR
      NGEN_SCALE: 1.0
    GLOBAL:
      RANSEED_REPEAT: 3 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 2

  Y2S2:
    IA:
      BASE: fluxerr/fluxerr_base.input
      GENRANGE_PEAKMJD: 56870  57090
      SIMLIB_FIELDLIST: S2
      DNDZ: ZPOLY 1.0 0.0 0.0 0.0
      GENMODEL: SALT2.Guy10_UV2IR
      NGEN_SCALE: 1.0
    GLOBAL:
      RANSEED_REPEAT: 3 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 2

  Y2C1:
    IA:
      BASE: fluxerr/fluxerr_base.input
      GENRANGE_PEAKMJD: 56870  57090
      SIMLIB_FIELDLIST: C1
      DNDZ: ZPOLY 1.0 0.0 0.0 0.0
      GENMODEL: SALT2.Guy10_UV2IR
      NGEN_SCALE: 1.0
    GLOBAL:
      RANSEED_REPEAT: 3 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 2

  Y2C2:
    IA:
      BASE: fluxerr/fluxerr_base.input
      GENRANGE_PEAKMJD: 56870  57090
      SIMLIB_FIELDLIST: C2
      DNDZ: ZPOLY 1.0 0.0 0.0 0.0
      GENMODEL: SALT2.Guy10_UV2IR
      NGEN_SCALE: 1.0
    GLOBAL:
      RANSEED_REPEAT: 3 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 2

  Y2C3:
    IA:
      BASE: fluxerr/fluxerr_base.input
      GENRANGE_PEAKMJD: 56870  57090
      SIMLIB_FIELDLIST: C3
      DNDZ: ZPOLY 1.0 0.0 0.0 0.0
      GENMODEL: SALT2.Guy10_UV2IR
      NGEN_SCALE: 1.0
    GLOBAL:
      RANSEED_REPEAT: 3 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 2

  Y2X1:
    IA:
      BASE: fluxerr/fluxerr_base.input
      GENRANGE_PEAKMJD: 56870  57090
      SIMLIB_FIELDLIST: X1
      DNDZ: ZPOLY 1.0 0.0 0.0 0.0
      GENMODEL: SALT2.Guy10_UV2IR
      NGEN_SCALE: 1.0
    GLOBAL:
      RANSEED_REPEAT: 3 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 2

  Y2X2:
    IA:
      BASE: fluxerr/fluxerr_base.input
      GENRANGE_PEAKMJD: 56870  57090
      SIMLIB_FIELDLIST: X2
      DNDZ: ZPOLY 1.0 0.0 0.0 0.0
      GENMODEL: SALT2.Guy10_UV2IR
      NGEN_SCALE: 1.0
    GLOBAL:
      RANSEED_REPEAT: 3 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 2

  Y2X3:
    IA:
      BASE: fluxerr/fluxerr_base.input
      GENRANGE_PEAKMJD: 56870  57090
      SIMLIB_FIELDLIST: X3
      DNDZ: ZPOLY 1.0 0.0 0.0 0.0
      GENMODEL: SALT2.Guy10_UV2IR
      NGEN_SCALE: 1.0
    GLOBAL:
      RANSEED_REPEAT: 3 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 2

  Y3E1:
    IA:
      BASE: fluxerr/fluxerr_base.input
      GENRANGE_PEAKMJD: 57225  57460
      SIMLIB_FIELDLIST: E1
      DNDZ: ZPOLY 1.0 0.0 0.0 0.0
      GENMODEL: SALT2.Guy10_UV2IR
      NGEN_SCALE: 1.0
    GLOBAL:
      RANSEED_REPEAT: 3 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 2

  Y3E2:
    IA:
      BASE: fluxerr/fluxerr_base.input
      GENRANGE_PEAKMJD: 57225  57460
      SIMLIB_FIELDLIST: E2
      DNDZ: ZPOLY 1.0 0.0 0.0 0.0
      GENMODEL: SALT2.Guy10_UV2IR
      NGEN_SCALE: 1.0
    GLOBAL:
      RANSEED_REPEAT: 3 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 2

  Y3S1:
    IA:
      BASE: fluxerr/fluxerr_base.input
      GENRANGE_PEAKMJD: 57225  57460
      SIMLIB_FIELDLIST: S1
      DNDZ: ZPOLY 1.0 0.0 0.0 0.0
      GENMODEL: SALT2.Guy10_UV2IR
      NGEN_SCALE: 1.0
    GLOBAL:
      RANSEED_REPEAT: 3 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 2

  Y3S2:
    IA:
      BASE: fluxerr/fluxerr_base.input
      GENRANGE_PEAKMJD: 57225  57460
      SIMLIB_FIELDLIST: S2
      DNDZ: ZPOLY 1.0 0.0 0.0 0.0
      GENMODEL: SALT2.Guy10_UV2IR
      NGEN_SCALE: 1.0
    GLOBAL:
      RANSEED_REPEAT: 3 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 2

  Y3C1:
    IA:
      BASE: fluxerr/fluxerr_base.input
      GENRANGE_PEAKMJD: 57225  57460
      SIMLIB_FIELDLIST: C1
      DNDZ: ZPOLY 1.0 0.0 0.0 0.0
      GENMODEL: SALT2.Guy10_UV2IR
      NGEN_SCALE: 1.0
    GLOBAL:
      RANSEED_REPEAT: 3 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 2

  Y3C2:
    IA:
      BASE: fluxerr/fluxerr_base.input
      GENRANGE_PEAKMJD: 57225  57460
      SIMLIB_FIELDLIST: C2
      DNDZ: ZPOLY 1.0 0.0 0.0 0.0
      GENMODEL: SALT2.Guy10_UV2IR
      NGEN_SCALE: 1.0
    GLOBAL:
      RANSEED_REPEAT: 3 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 2

  Y3C3:
    IA:
      BASE: fluxerr/fluxerr_base.input
      GENRANGE_PEAKMJD: 57225  57460
      SIMLIB_FIELDLIST: C3
      DNDZ: ZPOLY 1.0 0.0 0.0 0.0
      GENMODEL: SALT2.Guy10_UV2IR
      NGEN_SCALE: 1.0
    GLOBAL:
      RANSEED_REPEAT: 3 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 2

  Y3X1:
    IA:
      BASE: fluxerr/fluxerr_base.input
      GENRANGE_PEAKMJD: 57225  57460
      SIMLIB_FIELDLIST: X1
      DNDZ: ZPOLY 1.0 0.0 0.0 0.0
      GENMODEL: SALT2.Guy10_UV2IR
      NGEN_SCALE: 1.0
    GLOBAL:
      RANSEED_REPEAT: 3 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 2

  Y3X2:
    IA:
      BASE: fluxerr/fluxerr_base.input
      GENRANGE_PEAKMJD: 57225  57460
      SIMLIB_FIELDLIST: X2
      DNDZ: ZPOLY 1.0 0.0 0.0 0.0
      GENMODEL: SALT2.Guy10_UV2IR
      NGEN_SCALE: 1.0
    GLOBAL:
      RANSEED_REPEAT: 3 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 2

  Y3X3:
    IA:
      BASE: fluxerr/fluxerr_base.input
      GENRANGE_PEAKMJD: 57225  57460
      SIMLIB_FIELDLIST: X3
      DNDZ: ZPOLY 1.0 0.0 0.0 0.0
      GENMODEL: SALT2.Guy10_UV2IR
      NGEN_SCALE: 1.0
    GLOBAL:
      RANSEED_REPEAT: 3 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 2

  Y4E1:
    IA:
      BASE: fluxerr/fluxerr_base.input
      GENRANGE_PEAKMJD: 57604  57835
      SIMLIB_FIELDLIST: E1
      DNDZ: ZPOLY 1.0 0.0 0.0 0.0
      GENMODEL: SALT2.Guy10_UV2IR
      NGEN_SCALE: 1.0
    GLOBAL:
      RANSEED_REPEAT: 3 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 2

  Y4E2:
    IA:
      BASE: fluxerr/fluxerr_base.input
      GENRANGE_PEAKMJD: 57604  57835
      SIMLIB_FIELDLIST: E2
      DNDZ: ZPOLY 1.0 0.0 0.0 0.0
      GENMODEL: SALT2.Guy10_UV2IR
      NGEN_SCALE: 1.0
    GLOBAL:
      RANSEED_REPEAT: 3 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 2

  Y4S1:
    IA:
      BASE: fluxerr/fluxerr_base.input
      GENRANGE_PEAKMJD: 57604  57835
      SIMLIB_FIELDLIST: S1
      DNDZ: ZPOLY 1.0 0.0 0.0 0.0
      GENMODEL: SALT2.Guy10_UV2IR
      NGEN_SCALE: 1.0
    GLOBAL:
      RANSEED_REPEAT: 3 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 2

  Y4S2:
    IA:
      BASE: fluxerr/fluxerr_base.input
      GENRANGE_PEAKMJD: 57604  57835
      SIMLIB_FIELDLIST: S2
      DNDZ: ZPOLY 1.0 0.0 0.0 0.0
      GENMODEL: SALT2.Guy10_UV2IR
      NGEN_SCALE: 1.0
    GLOBAL:
      RANSEED_REPEAT: 3 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 2

  Y4C1:
    IA:
      BASE: fluxerr/fluxerr_base.input
      GENRANGE_PEAKMJD: 57604  57835
      SIMLIB_FIELDLIST: C1
      DNDZ: ZPOLY 1.0 0.0 0.0 0.0
      GENMODEL: SALT2.Guy10_UV2IR
      NGEN_SCALE: 1.0
    GLOBAL:
      RANSEED_REPEAT: 3 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 2

  Y4C2:
    IA:
      BASE: fluxerr/fluxerr_base.input
      GENRANGE_PEAKMJD: 57604  57835
      SIMLIB_FIELDLIST: C2
      DNDZ: ZPOLY 1.0 0.0 0.0 0.0
      GENMODEL: SALT2.Guy10_UV2IR
      NGEN_SCALE: 1.0
    GLOBAL:
      RANSEED_REPEAT: 3 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 2

  Y4C3:
    IA:
      BASE: fluxerr/fluxerr_base.input
      GENRANGE_PEAKMJD: 57604  57835
      SIMLIB_FIELDLIST: C3
      DNDZ: ZPOLY 1.0 0.0 0.0 0.0
      GENMODEL: SALT2.Guy10_UV2IR
      NGEN_SCALE: 1.0
    GLOBAL:
      RANSEED_REPEAT: 3 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 2

  Y4X1:
    IA:
      BASE: fluxerr/fluxerr_base.input
      GENRANGE_PEAKMJD: 57604  57835
      SIMLIB_FIELDLIST: X1
      DNDZ: ZPOLY 1.0 0.0 0.0 0.0
      GENMODEL: SALT2.Guy10_UV2IR
      NGEN_SCALE: 1.0
    GLOBAL:
      RANSEED_REPEAT: 3 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 2

  Y4X2:
    IA:
      BASE: fluxerr/fluxerr_base.input
      GENRANGE_PEAKMJD: 57604  57835
      SIMLIB_FIELDLIST: X2
      DNDZ: ZPOLY 1.0 0.0 0.0 0.0
      GENMODEL: SALT2.Guy10_UV2IR
      NGEN_SCALE: 1.0
    GLOBAL:
      RANSEED_REPEAT: 3 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 2

  Y4X3:
    IA:
      BASE: fluxerr/fluxerr_base.input
      GENRANGE_PEAKMJD: 57604  57835
      SIMLIB_FIELDLIST: X3
      DNDZ: ZPOLY 1.0 0.0 0.0 0.0
      GENMODEL: SALT2.Guy10_UV2IR
      NGEN_SCALE: 1.0
    GLOBAL:
      RANSEED_REPEAT: 3 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 2

LCFIT:
  FAKES:
    BASE: fluxerr/fluxerr_base.nml