# After computing the error map from fakes_simlib, we want to make sure the fakes dist
# and the correct sim fakes match their distributions.

DATAPREP:
  FAKES:
    OPTS:
      RAW_DIR: $DES_ROOT/lcmerge/DESALL_forcePhoto_fake_snana_fits

SIM:
  FAKESIMLIB:
    IA:
      BASE: fluxerr/fakes.input
    GLOBAL:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/DES5YR_SIM_ERRORFUDGES_LOGSNR_SBMAG.DAT
      RANSEED_REPEAT: 10 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 10

LCFIT:
  D:
    BASE: des.nml
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 40

ANALYSE:
  SIM_FAKES_COMP:
    HISTOGRAM: [D_FAKES, D_FAKESIMLIB]