DATAPREP:
  DATADES5YR:  # 5 yr photometry sample
    OPTS:
      RAW_DIR: $DES_ROOT/lcmerge/DESALL_forcePhoto_real_snana_fits
      TYPES:
        IA: [1, 101]
        NONIA: [120, 130, 20, 30]
      BLIND: False # Defaults to true anyway! Set to false to unblind
SIM:
  SIMDES_G10_REDCOV:
    IA_G10:
      BASE: sn_ia_salt2_g10_shifted.input
    GLOBAL:
      OPT_DEVEL_GENFLUX: 2
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/DES5YR_SIM_ERRORFUDGES.DAT
      FLUXERRMODEL_REDCOV(DEEP): "griz:0.3"
      FLUXERRMODEL_REDCOV(SHALLOW): "griz:0.0"
      NGEN_UNIT: 1.0
      RANSEED_REPEAT: 5 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 5

  SIMDES_C11_REDCOV:
    IA_C11:
      BASE: sn_ia_salt2_c11_shifted.input
    GLOBAL:
      OPT_DEVEL_GENFLUX: 2
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/DES5YR_SIM_ERRORFUDGES.DAT
      FLUXERRMODEL_REDCOV(DEEP): "griz:0.3"
      FLUXERRMODEL_REDCOV(SHALLOW): "griz:0.0"
      NGEN_UNIT: 1.0
      RANSEED_REPEAT: 5 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 5

  SIMDES_G10:
    IA_G10:
      BASE: sn_ia_salt2_g10_shifted.input
    GLOBAL:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/DES5YR_SIM_ERRORFUDGES.DAT
      NGEN_UNIT: 1.0
      RANSEED_REPEAT: 5 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 5

  SIMDES_C11:
    IA_C11:
      BASE: sn_ia_salt2_c11_shifted.input
    GLOBAL:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/DES5YR_SIM_ERRORFUDGES.DAT
      NGEN_UNIT: 1.0
      RANSEED_REPEAT: 5 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 5


LCFIT:
  D:
    BASE: des.nml
    SNLCINP:
      FLUXERRMODEL_FILE: "'$DES_ROOT/simlibs/DES5YR_FAKES_ERRORFUDGES.DAT'"
      ROOTFILE_OUT: "'FIT.ROOT'"
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 20
      APPEND_TABLE_TEXT: SNRMAX_g SNRMAX_r SNRMAX_i SNRMAX_z

ANALYSE:
  5YR_REDCOV_COMP:
    HISTOGRAM: [D_SIMDES_C11, D_SIMDES_G10, D_SIMDES_C11_REDCOV, D_SIMDES_G10_REDCOV, D_DATADES5YR]