# After computing the error map from fakes_simlib, we want to make sure the fakes dist
# and the correct sim fakes match their distributions.

DATAPREP:
  FAKES:
    OPTS:
      RAW_DIR: $DES_ROOT/lcmerge/DESALL_forcePhoto_fake_snana_fits

SIM:
  NEWCORR_5:
    IA:
      BASE: fluxerr/fakes.input
    GLOBAL:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/DES5YR_SIM_ERRORFUDGES_LOGSNR_SBMAG_5.DAT
      RANSEED_REPEAT: 1 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2.TEMPLATE 2

  NOCORR:
    IA:
      BASE: fluxerr/fakes.input
    GLOBAL:
      RANSEED_REPEAT: 1 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2.TEMPLATE 2

LCFIT:
  D:
    BASE: des.nml
    FITINP:
      FITMODEL_NAME: "'SALT2.Guy10_UV2IR'"
      USE_MODEL_MAGERR: F
    SNLCINP:
      ROOTFILE_OUT: "'FIT.ROOT'"
      SNTABLE_LIST: "'FITRES FITRES+RESIDUALS LCPLOT(text:csv)'"
      FLUXERRMODEL_FILE: "'$DES_ROOT/simlibs/DES5YR_FAKES_ERRORFUDGES_LOGSNR_SBMAG_5.DAT'"
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2.TEMPLATE 30
      APPEND_TABLE_TEXT: SNRMAX_g SNRMAX_r SNRMAX_i SNRMAX_z chi2_g chi2_r chi2_i chi2_z

ANALYSE:
  SIM_FAKES_COMP:
    HISTOGRAM: [D_FAKES, D_NOCORR, D_NEWCORR_5] # D_OLDCORR, D_NEWCORR_PSF_5, D_NEWCORR_PSF_4, D_NEWCORR_4]