# After computing the error map from fakes_simlib, we want to make sure the fakes dist
# and the correct sim fakes match their distributions.

DATAPREP:
  FAKES:
    OPTS:
      RAW_DIR: $DES_ROOT/lcmerge/DESALL_forcePhoto_fake_snana_fits

SIM:
  NEWCORR_5:
    IA:
      BASE: fluxerr/fakes.input
    GLOBAL:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/DES5YR_SIM_ERRORFUDGES_DIFFIMG_LOGSNR_SBMAG_5.DAT
      RANSEED_REPEAT: 1 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 1

  NOCORR:
    IA:
      BASE: fluxerr/fakes.input
    GLOBAL:
      RANSEED_REPEAT: 1 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 1

LCFIT:
  D:
    BASE: fluxerr/fluxerr_base.nml
    SNLCINP:
      FLUXERRMODEL_FILE: "'$DES_ROOT/simlibs/DES5YR_FAKES_ERRORFUDGES_DIFFIMG_LOGSNR_SBMAG_5.DAT'"
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 30
      APPEND_TABLE_TEXT: SNRMAX_g SNRMAX_r SNRMAX_i SNRMAX_z chi2_g chi2_r chi2_i chi2_z

  D_N:
    BASE: fluxerr/fluxerr_base.nml
    MASK_SIM: FAKES
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 30
      APPEND_TABLE_TEXT: SNRMAX_g SNRMAX_r SNRMAX_i SNRMAX_z chi2_g chi2_r chi2_i chi2_z
ANALYSE:
  SIM_FAKES_COMP:
    HISTOGRAM: [D_FAKES, D_N_FAKES, D_NOCORR, D_NEWCORR_5] # D_OLDCORR, D_NEWCORR_PSF_5, D_NEWCORR_PSF_4, D_NEWCORR_4]