# After computing the error map from fakes_simlib, we want to make sure the fakes dist
# and the correct sim fakes match their distributions.

DATAPREP:
  FAKES:
    OPTS:
      RAW_DIR: $DES_ROOT/lcmerge/DESALL_forcePhoto_fake_snana_fits

SIM:
  NEWCORR_PSF_7:
    IA:
      BASE: fluxerr/fakes.input
    GLOBAL:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/DES5YR_SIM_ERRORFUDGES_LOGSNR_SBMAG_PSF_7.DAT
      RANSEED_REPEAT: 5 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 5

  NEWCORR_PSF_10:
    IA:
      BASE: fluxerr/fakes.input
    GLOBAL:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/DES5YR_SIM_ERRORFUDGES_LOGSNR_SBMAG_PSF_10.DAT
      RANSEED_REPEAT: 5 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 5

  NEWCORR_PSF_5:
    IA:
      BASE: fluxerr/fakes.input
    GLOBAL:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/DES5YR_SIM_ERRORFUDGES_LOGSNR_SBMAG_PSF_5.DAT
      RANSEED_REPEAT: 5 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 5

  NEWCORR_PSF_4:
    IA:
      BASE: fluxerr/fakes.input
    GLOBAL:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/DES5YR_SIM_ERRORFUDGES_LOGSNR_SBMAG_PSF_4.DAT
      RANSEED_REPEAT: 5 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 5

  NEWCORR_7:
    IA:
      BASE: fluxerr/fakes.input
    GLOBAL:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/DES5YR_SIM_ERRORFUDGES_LOGSNR_SBMAG_7.DAT
      RANSEED_REPEAT: 5 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 5

  NEWCORR_10:
    IA:
      BASE: fluxerr/fakes.input
    GLOBAL:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/DES5YR_SIM_ERRORFUDGES_LOGSNR_SBMAG_10.DAT
      RANSEED_REPEAT: 5 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 5

  NEWCORR_5:
    IA:
      BASE: fluxerr/fakes.input
    GLOBAL:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/DES5YR_SIM_ERRORFUDGES_LOGSNR_SBMAG_5.DAT
      RANSEED_REPEAT: 5 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 5

  OLDCORR:
    IA:
      BASE: fluxerr/fakes.input
    GLOBAL:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/DES3YR_SIM_ERRORFUDGES.DAT
      RANSEED_REPEAT: 5 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 5

  NEWCORR_4:
    IA:
      BASE: fluxerr/fakes.input
    GLOBAL:
      FLUXERRMODEL_FILE: $DES_ROOT/simlibs/DES5YR_SIM_ERRORFUDGES_LOGSNR_SBMAG_4.DAT
      RANSEED_REPEAT: 5 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 5

LCFIT:
  D:
    BASE: des.nml
    SNLCINP:
      ROOTFILE_OUT: "'FIT.ROOT'"
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 20
      APPEND_TABLE_TEXT: SNRMAX_g SNRMAX_r SNRMAX_i SNRMAX_z

ANALYSE:
  SIM_FAKES_COMP:
    HISTOGRAM: [D_FAKES, D_OLDCORR, D_NEWCORR_PSF_5, D_NEWCORR_PSF_4, D_NEWCORR_PSF_10, D_NEWCORR_PSF_7, D_NEWCORR_5, D_NEWCORR_10, D_NEWCORR_7, D_NEWCORR_4]