# Once I understand whats happening, replace this with a useful comment on why any of this is happening.

SIM:
  FakesY1E1:
    IA:
      BASE: fluxerr/fluxerr_base.input
      GENRANGE_PEAKMJD: 56505 56726
      SIMLIB_FIELDLIST: E1
      DNDZ: ZPOLY 1.0 0.0 0.0 0.0
      GENMODEL: SALT2.Guy10_LAMOPEN
      NGEN_SCALE: 0.1
    GLOBAL:
      RANSEED_REPEAT: 2 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 2

  FakesY1E2:
    IA:
      BASE: fluxerr/fluxerr_base.input
      GENRANGE_PEAKMJD: 56505 56726
      SIMLIB_FIELDLIST: E2
      DNDZ: ZPOLY 1.0 0.0 0.0 0.0
      GENMODEL: SALT2.Guy10_LAMOPEN
      NGEN_SCALE: 0.1
    GLOBAL:
      RANSEED_REPEAT: 2 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 2

  FakesY1S1:
    IA:
      BASE: fluxerr/fluxerr_base.input
      GENRANGE_PEAKMJD: 56505 56726
      SIMLIB_FIELDLIST: S1
      DNDZ: ZPOLY 1.0 0.0 0.0 0.0
      GENMODEL: SALT2.Guy10_LAMOPEN
      NGEN_SCALE: 0.1
    GLOBAL:
      RANSEED_REPEAT: 2 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 2

  FakesY1S2:
    IA:
      BASE: fluxerr/fluxerr_base.input
      GENRANGE_PEAKMJD: 56505 56726
      SIMLIB_FIELDLIST: S2
      DNDZ: ZPOLY 1.0 0.0 0.0 0.0
      GENMODEL: SALT2.Guy10_LAMOPEN
      NGEN_SCALE: 0.1
    GLOBAL:
      RANSEED_REPEAT: 2 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 2

  FakesY1C1:
    IA:
      BASE: fluxerr/fluxerr_base.input
      GENRANGE_PEAKMJD: 56505 56726
      SIMLIB_FIELDLIST: C1
      DNDZ: ZPOLY 1.0 0.0 0.0 0.0
      GENMODEL: SALT2.Guy10_LAMOPEN
      NGEN_SCALE: 0.1
    GLOBAL:
      RANSEED_REPEAT: 2 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 2

  FakesY1C2:
    IA:
      BASE: fluxerr/fluxerr_base.input
      GENRANGE_PEAKMJD: 56505 56726
      SIMLIB_FIELDLIST: C2
      DNDZ: ZPOLY 1.0 0.0 0.0 0.0
      GENMODEL: SALT2.Guy10_LAMOPEN
      NGEN_SCALE: 0.1
    GLOBAL:
      RANSEED_REPEAT: 2 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 2

  FakesY1C3:
    IA:
      BASE: fluxerr/fluxerr_base.input
      GENRANGE_PEAKMJD: 56505 56726
      SIMLIB_FIELDLIST: C3
      DNDZ: ZPOLY 1.0 0.0 0.0 0.0
      GENMODEL: SALT2.Guy10_LAMOPEN
      NGEN_SCALE: 0.1
    GLOBAL:
      RANSEED_REPEAT: 2 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 2

  FakesY1X1:
    IA:
      BASE: fluxerr/fluxerr_base.input
      GENRANGE_PEAKMJD: 56505 56726
      SIMLIB_FIELDLIST: X1
      DNDZ: ZPOLY 1.0 0.0 0.0 0.0
      GENMODEL: SALT2.Guy10_LAMOPEN
      NGEN_SCALE: 0.1
    GLOBAL:
      RANSEED_REPEAT: 2 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 2

  FakesY1X2:
    IA:
      BASE: fluxerr/fluxerr_base.input
      GENRANGE_PEAKMJD: 56505 56726
      SIMLIB_FIELDLIST: X2
      DNDZ: ZPOLY 1.0 0.0 0.0 0.0
      GENMODEL: SALT2.Guy10_LAMOPEN
      NGEN_SCALE: 0.1
    GLOBAL:
      RANSEED_REPEAT: 2 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 2

  FakesY1X3:
    IA:
      BASE: fluxerr/fluxerr_base.input
      GENRANGE_PEAKMJD: 56505 56726
      SIMLIB_FIELDLIST: X3
      DNDZ: ZPOLY 1.0 0.0 0.0 0.0
      GENMODEL: SALT2.Guy10_LAMOPEN
      NGEN_SCALE: 0.1
    GLOBAL:
      RANSEED_REPEAT: 2 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 2