DATAPREP:
  DATALOWZ:  # lowz combined sample
    OPTS:
      RAW_DIR: $DES_ROOT/lcmerge/DES3YR_LOWZ_COMBINED_FITS
      TYPES:
        IA: [1, 101]
        NONIA: [120, 130, 20, 30]
  DATADES3YR:  # 3yr spec sample
    OPTS:
      RAW_DIR: $DES_ROOT/lcmerge/DESALL_specType_SMP_real_snana_fits
      TYPES:
        IA: [1, 101]
        NONIA: [120, 130, 20, 30]

SIM:
  LOWZSIMBIAS:
    IA_G10_LOWZ:
      BASE: sn_ia_salt2_g10_lowz.input
      GENSIGMA_SALT2ALPHA: 1E8  1E8
      GENRANGE_SALT2ALPHA: 0.12 0.20
      GENGRID_SALT2ALPHA: 2
      GENSIGMA_SALT2BETA: 1E8  1E8
      GENRANGE_SALT2BETA: 2.6  3.6
      GENGRID_SALT2BETA: 2
    GLOBAL:
      NGEN_UNIT: 20
      RANSEED_REPEAT: 10 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 10

  DESSIMBIAS3YRIA:
    IA_G10_DES3YR:
      BASE: sn_ia_salt2_g10_des3yr.input
      GENSIGMA_SALT2ALPHA: 1E8  1E8
      GENRANGE_SALT2ALPHA: 0.12 0.20
      GENGRID_SALT2ALPHA: 2
      GENSIGMA_SALT2BETA: 1E8  1E8
      GENRANGE_SALT2BETA: 2.6  3.6
      GENGRID_SALT2BETA: 2
    GLOBAL:
      NGEN_UNIT: 20
      RANSEED_REPEAT: 10 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 10

LCFIT:
  LOLD:
    BASE: lowz.nml
    MASK: LOWZ
    SNLCINP:
      USE_MINOS: F
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 20

  LNEW:
    BASE: lowz.nml
    MASK: DATALOWZ  # Change this to just LOWZ if you want to also check effects of modifying biascor sample
    FITINP:
      FITMODEL_NAME: "'$DES_USERS/gtaylor/SALT_SURFACES/SALT2.GT_03_MWEBV_ZP'"
    SNLCINP:
      USE_MINOS: F
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 20

  DOLD:
    BASE: des.nml
    MASK: DES
    SNLCINP:
      USE_MINOS: F
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 20
  DNEW:
    BASE: des.nml
    MASK: DATADES  # Change this to just DES if you want to also check effects of modifying biascor sample
    FITINP:
      FITMODEL_NAME: "'$DES_USERS/gtaylor/SALT_SURFACES/SALT2.GT_03_MWEBV_ZP'"
    SNLCINP:
      USE_MINOS: F
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 20

CLASSIFICATION:
  UNITY:
    CLASSIFIER: UnityClassifier
    MODE: predict

AGGREGATION:
  AGG:

MERGE:
  MERGE:

BIASCOR:
  3YR_OLD:
    BASE: bbc_spec.input
    DATA: [DOLD_DATADES3YR, LOLD_DATALOWZ]
    SIMFILE_BIASCOR: [DOLD_DESSIMBIAS3YRIA, LOLD_LOWZSIMBIAS]
    CLASSIFIER: UNITY
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 5

  3YR_NEW:
    BASE: bbc_spec.input
    DATA: [DNEW_DATADES3YR, LNEW_DATALOWZ]
    SIMFILE_BIASCOR: [DOLD_DESSIMBIAS3YRIA, LOLD_LOWZSIMBIAS]
    CLASSIFIER: UNITY
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 5


CREATE_COV:
  ALL:


COSMOMC:
  SN_OMW:
    OPTS:
      INI: sn_omw
      NUM_WALKERS: 20

#  SN_CMB_OMW:
#    OPTS:
#      INI: sn_cmb_omw
#      COVOPTS: [ALL]
#      NUM_WALKERS: 20

ANALYSE:
#  ALL_OMW:
#    MASK_COSMOMC: OMW
#    OPTS:
#      BLIND: w

  SNONLY:
    MASK_COSMOMC: SN_OMW

# Results should be in $PIPPIN_OUTPUT/GEORGIE_SALT2_SURFACE/9_ANALYSE/SNONLY... or something like that.
