# Generates bias cor simulations that can be used by other configurations

ALIAS:
  GRID_G10: &grid_g10
    GENSIGMA_SALT2ALPHA: 1E8  1E8
    GENRANGE_SALT2ALPHA: 0.12 0.20
    GENGRID_SALT2ALPHA: 2
    GENSIGMA_SALT2BETA: 1E8  1E8
    GENRANGE_SALT2BETA: 2.6  3.6
    GENGRID_SALT2BETA: 2
  GRID_C11: &grid_c11
    GENSIGMA_SALT2ALPHA: 1E8  1E8
    GENRANGE_SALT2ALPHA:  0.10 0.24
    GENGRID_SALT2ALPHA: 2
    GENSIGMA_SALT2BETA: 1E8  1E8
    GENRANGE_SALT2BETA:  3.3  4.3
    GENGRID_SALT2BETA: 2
  NUMS: &nums
    NGEN_UNIT: 5
    RANSEED_REPEAT: 20 12345

SIM:
  LOWZSIMBIAS_G10:
    IA_G10_LOWZ:
      BASE: surveys/lowz/sims_ia/sn_ia_salt2_g10_lowz.input
      <<: *grid_g10
    GLOBAL:
      <<: *nums
      NGEN_UNIT: 10

  LOWZSIMBIAS_C11:
    IA_C11_LOWZ:
      BASE: surveys/lowz/sims_ia/sn_ia_salt2_c11_lowz.input
      <<: *grid_c11
    GLOBAL:
      <<: *nums
      NGEN_UNIT: 10

  DESSIMBIAS3YRIA_G10:
    IA_G10_DES3YR:
      BASE: surveys/des/sims_ia/sn_ia_salt2_g10_des3yr.input
      <<: *grid_g10
    GLOBAL: *nums

  DESSIMBIAS3YRIA_C11:
    IA_C11_DES3YR:
      BASE: surveys/des/sims_ia/sn_ia_salt2_c11_des3yr.input
      <<: *grid_c11
    GLOBAL: *nums

  DESSIMBIAS5YRIA_G10:
    IA_G10:
      BASE: surveys/des/sims_ia/sn_ia_salt2_g10_des5yr.input
      <<: *grid_g10
    GLOBAL: *nums

  DESSIMBIAS5YRIA_C11:
    IA_G10:
      BASE: surveys/des/sims_ia/sn_ia_salt2_c11_des5yr.input
      <<: *grid_c11
    GLOBAL: *nums


  DESSIMBIAS5YRCC:
    IBC_TEMPLATES:
      BASE: surveys/des/sims_cc/sn_collection_maria.input
    GLOBAL: *nums
