SIM:
  TRAININGSIM:
    IA_G10:
      BASE: surveys/des/sims_ia/sn_ia_salt2_g10_des5yr.input
    II:
      BASE: surveys/des/sims_cc/sn_collection_maria_split_a.input
    GLOBAL:
      NGEN_UNIT: 5
      RANSEED_REPEAT: 20 12345

  TESTSIM:
    IA_C11:
      BASE: surveys/des/sims_ia/sn_ia_salt2_c11_des5yr.input
    II:
      BASE: surveys/des/sims_cc/sn_collection_maria_split_b.input
    GLOBAL:
      NGEN_UNIT: 1
      RANSEED_REPEAT: 20 12345

LCFIT:
  TESTFIT:
    BASE: surveys/des/lcfit_nml/des_5yr.nml
    SNLCINP:
      USE_MINOS: F

CLASSIFICATION:
  SNNTRAIN:
    CLASSIFIER: SuperNNovaClassifier
    MODE: train
    MASK_SIM: TRAINING

  SNNTEST:
    CLASSIFIER: SuperNNovaClassifier
    MODE: predict
    OPTS:
      MODEL: SNNTRAIN

  SNNVARTRAIN:
    CLASSIFIER: SuperNNovaClassifier
    MODE: train
    MASK_SIM: TRAINING
    OPTS:
      VARIANT: variational

  SNNVARTEST:
    CLASSIFIER: SuperNNovaClassifier
    MODE: predict
    OPTS:
      MODEL: SNNVARTRAIN
      VARIANT: variational

  SNNBAYTRAIN:
    CLASSIFIER: SuperNNovaClassifier
    MODE: train
    MASK_SIM: TRAINING
    OPTS:
      VARIANT: bayesian

  SNNBAYTEST:
    CLASSIFIER: SuperNNovaClassifier
    MODE: predict
    OPTS:
      MODEL: SNNBAYTRAIN
      VARIANT: bayesian

  FITPROBTEST:
    CLASSIFIER: FitProbClassifier
    MODE: predict

  NNTRAIN:
    CLASSIFIER: NearestNeighborPyClassifier
    MODE: train
    MASK_SIM: TRAINING

  NNTEST:
    CLASSIFIER: NearestNeighborPyClassifier
    MODE: predict
    OPTS:
        MODEL: NNTRAIN

  SNIRFTRAIN:
    CLASSIFIER: SnirfClassifier
    MODE: train
    MASK_SIM: TRAINING

  SNIRFTEST:
    CLASSIFIER: SnirfClassifier
    MODE: predict
    OPTS:
      MODEL: SNIRFTRAIN

  SNIRF_SMALL_TRAIN:
    CLASSIFIER: SnirfClassifier
    MODE: train
    MASK_SIM: TRAINING
    OPTS:
      N_ESTIMATORS: 100
      MIN_SAMPLES_SPLIT: 10
      MIN_SAMPLES_LEAF: 5
      MAX_DEPTH: 10

  SNIRF_SMALL_TEST:
    CLASSIFIER: SnirfClassifier
    MODE: predict
    OPTS:
      MODEL: SNIRF_SMALL_TRAIN
      N_ESTIMATORS: 100
      MIN_SAMPLES_SPLIT: 10
      MIN_SAMPLES_LEAF: 5
      MAX_DEPTH: 10

AGGREGATION:
  AGG:
    OPTS:
      INCLUDE_TYPE: True
      PLOT: True

MERGE:
  MERGE:
