# Generates bias cor simulations that can be used by other configurations

ALIAS:
  GRID_G10: &grid_g10
    GENSIGMA_SALT2ALPHA: 1E8  1E8
    GENRANGE_SALT2ALPHA: 0.12 0.20
    GENGRID_SALT2ALPHA: 2
    GENSIGMA_SALT2BETA: 1E8  1E8
    GENRANGE_SALT2BETA: 2.6  3.6
    GENGRID_SALT2BETA: 2
  GRID_C11: &grid_c11
    GENSIGMA_SALT2ALPHA: 1E8  1E8
    GENRANGE_SALT2ALPHA:  0.10 0.24
    GENGRID_SALT2ALPHA: 2
    GENSIGMA_SALT2BETA: 1E8  1E8
    GENRANGE_SALT2BETA:  3.3  4.3
    GENGRID_SALT2BETA: 2
  NUMS: &nums
    NGEN_UNIT: 10
    RANSEED_REPEAT: 30 12345
    BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2b.TEMPLATE 20

SIM:
  LOWZSIMBIAS_G10:
    IA_G10_LOWZ:
      BASE: surveys/lowz/sims_ia/sn_ia_salt2_g10_lowz.input
      <<: *grid_g10
    GLOBAL:
      <<: *nums
      NGEN_UNIT: 10

  LOWZSIMBIAS_C11:
    IA_C11_LOWZ:
      BASE: surveys/lowz/sims_ia/sn_ia_salt2_c11_lowz.input
      <<: *grid_c11
    GLOBAL:
      <<: *nums
      NGEN_UNIT: 10

  DESSIMBIAS3YRIA_G10:
    IA_G10_DES3YR:
      BASE: surveys/des/sims_ia/sn_ia_salt2_g10_des3yr.input
      <<: *grid_g10
    GLOBAL: *nums

  DESSIMBIAS3YRIA_C11:
    IA_C11_DES3YR:
      BASE: surveys/des/sims_ia/sn_ia_salt2_c11_des3yr.input
      <<: *grid_c11
    GLOBAL: *nums

  DESSIMBIAS5YRIA_G10:
    IA_G10:
      BASE: surveys/des/sims_ia/sn_ia_salt2_g10_des5yr.input
      <<: *grid_g10
    GLOBAL: *nums

  DESSIMBIAS5YRIA_C11:
    IA_G10:
      BASE: surveys/des/sims_ia/sn_ia_salt2_c11_des5yr.input
      <<: *grid_c11
    GLOBAL: *nums

  DESSIMBIAS5YRCC:
    IBC_TEMPLATES:
      BASE: surveys/des/sims_cc/sn_collection_maria.input
    GLOBAL: *nums

  DESTRAIN:
    IA_G10:
      BASE: surveys/des/sims_ia/sn_ia_salt2_c11_des5yr.input
      GENMODEL: SALT2.P18_UV2IR
    II:
      BASE: surveys/des/sims_cc/sn_collection_maria_split_a.input
    GLOBAL:
      <<: *nums

  DESTEST:
    IA_C11:
      BASE: surveys/des/sims_ia/sn_ia_salt2_g10_des5yr.input
      GENMODEL: SALT2.P18_UV2IR
    II:
      BASE: surveys/des/sims_cc/sn_collection_maria_split_b.input
    GLOBAL:
      NGEN_UNIT: 1
      RANSEED_REPEAT: 20 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2b.TEMPLATE 20


LCFIT:
  D:
    BASE: surveys/des/lcfit_nml/des_5yr.nml
    MASK: DES
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2b.TEMPLATE 20

  L:
    BASE: surveys/lowz/lcfit_nml/lowz.nml
    MASK: LOWZ
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2b.TEMPLATE 20


CLASSIFICATION:
  SNNTRAIN:
    CLASSIFIER: SuperNNovaClassifier
    MODE: train
    MASK_SIM: TRAIN

  SNNTEST:
    CLASSIFIER: SuperNNovaClassifier
    MODE: predict
    OPTS:
      MODEL: SNNTRAIN

  FITPROBTEST:
    CLASSIFIER: FitProbClassifier
    MODE: predict

  SNIRFTRAIN:
    CLASSIFIER: SnirfClassifier
    MODE: train
    MASK_SIM: TRAIN

  SNIRFTEST:
    CLASSIFIER: SnirfClassifier
    MODE: predict
    OPTS:
      MODEL: SNIRFTRAIN

AGGREGATION:
  AGG:


MERGE:
  MERGE:
