SIM:
  LOWZSIM:
    IA_G10_LOWZ:
      BASE: sn_ia_salt2_g10_lowz.input
    IA_C11_LOWZ:
      BASE: sn_ia_salt2_c11_lowz.input
    GLOBAL:
      NGEN_UNIT: 0.1
      RANSEED_REPEAT: 1 12345

LCFIT:
  TESTFIT:
    BASE: lowz.nml

CLASSIFICATION:
  UNITY:
    CLASSIFIER: UnityClassifier
    MODE: predict

AGGREGATION:
  AGG:
    OPTS:
      INCLUDE_TYPE: True
      PLOT: True

MERGE:
  MERGE:
