SIM:
  FakesY1E1:
    Ia:
      BASE: fluxerr/base.input
      SIMLIB_FIELDLIST: E1
      NGEN_SCALE: 0.167
      DNDZ: ZPOLY 0.0939158382461 4.9401375184 -6.96574861099 2.75617274478
      GENRANGE_PEAKMJD: 56505 56726
      GENRANGE_TREST: -15.0 65
      TGRIDSTEP_MODEL_INTERP: 4.0
      GENRANGE_MWEBV: 0.0413 0.04131
      GENMODEL: SALT2.Guy10_LAMOPEN