SIM:
  TRAIN:
    IA_G10:
      BASE: sn_ia_salt2_g10.input
    GLOBAL:
      NGEN_UNIT: 0.1
  TEST:
    IA_G10:
      BASE: sn_ia_salt2_g10.input
    GLOBAL:
      NGEN_UNIT: 0.1
      RANSEED_CHANGE: 2 12345

LCFIT:
  F:
    BASE: des.nml
    SNLCINP:
      USE_MINOS: F


CLASSIFICATION:
  SNNVANILLATRAIN:
    CLASSIFIER: SuperNNovaClassifier
    MODE: train
    MASK_SIM: TRAIN

  SNNVANILLATEST:
    CLASSIFIER: SuperNNovaClassifier
    MODE: predict
    MASK: TEST
    OPTS:
      MODEL: SNNVANILLATRAIN

  SNNVARIATIONALTRAIN:
    CLASSIFIER: SuperNNovaClassifier
    MODE: train
    MASK_SIM: TRAIN
    OPTS:
      VARIANT: variational

  SNNVARIATIONALTEST:
    CLASSIFIER: SuperNNovaClassifier
    MODE: predict
    MASK: TEST
    OPTS:
      MODEL: SNNVARIATIONALTRAIN
      VARIANT: variational

  SNNBAYESIANTRAIN:
    CLASSIFIER: SuperNNovaClassifier
    MODE: train
    MASK_SIM: TRAIN
    OPTS:
      VARIANT: bayesian

  SNNBAYESIANTEST:
    CLASSIFIER: SuperNNovaClassifier
    MODE: predict
    MASK: TEST
    OPTS:
      MODEL: SNNBAYESIANTRAIN
      VARIANT: bayesian

  FITPROBTEST:
    CLASSIFIER: FitProbClassifier
    MODE: predict
    MASK: TEST

  NNTRAIN:
    CLASSIFIER: NearestNeighborClassifier
    MODE: train
    MASK_SIM: TRAIN

  NNTEST:
    CLASSIFIER: NearestNeighborClassifier
    MODE: predict
    MASK_SIM: TEST
    OPTS:
        MODEL: NNTRAIN

  SNIRF-TRAIN:
    CLASSIFIER: SnirfClassifier
    MODE: train
    MASK_SIM: TRAIN

  SNIRF-TEST:
    CLASSIFIER: SnirfClassifier
    MODE: predict
    MASK_SIM: TEST
    OPTS:
      MODEL: SNIRF-TRAIN


AGGREGATION:
  AGG:
    MASK_SIM: TEST
    OPTS:
      PLOT: True

MERGE:
  MERGE:
    MASK_FIT: TEST