DATAPREP:
  DATALOWZ:  # lowz combined sample
    OPTS:
      RAW_DIR: $DES_ROOT/lcmerge/DES3YR_LOWZ_COMBINED_FITS
      TYPES:
        IA: [1, 101]
        NONIA: [120, 130, 20, 30]
      BLIND: True

  DATAFOUND:  # Foundation sample
    OPTS:
      RAW_DIR: $SNDATA_ROOT/lcmerge/Foundation_DR1
      TYPES:
        IA: [1, 101]
        NONIA: [120, 130, 20, 30]
      BLIND: True

  DATADES5YR:  # 5 yr photometry sample
    OPTS:
      RAW_DIR: $DES_ROOT/lcmerge/DESALL_forcePhoto_real_snana_fits
      TYPES:
        IA: [1, 101]
        NONIA: [120, 130, 20, 30]
      BLIND: True

SIM:
  DESSIMBIAS5YRIA_C11:
    EXTERNAL: $PIPPIN_OUTPUT/GLOBAL/1_SIM/DESSIMBIAS5YRIA_C11
  DESSIMBIAS5YRIA_G10:
    EXTERNAL: $PIPPIN_OUTPUT/GLOBAL/1_SIM/DESSIMBIAS5YRIA_G10
  DESSIMBIAS5YRCC:
    EXTERNAL: $PIPPIN_OUTPUT/GLOBAL/1_SIM/DESSIMBIAS5YRCC

  LOWZSIMBIAS_G10:
    EXTERNAL: $PIPPIN_OUTPUT/GLOBAL/1_SIM/LOWZSIMBIAS_G10
  LOWZSIMBIAS_C11:
    EXTERNAL: $PIPPIN_OUTPUT/GLOBAL/1_SIM/LOWZSIMBIAS_C11

  FOUNDSIMBIAS_G10:
    EXTERNAL: $PIPPIN_OUTPUT/GLOBAL/1_SIM/FOUNDSIMBIAS_G10
  FOUNDSIMBIAS_C11:
    EXTERNAL: $PIPPIN_OUTPUT/GLOBAL/1_SIM/FOUNDSIMBIAS_C11

LCFIT:
  DS:
    BASE: surveys/des/lcfit_nml/des_5yr.nml
    MASK: DATADES
    FITOPTS: surveys/global/lcfit_fitopts/global.yml
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 20

  # For the biascor sims, fit without fitopt
  D:
    BASE: surveys/des/lcfit_nml/des_5yr.nml
    MASK: DESSIM
    EXTERNAL_DIRS:
      - $PIPPIN_OUTPUT/GLOBAL/2_LCFIT/D_DESSIMBIAS5YRIA_C11
      - $PIPPIN_OUTPUT/GLOBAL/2_LCFIT/D_DESSIMBIAS5YRIA_G10
      - $PIPPIN_OUTPUT/GLOBAL/2_LCFIT/D_DESSIMBIAS5YRCC

  LS:
    BASE: surveys/lowz/lcfit_nml/lowz.nml
    MASK: DATALOWZ
    FITOPTS: surveys/global/lcfit_fitopts/global.yml
    SNLCINP:
      USE_MINOS: F
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 20

  L:
    BASE: surveys/lowz/lcfit_nml/lowz.nml
    MASK: LOWZSIM
    SNLCINP:
      USE_MINOS: F
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 20
    EXTERNAL_DIRS:
      - $PIPPIN_OUTPUT/GLOBAL/2_LCFIT/L_LOWZSIMBIAS_G10
      - $PIPPIN_OUTPUT/GLOBAL/2_LCFIT/L_LOWZSIMBIAS_C11

  FS:
    BASE: surveys/foundation/lcfit_nml/foundation.nml
    MASK: DATAFOUND
    FITOPTS: surveys/global/lcfit_fitopts/global.yml
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2b.TEMPLATE 20

  F:
    BASE: surveys/foundation/lcfit_nml/foundation.nml
    MASK: FOUNDSIM
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2b.TEMPLATE 20
    EXTERNAL_DIRS:
      - $PIPPIN_OUTPUT/GLOBAL/2_LCFIT/F_FOUNDSIMBIAS_G10
      - $PIPPIN_OUTPUT/GLOBAL/2_LCFIT/F_FOUNDSIMBIAS_C11

CLASSIFICATION:
  SNNTEST:
    CLASSIFIER: SuperNNovaClassifier
    MODE: predict
    MASK_SIM: DES
    OPTS:
      MODEL: $PIPPIN_OUTPUT/GLOBAL/3_CLAS/SNNTRAIN_DESTRAIN/model.pt
    EXTERNAL_DIRS:
      - $PIPPIN_OUTPUT/GLOBAL/3_CLAS/SNNTEST_DESSIMBIAS5YRIA_C11_SNNTRAIN_DESTRAIN
      - $PIPPIN_OUTPUT/GLOBAL/3_CLAS/SNNTEST_DESSIMBIAS5YRIA_G10_SNNTRAIN_DESTRAIN
      - $PIPPIN_OUTPUT/GLOBAL/3_CLAS/SNNTEST_DESSIMBIAS5YRCC_SNNTRAIN_DESTRAIN
      - $PIPPIN_OUTPUT/GLOBAL/3_CLAS/SNNTEST_LOWZSIMBIAS_G10_SNNTRAIN_DESTRAIN
      - $PIPPIN_OUTPUT/GLOBAL/3_CLAS/SNNTEST_LOWZSIMBIAS_C11_SNNTRAIN_DESTRAIN
      - $PIPPIN_OUTPUT/GLOBAL/3_CLAS/SNNTEST_FOUNDSIMBIAS_G10_SNNTRAIN_DESTRAIN
      - $PIPPIN_OUTPUT/GLOBAL/3_CLAS/SNNTEST_FOUNDSIMBIAS_C11_SNNTRAIN_DESTRAIN

  FITPROBTEST:
    CLASSIFIER: FitProbClassifier
    MODE: predict
    MASK_SIM: DES
    EXTERNAL_DIRS:
      - $PIPPIN_OUTPUT/GLOBAL/3_CLAS/FITPROBTEST_D_DESSIMBIAS5YRIA_C11
      - $PIPPIN_OUTPUT/GLOBAL/3_CLAS/FITPROBTEST_D_DESSIMBIAS5YRIA_G10
      - $PIPPIN_OUTPUT/GLOBAL/3_CLAS/FITPROBTEST_D_DESSIMBIAS5YRCC
      - $PIPPIN_OUTPUT/GLOBAL/3_CLAS/FITPROBTEST_L_LOWZSIMBIAS_G10
      - $PIPPIN_OUTPUT/GLOBAL/3_CLAS/FITPROBTEST_L_LOWZSIMBIAS_C11
      - $PIPPIN_OUTPUT/GLOBAL/3_CLAS/FITPROBTEST_F_FOUNDSIMBIAS_G10
      - $PIPPIN_OUTPUT/GLOBAL/3_CLAS/FITPROBTEST_F_FOUNDSIMBIAS_C11

  SNIRFTEST:
    CLASSIFIER: SnirfClassifier
    MODE: predict
    MASK_SIM: DES
    OPTS:
      MODEL: $PIPPIN_OUTPUT/GLOBAL/3_CLAS/SNIRFTRAIN_D_DESTRAIN/model.pkl
    EXTERNAL_DIRS:
      - $PIPPIN_OUTPUT/GLOBAL/3_CLAS/SNIRFTEST_D_DESSIMBIAS5YRIA_C11_SNIRFTRAIN_D_DESTRAIN
      - $PIPPIN_OUTPUT/GLOBAL/3_CLAS/SNIRFTEST_D_DESSIMBIAS5YRIA_G10_SNIRFTRAIN_D_DESTRAIN
      - $PIPPIN_OUTPUT/GLOBAL/3_CLAS/SNIRFTEST_D_DESSIMBIAS5YRCC_SNIRFTRAIN_D_DESTRAIN
      - $PIPPIN_OUTPUT/GLOBAL/3_CLAS/SNIRFTEST_L_LOWZSIMBIAS_C11_SNIRFTRAIN_D_DESTRAIN
      - $PIPPIN_OUTPUT/GLOBAL/3_CLAS/SNIRFTEST_L_LOWZSIMBIAS_G10_SNIRFTRAIN_D_DESTRAIN
      - $PIPPIN_OUTPUT/GLOBAL/3_CLAS/SNIRFTEST_F_FOUNDSIMBIAS_C11_SNIRFTRAIN_D_DESTRAIN
      - $PIPPIN_OUTPUT/GLOBAL/3_CLAS/SNIRFTEST_F_FOUNDSIMBIAS_G10_SNIRFTRAIN_D_DESTRAIN

AGGREGATION:
  AGG:
    EXTERNAL_DIRS:
      - $PIPPIN_OUTPUT/GLOBAL/4_AGG/AGG_DESSIMBIAS5YRIA_C11
      - $PIPPIN_OUTPUT/GLOBAL/4_AGG/AGG_DESSIMBIAS5YRIA_G10
      - $PIPPIN_OUTPUT/GLOBAL/4_AGG/AGG_DESSIMBIAS5YRCC
      - $PIPPIN_OUTPUT/GLOBAL/4_AGG/AGG_LOWZSIMBIAS_C11
      - $PIPPIN_OUTPUT/GLOBAL/4_AGG/AGG_LOWZSIMBIAS_G10
      - $PIPPIN_OUTPUT/GLOBAL/4_AGG/AGG_FOUNDSIMBIAS_C11
      - $PIPPIN_OUTPUT/GLOBAL/4_AGG/AGG_FOUNDSIMBIAS_G10
MERGE:
  MERGE:
    EXTERNAL_DIRS:
      - $PIPPIN_OUTPUT/GLOBAL/5_MERGE/MERGE_D_DESSIMBIAS5YRIA_C11
      - $PIPPIN_OUTPUT/GLOBAL/5_MERGE/MERGE_D_DESSIMBIAS5YRIA_G10
      - $PIPPIN_OUTPUT/GLOBAL/5_MERGE/MERGE_D_DESSIMBIAS5YRCC
      - $PIPPIN_OUTPUT/GLOBAL/5_MERGE/MERGE_L_LOWZSIMBIAS_C11
      - $PIPPIN_OUTPUT/GLOBAL/5_MERGE/MERGE_L_LOWZSIMBIAS_G10
      - $PIPPIN_OUTPUT/GLOBAL/5_MERGE/MERGE_F_FOUNDSIMBIAS_C11
      - $PIPPIN_OUTPUT/GLOBAL/5_MERGE/MERGE_F_FOUNDSIMBIAS_G10

BIASCOR:
  5YR:
    DATA: [DS_DATADES5YR, LS_DATALOWZ, FS_DATAFOUND]
    SIMFILE_BIASCOR: [D_DESSIMBIAS5YRIA_G10, L_LOWZSIMBIAS_G10, F_FOUNDSIMBIAS_G10]
    SIMFILE_CCPRIOR: D_DESSIMBIAS5YRCC
    CLASSIFIER: SNNTEST
    MUOPTS:
      SCATTER_C11:
        SIMFILE_BIASCOR: [D_DESSIMBIAS5YRIA_C11, L_LOWZSIMBIAS_C11, F_FOUNDSIMBIAS_C11]
      CLAS_SNIRF:
        CLASSIFIER: SNIRFTEST
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 40

CREATE_COV:
  ALL:
    OPTS:
      COVOPTS:
        - "[NOSYS] [=DEFAULT,=DEFAULT]"
        - "[SCATTER] [=DEFAULT,+SCATTER]"
        - "[CLASSIFICATION] [=DEFAULT,+CLAS]"

COSMOMC:
  SN_OMW:
    OPTS:
      INI: sn_omw.ini

ANALYSE:
  ALL_OMW:
    MASK_COSMOMC: OMW
#    MASK_BIASCOR: 5YR
