DATAPREP:
  DATALOWZ:  # lowz combined sample
    OPTS:
      RAW_DIR: $DES_ROOT/lcmerge/DES3YR_LOWZ_COMBINED_FITS
      TYPES:
        IA: [1, 101]
        NONIA: [120, 130, 20, 30]
      BLIND: True

  DATAFOUND:  # Foundation sample
    OPTS:
      RAW_DIR: $SNDATA_ROOT/lcmerge/Foundation_DR1
      TYPES:
        IA: [1, 101]
        NONIA: [120, 130, 20, 30]
      BLIND: True

  DATADES5YR:  # 5 yr photometry sample
    OPTS:
      RAW_DIR: $DES_ROOT/lcmerge/DESALL_forcePhoto_real_snana_fits
      TYPES:
        IA: [1, 101]
        NONIA: [120, 130, 20, 30]
      BLIND: True


LCFIT:
  DS:
    BASE: surveys/des/lcfit_nml/des_5yr.nml
    MASK: DES
    FITOPTS: surveys/global/lcfit_fitopts/global.yml
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 60
  D:
    BASE: surveys/des/lcfit_nml/des_5yr.nml
    MASK: DES

  LS:
    BASE: surveys/lowz/lcfit_nml/lowz.nml
    MASK: LOWZ
    FITOPTS: surveys/global/lcfit_fitopts/global.yml
    SNLCINP:
      USE_MINOS: F
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 20
  L:
    BASE: surveys/lowz/lcfit_nml/lowz.nml
    MASK: LOWZ
    SNLCINP:
      USE_MINOS: F
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 20

  FS:
    BASE: surveys/foundation/lcfit_nml/foundation.nml
    MASK: FOUND
    FITOPTS: surveys/global/lcfit_fitopts/global.yml
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2b.TEMPLATE 20
  F:
    BASE: surveys/foundation/lcfit_nml/foundation.nml
    MASK: FOUND
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2b.TEMPLATE 20
