DATAPREP:

  DATALOWZ:  # lowz combined sample
    OPTS:
      RAW_DIR: $DES_ROOT/lcmerge/DES3YR_LOWZ_COMBINED_FITS
      TYPES:
        IA: [1, 101]
        NONIA: [120, 130, 20, 30]
      BLIND: False

  DATADES3YR:  # 3yr spec sample
    OPTS:
      RAW_DIR: $DES_ROOT/lcmerge/DESALL_specType_SMP_real_snana_fits
      TYPES:
        IA: [1, 101]
        NONIA: [120, 130, 20, 30]
      BLIND: False

SIM:
  DESSIMBIAS3YRIA_C11:
    EXTERNAL: $PIPPIN_OUTPUT/GLOBAL/1_SIM/DESSIMBIAS3YRIA_C11
  DESSIMBIAS3YRIA_G10:
    EXTERNAL: $PIPPIN_OUTPUT/GLOBAL/1_SIM/DESSIMBIAS3YRIA_G10

  LOWZSIMBIAS_G10:
    EXTERNAL: $PIPPIN_OUTPUT/GLOBAL/1_SIM/LOWZSIMBIAS_G10
  LOWZSIMBIAS_C11:
    EXTERNAL: $PIPPIN_OUTPUT/GLOBAL/1_SIM/LOWZSIMBIAS_C11

LCFIT:
  L:
    BASE: surveys/lowz/lcfit_nml/lowz.nml
    MASK: LOWZ
    SNLCINP:
      USE_MINOS: F
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 20
    EXTERNAL_DIRS:
      - $PIPPIN_OUTPUT/GLOBAL/2_LCFIT/L_LOWZSIMBIAS_G10
      - $PIPPIN_OUTPUT/GLOBAL/2_LCFIT/L_LOWZSIMBIAS_C11

  D:
    BASE: surveys/des/lcfit_nml/des_3yr.nml
    MASK: DES
    SNLCINP:
      USE_MINOS: F
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 20
    EXTERNAL_DIRS:
      - $PIPPIN_OUTPUT/GLOBAL/2_LCFIT/D_DESSIMBIAS3YRIA_C11
      - $PIPPIN_OUTPUT/GLOBAL/2_LCFIT/D_DESSIMBIAS3YRIA_G10

AGGREGATION:
  AGG:
    EXTERNAL_DIRS:
      - $PIPPIN_OUTPUT/GLOBAL/4_AGG/AGG_LOWZSIMBIAS_G10
      - $PIPPIN_OUTPUT/GLOBAL/4_AGG/AGG_LOWZSIMBIAS_C11
      - $PIPPIN_OUTPUT/GLOBAL/4_AGG/AGG_DESSIMBIAS3YRIA_C11
      - $PIPPIN_OUTPUT/GLOBAL/4_AGG/AGG_DESSIMBIAS3YRIA_G10
MERGE:
  MERGE:
    EXTERNAL_DIRS:
      - $PIPPIN_OUTPUT/GLOBAL/5_MERGE/MERGE_L_LOWZSIMBIAS_G10
      - $PIPPIN_OUTPUT/GLOBAL/5_MERGE/MERGE_L_LOWZSIMBIAS_C11
      - $PIPPIN_OUTPUT/GLOBAL/5_MERGE/MERGE_D_DESSIMBIAS3YRIA_C11
      - $PIPPIN_OUTPUT/GLOBAL/5_MERGE/MERGE_D_DESSIMBIAS3YRIA_G10

BIASCOR:
  3YR:
    BASE: surveys/des/bbc/bbc_3yr.input
    DATA: [D_DATADES3YR, L_DATALOWZ]
    SIMFILE_BIASCOR: [D_DESSIMBIAS3YRIA_G10, L_LOWZSIMBIAS_G10]
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_10hr.TEMPLATE 5
      chi2max: 16


CREATE_COV:
  ALL:
    OPTS:
      COVOPTS:
        - "[NOSYS] [=DEFAULT,=DEFAULT]"


COSMOMC:
  SN_OMW:
    OPTS:
      INI: sn_omw
      COVOPTS: [ALL, NOSYS]
      NUM_WALKERS: 40

  SN_CMB_OMW:
    OPTS:
      INI: sn_cmb_omw
      COVOPTS: [ALL]
      NUM_WALKERS: 20

  CMB_OMW:
    OPTS:
      INI: cmb_omw

ANALYSE:
  ALL_OMW:
    MASK_COSMOMC: OMW

