DATAPREP:
  DATADES5YR:  # 5 yr photometry sample
    OPTS:
      RAW_DIR: $DES_ROOT/lcmerge/DESALL_forcePhoto_real_snana_fits
      TYPES:
        IA: [1, 101]
        NONIA: [120, 130, 20, 30]
      BLIND: True
  DATALOWZ:  # lowz combined sample
    OPTS:
      RAW_DIR: $DES_ROOT/lcmerge/DES3YR_LOWZ_COMBINED_FITS
      TYPES:
        IA: [1, 101]
        NONIA: [120, 130, 20, 30]
      BLIND: False


SIM:
  DESLIKE_G10:
    IA_G10:
      BASE: surveys/des/sims_ia/sn_ia_salt2_g10_des5yr.input
    IAX:
      BASE: surveys/des/sims_cc/sn_iax_dust.input
    IA91BG:
      BASE: surveys/des/sims_cc/sn_ia91bg.input
    CC_TEMPLATES:
      BASE: surveys/des/sims_cc/sn_collection_maria_dust1.input
    GLOBAL:
      NGEN_UNIT: 1
      RANSEED_REPEAT: 20 12345

  DESLIKE_C11:
    IA_C11:
      BASE: surveys/des/sims_ia/sn_ia_salt2_c11_des5yr.input
    IAX:
      BASE: surveys/des/sims_cc/sn_iax_dust.input
    IA91BG:
      BASE: surveys/des/sims_cc/sn_ia91bg.input
    CC_TEMPLATES:
      BASE: surveys/des/sims_cc/sn_collection_maria_dust1.input
    GLOBAL:
      NGEN_UNIT: 1
      RANSEED_REPEAT: 20 12345

    LOWZLIKE_G10:
      IA_G10_LOWZ:
        BASE: surveys/lowz/sims_ia/sn_ia_salt2_g10_lowz.input
      GLOBAL:
      NGEN_UNIT: 1
      RANSEED_REPEAT: 20 12345

    LOWZLIKE_C11:
      IA_C11_LOWZ:
        BASE: surveys/lowz/sims_ia/sn_ia_salt2_c11_lowz.input
      GLOBAL:
      NGEN_UNIT: 1
      RANSEED_REPEAT: 20 12345

LCFIT:
  D:
    BASE: surveys/des/lcfit_nml/des_5yr.nml
    MASK: DES
  L:
    BASE: surveys/lowz/lcfit_nml/lowz.nml
    MASK: LOWZ

ANALYSE:
  DES_COMPARISON:
    MASK_LCFIT: DES
  LOWZ_COMPARISON:
    MASK_LCFIT: LOWZ