SIM:
  DES:
    IA_G10:
      BASE: sn_ia_salt2_g10.input
    IA_C11:
      BASE: sn_ia_salt2_c11.input
    IAX:
      BASE: sn_iax.input
      DNDZ_ALLSCALE: 3.0
    IA91BG:
      BASE: sn_ia91bg.input
      DNDZ_ALLSCALE: 3.0
    IBC_MOSFIT:
      BASE: sn_ibc_mosfit.input
      DNDZ_ALLSCALE: 0.5
    IBC_TEMPLATES:
      BASE: sn_ibc_templates.input
      DNDZ_ALLSCALE: 0.5
    II_NMF:
      BASE: sn_ii_nmf.input
      DNDZ_ALLSCALE: 1.0
    II_TEMPLATES:
      BASE: sn_ii_templates.input
      DNDZ_ALLSCALE: 1.0
    GLOBAL:
      NGEN_UNIT: 1


LCFIT:
  BASIC:
      BASE: des.nml


CLASSIFICATION:
  SNN:
    CLASSIFIER: SuperNNovaClassifier
    OPTS:
      TRAIN: True
