SIM:

  DES_J17:
    IA_G10:
      BASE: /project2/rkessler/SURVEYS/DES/USERS/mvincenzi/MYINPUT/mv_input/sn_ia_salt2_g10.input
    IAX:
      BASE: sn_iax.input
      DNDZ_ALLSCALE: 3.0
    IA91BG:
      BASE: sn_ia91bg.input
      DNDZ_ALLSCALE: 3.0
    CC_TEMPLATES:
      BASE: sn_collection_jones.input
    GLOBAL:
      FLUXERRMODEL_FILE: /project2/rkessler/SURVEYS/DES/USERS/mvincenzi/MYINPUT/mv_input/Original_DES_ERRORFUDGES.DAT
      NGEN_UNIT: 0.1
      RANSEED_REPEAT: 2 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_1hr.TEMPLATE 2

  DES_RateZ:
    IA_G10: # Starts with IA_
      BASE: sn_ia_salt2_g10.input
    IAX:
      BASE: sn_iax.input
      DNDZ_ALLSCALE: 3.0
    IA91BG:
      BASE: sn_ia91bg.input
      DNDZ_ALLSCALE: 3.0
    II_TEMPLATES:
      BASE: /project2/rkessler/SURVEYS/DES/USERS/mvincenzi/MYINPUT/NON1A_INPUT_FILES/for_pippin/pippin_II_LiRevised_minimized.INPUT
      DNDZ:
        - POWERLAW2 3.9E-5 3.5 0.0 0.4
        - POWERLAW2 1.0E-4 0.5 0.4 1.3
    Ibc_TEMPLATES:
      BASE: /project2/rkessler/SURVEYS/DES/USERS/mvincenzi/MYINPUT/NON1A_INPUT_FILES/for_pippin/pippin_Ibc_LiRevised_minimized.INPUT
      DNDZ:
        - POWERLAW2 2.1E-5 5.5 0.0 0.4
        - POWERLAW2 9.0E-5 1.3 0.4 1.3
    GLOBAL:
      NGEN_UNIT: 0.1
      RANSEED_REPEAT: 2 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_1hr.TEMPLATE 2

