SIM:
  LOWZSIM:
    IA_G10_LOWZ:
      BASE: sn_ia_salt2_g10_lowz.input
    GLOBAL:
      NGEN_UNIT: 1
      RANSEED_REPEAT: 1 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_1hr.TEMPLATE 10

  DESSIM:
    IA_G10_DES3YR:
      BASE: sn_ia_salt2_g10_des3yr.input
    GLOBAL:
      NGEN_UNIT: 1
      RANSEED_REPEAT: 1 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_1hr.TEMPLATE 10

  LOWZBIASCOR:
    IA_G10_LOWZ:
      BASE: sn_ia_salt2_g10_lowz.input
      GENSIGMA_SALT2ALPHA: 1E8  1E8
      GENSIGMA_SALT2BETA: 1E8  1E8
    GLOBAL:
      NGEN_UNIT: 2
      RANSEED_REPEAT: 20 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_1hr.TEMPLATE 10

  LOWZBIASSYS_C11:
    IA_C11_LOWZ:
      BASE: sn_ia_salt2_c11_lowz.input
      GENSIGMA_SALT2ALPHA: 1E8  1E8
      GENSIGMA_SALT2BETA: 1E8  1E8
    GLOBAL:
      NGEN_UNIT: 2
      RANSEED_REPEAT: 20 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_1hr.TEMPLATE 10

  DESBIASCOR:
    IA_G10_DES3YR:
      BASE: sn_ia_salt2_g10_des3yr.input
      GENSIGMA_SALT2ALPHA: 1E8  1E8
      GENSIGMA_SALT2BETA: 1E8  1E8
    GLOBAL:
      NGEN_UNIT: 2
      RANSEED_REPEAT: 20 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_1hr.TEMPLATE 10

  DESBIASSYS_C11:
    IA_C11_DES3YR:
      BASE: sn_ia_salt2_c11_des3yr.input
      GENSIGMA_SALT2ALPHA: 1E8  1E8
      GENSIGMA_SALT2BETA: 1E8  1E8
    GLOBAL:
      NGEN_UNIT: 2
      RANSEED_REPEAT: 20 12345
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_1hr.TEMPLATE 10

LCFIT:
  LOWZFITSYS:
    BASE: lowz.nml
    FITOPTS: test.fitopts
    MASK: LOWZSIM
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_1hr.TEMPLATE 10
  DESFITSYS:
    BASE: des.nml
    FITOPTS: test.fitopts
    MASK: DESSIM
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_1hr.TEMPLATE 10
  LOWZFIT:
    BASE: lowz.nml
    MASK: LOWZBIAS
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_1hr.TEMPLATE 10
  DESFIT:
    BASE: des.nml
    MASK: DESBIAS
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_1hr.TEMPLATE 10

# Note the stuff below does effectively nothing, but allows
# us to treat spec and photometric samples identically
CLASSIFICATION:
  UNITY:
    CLASSIFIER: UnityClassifier
    MODE: predict

AGGREGATION:
  AGG:  # Leaving this blank, no plots or type column

MERGE:
  MERGE: # Leaving the options blank will do the default - all applicable classifiers, sims and fits

BIASCOR:
  BCOR:
    DATA: [DESSIM, LOWZSIM]
    SIMFILE_BIASCOR: [DESBIASCOR, LOWZBIASCOR]
    CLASSIFIER: UNITY
    MUOPTS:
      C11:
        SIMFILE_BIASCOR: [DESBIASSYS_C11, LOWZBIASSYS_C11]
        FITOPT: 0
    OTPS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2_1hr.TEMPLATE 10

CREATE_COV:
  ALL:
    OPTS:
      FITOPT_SCALES:  # Optional
        cal: 2.0  # checks if its in the label, not an exact match
      MUOPT_SCALES: # Optional - used to construct SYSFILE input
        C11: 0.5 # This should exact match a MUOPT label in the biascor step
      COVOPTS:  # note you'll get an 'ALL' covopt no matter what
        - "[NOSYS] [=DEFAULT,=DEFAULT]"
        - "[CALIBRATION] [+cal,=DEFAULT]"
        - "[SCATTER] [=DEFAULT,=C11]"

COSMOMC:
  SN_OMW:
    OPTS:
      INI: sn_omw
      COVOPTS: [ALL, NOSYS]  # If you leave this blank, you get them all. Exact matching

ANALYSE:
  ALL_OMW:
    MASK_COSMOMC: OMW
    OPTS:
      BLIND: w
      COVOPTS: ALL