SIM:
  TRAININGSIM:
    IA_G10:
      BASE: sn_ia_salt2_g10.input
    II_JONES:
      BASE: sn_collection_jones.input
      DNDZ_ALLSCALE: 3.0
    GLOBAL:
      NGEN_UNIT: 0.2
      RANSEED_REPEAT: 10 12345

  TESTSIM:
    IA_C11:
      BASE: sn_ia_salt2_c11.input
    IBC_TEMPLATES:
      BASE: sn_ibc_templates.input
    II_TEMPLATES:
      BASE: sn_ii_templates.input
    GLOBAL:
      NGEN_UNIT: 0.2
      RANSEED_REPEAT: 10 12345

LCFIT:
  TESTFIT:
    BASE: des.nml

CLASSIFICATION:
  SNNTRAIN:
    CLASSIFIER: SuperNNovaClassifier
    MODE: train # train or predict
    MASK: TRAINING
    OPTS:
      USE_PHOTOMETRY: True

  SNNTEST:
    CLASSIFIER: SuperNNovaClassifier
    MODE: predict # train or predict
    MASK: TEST
    OPTS:
      USE_PHOTOMETRY: True
      MODEL: SNNTRAIN  # Can point to a classification task or a saved model file to load

  FITPROBTEST:
    CLASSIFIER: FitProbClassifier
    MODE: predict
    MASK: TEST

AGGREGATION:
  AGG:
    MASK: TEST
    OPTS:
      INCLUDE_TYPE: True
      PLOT: True