# Testing recalibration of ML classification probabilities

SIM:
  TRAININGSIM:
    IA_G10:
      BASE: sn_ia_salt2_g10.input
    II_JONES:
      BASE: sn_collection_jones.input
    GLOBAL:
      NGEN_UNIT: 1
      RANSEED_REPEAT: 10 12345

  TESTSIM:
    IA_C11:
      BASE: sn_ia_salt2_c11.input
    II_MARIA:
      BASE: sn_collection_maria.input
    GLOBAL:
      NGEN_UNIT: 1
      RANSEED_REPEAT: 10 123

  TESTSIM2:
    IA_C11:
      BASE: sn_ia_salt2_c11.input
    II_MARIA:
      BASE: sn_collection_maria.input
    GLOBAL:
      NGEN_UNIT: 1
      RANSEED_REPEAT: 10 321

LCFIT:
  TESTFIT:
    BASE: des.nml

CLASSIFICATION:
  FITPROBTEST:
    CLASSIFIER: FitProbClassifier
    MODE: predict
    MASK: TEST

  SNIRFTRAIN:
    CLASSIFIER: SnirfClassifier
    MODE: train
    MASK_SIM: TRAININGSIM

  SNIRFTEST:
    CLASSIFIER: SnirfClassifier
    MODE: predict
    OPTS:
      MODEL: SNIRFTRAIN

  NNTRAIN:
    CLASSIFIER: NearestNeighborPyClassifier
    MODE: train
    MASK_SIM: TRAININGSIM

  NNTEST:
    CLASSIFIER: NearestNeighborPyClassifier
    MODE: predict
    OPTS:
        MODEL: NNTRAIN



AGGREGATION:
  AGG:
    RECALIBRATION: TESTSIM

MERGE:
  MERGE:
