SIM:
  TRAININGSIM:
    IA_G10:
      BASE: sn_ia_salt2_g10.input
    II_JONES:
      BASE: sn_collection_jones.input
    GLOBAL:
      NGEN_UNIT: 1
      RANSEED_REPEAT: 40 12345

  TESTSIM:
    IA_C11:
      BASE: sn_ia_salt2_c11.input
    IBC_TEMPLATES:
      BASE: sn_ibc_templates.input
    II_TEMPLATES:
      BASE: sn_ii_templates.input
    GLOBAL:
      NGEN_UNIT: 1
      RANSEED_REPEAT: 20 12345

LCFIT:
  TESTFIT:
    BASE: des.nml

CLASSIFICATION:
  SNNTRAIN:
    CLASSIFIER: SuperNNovaClassifier
    MODE: train
    MASK: TRAINING
    OPTS:
      USE_PHOTOMETRY: True

  SNNTRAINLC:
    CLASSIFIER: SuperNNovaClassifier
    MODE: train
    MASK_SIM: TRAINING

  SNNTEST:
    CLASSIFIER: SuperNNovaClassifier
    MODE: predict
    MASK: TEST
    OPTS:
      USE_PHOTOMETRY: True
      MODEL: SNNTRAIN

  SNNTESTLC:
    CLASSIFIER: SuperNNovaClassifier
    MODE: predict
    MASK: TEST
    OPTS:
      USE_PHOTOMETRY: True
      MODEL: SNNTRAINLC

  FITPROBTEST:
    CLASSIFIER: FitProbClassifier
    MODE: predict
    MASK: TEST

  NNTRAIN:
    CLASSIFIER: NearestNeighborClassifier
    MODE: train
    MASK_SIM: TRAINING

  NNTEST:
    CLASSIFIER: NearestNeighborClassifier
    MODE: predict
    MASK_SIM: TEST
    OPTS:
        MODEL: NNTRAIN

AGGREGATION:
  AGG:
    MASK: TEST
    OPTS:
      INCLUDE_TYPE: True
      PLOT: True