SIM:
  TRAININGSIM:
    IA_G10:
      BASE: sn_ia_salt2_g10.input
    II:
      BASE: sn_collection_maria_split_a.input
    GLOBAL:
      NGEN_UNIT: 5
      RANSEED_REPEAT: 40 12345

  TESTSIM:
    IA_C11:
      BASE: sn_ia_salt2_c11.input
    II:
      BASE: sn_collection_maria_split_b.input
    GLOBAL:
      NGEN_UNIT: 3
      RANSEED_REPEAT: 20 12345

LCFIT:
  TESTFIT:
    BASE: des.nml
    SNLCINP:
      USE_MINOS: F

CLASSIFICATION:
  SNNTRAIN:
    CLASSIFIER: SuperNNovaClassifier
    MODE: train
    MASK_SIM: TRAINING
    OPTS:
      NORM: cosmo

  SNNTEST:
    CLASSIFIER: SuperNNovaClassifier
    MODE: predict
    MASK: TEST
    OPTS:
      MODEL: SNNTRAIN
      NORM: cosmo

  SNNVARTRAIN:
    CLASSIFIER: SuperNNovaClassifier
    MODE: train
    MASK_SIM: TRAINING
    OPTS:
      VARIANT: variational
      NORM: cosmo

  SNNVARTEST:
    CLASSIFIER: SuperNNovaClassifier
    MODE: predict
    MASK: TEST
    OPTS:
      MODEL: SNNVARTRAIN
      VARIANT: variational
      NORM: cosmo

  SNNBAYTRAIN:
    CLASSIFIER: SuperNNovaClassifier
    MODE: train
    MASK_SIM: TRAINING
    OPTS:
      VARIANT: bayesian
      NORM: cosmo

  SNNBAYTEST:
    CLASSIFIER: SuperNNovaClassifier
    MODE: predict
    MASK: TEST
    OPTS:
      MODEL: SNNBAYTRAIN
      VARIANT: bayesian
      NORM: cosmo

  FITPROBTEST:
    CLASSIFIER: FitProbClassifier
    MODE: predict
    MASK: TEST

  NNTRAIN:
    CLASSIFIER: NearestNeighborPyClassifier
    MODE: train
    MASK_SIM: TRAINING

  NNTEST:
    CLASSIFIER: NearestNeighborPyClassifier
    MODE: predict
    MASK_SIM: TEST
    OPTS:
        MODEL: NNTRAIN

  SNIRF-TRAIN:
    CLASSIFIER: SnirfClassifier
    MODE: train
    MASK_SIM: TRAINING

  SNIRF-TEST:
    CLASSIFIER: SnirfClassifier
    MODE: predict
    MASK_SIM: TEST
    OPTS:
      MODEL: SNIRF-TRAIN


AGGREGATION:
  AGG:
    MASK: TEST
    OPTS:
      INCLUDE_TYPE: True
      PLOT: True

MERGE:
  MERGE:
    MASK_SIM: TEST
    MASK_FIT: TEST