SIM:
  DES:
    IA_G10:
      BASE: sn_ia_salt2_g10.input
    II_JONES:
      BASE: sn_collection_jones.input
      DNDZ_ALLSCALE: 5.0
    GLOBAL:
      NGEN_UNIT: 3.0
      RANSEED_REPEAT: 40 12345


LCFIT:
  BASIC:
      BASE: des.nml


CLASSIFICATION:
  SNN:
    CLASSIFIER: SuperNNovaClassifier
    MODE: train # train or predict
    OPTS:
      USE_PHOTOMETRY: True
