SIM:
  DES:
    IA_G10:
      BASE: sn_ia_salt2_g10.input
    II_JONES:
      BASE: sn_collection_jones.input
      DNDZ_ALLSCALE: 7.0
    GLOBAL:
      NGEN_UNIT: 15.0
      RANDSEED_REPEAT: 10 12345


LCFIT:
  BASIC:
      BASE: des.nml


CLASSIFICATION:
  SNN:
    CLASSIFIER: SuperNNovaClassifier
    OPTS:
      TRAIN: True
      USE_PHOTOMETRY: True